-- Function: tem.interfaz_fintra_logistica_apoteosys_r_cxc_descuadre()

-- DROP FUNCTION tem.interfaz_fintra_logistica_apoteosys_r_cxc_descuadre();

CREATE OR REPLACE FUNCTION tem.interfaz_fintra_logistica_apoteosys_r_cxc_descuadre()
  RETURNS text AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LOS INGRESOS Y
  *CONTRUYE EL ASIENTO CONTABLE(R) QUE MAS ADELANTE SE TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:= EL ARRAY _ARRCUENTASAET HACE REFERENCIA A LAS CUENTAS PARA
  *REALIZAR LA VERIFICACION DE LAS TRANSACCIONES ASI:
  *13101002,11050508
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-07-11
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_R0 RECORD;
 REC_R1 RECORD;
 REC_R2 RECORD;
 REC_R3 RECORD;
 REC_R RECORD;
 REC_R4 RECORD;
 REC_R5 RECORD;
 REC_R6 RECORD;
 SECUENCIA_R INTEGER;
 CONSEC INTEGER:=1;
 VAL_AET NUMERIC:=0;
 VAL_AGA NUMERIC:=0;
 VAL_EXT NUMERIC:=0;
 PLANILLA_ TEXT:='';
 FECHADOC_ TEXT:='';
 _VAR_CU TEXT:='';
 SW TEXT:='N';
 _ARRCUENTASAET VARCHAR[] :='{13101002,13101001,11050508,13802608}';--IDEAL UN TABLA OJO!!
 MCTYPE CON.TYPE_INSERT_MC;
 CADENA_ TEXT:= '';

BEGIN

--SE CONSULTAN LOS REGISTROS QUE SE VAN A TRANSPORTAR PARA EL BOTON DE INGRESO



			-----------------------------------
			--R CMC->TO Y OT
			-----------------------------------

			FOR REC_R2 IN
				SELECT
					DOCUMENTO,CMC, DESCRIPCION
				FROM
					CON.FACTURA
				WHERE REG_STATUS='' AND DOCUMENTO LIKE 'R0%'
				and documento in('R0036072')
			LOOP

				--IF(REC_R2.CMC='TO')THEN

					--SECUENCIA DE LA R
					SELECT INTO SECUENCIA_R NEXTVAL('CON.INTERFAZ_SECUENCIA_R_APOTEOSYS');
					VAL_AET :=0;
					VAL_AGA :=0;
					VAL_EXT :=0;

					FOR REC_R1 IN
						SELECT
							B.CREATION_DATE,
							A.PERIODO,
							B.CODIGO_CUENTA_CONTABLE AS CUENTA,
							B.VALOR_ITEM,
							--B.NIT,
							CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE B.NIT END AS NIT,
							(CASE
							 WHEN D.TIPO_IDEN='CED' THEN 'CC'
							 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
							 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
							 'CC' END) AS TERCER_CODIGO____TIT____B,
							C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
							(D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
							(D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
							D.NOMBRE AS TERCER_NOMBEXTE__B,
							 (CASE
							 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
							 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
							 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
							 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
							 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
							D.DIRECCION AS TERCER_DIRECCION_B,
							 (CASE
							 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
							 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
							D.TELEFONO AS TERCER_TELEFONO1_B,
							(SELECT TIPO_OPERACION FROM FIN.ANTICIPOS_PAGOS_TERCEROS
							WHERE PLANILLA IN(
							replace(replace(replace(replace(replace(replace(
							(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
							,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
							)
							GROUP BY PLANILLA, TIPO_OPERACION LIMIT 1) AS TIPO,
							(SELECT CASE WHEN CONCEPT_CODE='01' THEN 'AET'
							WHEN CONCEPT_CODE='10' THEN 'AGA'
							WHEN CONCEPT_CODE='50' THEN 'EXT'
							ELSE '' END
							FROM FIN.ANTICIPOS_PAGOS_TERCEROS
						--WHERE PLANILLA IN(SUBSTR(B.DESCRIPCION, 10, CHAR_LENGTH(B.DESCRIPCION)))
						WHERE PLANILLA IN
							(
							replace(replace(replace(replace(replace(replace(
							(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
							,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
							)
							and reg_status='' LIMIT 1) AS CONCEPT_CODE,
							(select CONCEPTO
							from
							tem.homologacion_planillas_concepto
							WHERE
-- 							PLANILLA IN
-- 							(replace(replace(replace(replace(replace(replace(
--  							(B.DESCRIPCION)
--  							,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
-- 							-- replace(replace(replace(replace(replace(replace(
-- -- 							(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
-- -- 							,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
-- 							) AND
							--NUM_INGRESO=REC_OS.NUM_INGRESO AND
							DOCUMENTO=A.DOCUMENTO
							limit 1
							) AS CONCEPT_CODE2,
							SUBSTR(B.DESCRIPCION, 10, CHAR_LENGTH(B.DESCRIPCION)) AS PLANILLA,
							B.DESCRIPCION
						 FROM
							CON.FACTURA A
						INNER JOIN
							CON.FACTURA_DETALLE B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.DOCUMENTO=A.DOCUMENTO)
						LEFT JOIN
							PROVEEDOR C ON(C.NIT=B.NIT)
						LEFT JOIN
							NIT D ON(D.CEDULA=C.NIT)
						LEFT JOIN
							CIUDAD E ON(E.CODCIU=D.CODCIU)
						LEFT JOIN
							CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=B.NIT)
						WHERE
							A.DSTRCT='FINV' AND
							A.TIPO_DOCUMENTO='FAC' AND
							A.DOCUMENTO=REC_R2.DOCUMENTO

					LOOP

						FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_R1.CREATION_DATE,1,7),'-','')=REC_R1.PERIODO THEN REC_R1.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_R1.PERIODO,1,4),SUBSTRING(REC_R1.PERIODO,5,2)::INT)::DATE END ;

						MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
						MCTYPE.MC_____CODIGO____TD_____B := 'CXCN' ;
						MCTYPE.MC_____CODIGO____CD_____B := 'CRLG'  ;
						MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
						MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE  ;
						MCTYPE.MC_____NUMERO____B := SECUENCIA_R  ;
						MCTYPE.MC_____SECUINTE__B := CONSEC  ;
						MCTYPE.MC_____REFERENCI_B := REC_R2.DOCUMENTO;
						MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_R1.PERIODO,1,4)::INT  ;
						MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_R1.PERIODO,5,2)::INT  ;
						MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
						MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_R1.CUENTA,'', 1)  ;
						MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(REC_R1.NIT)>10 THEN SUBSTR(REC_R1.NIT,1,10) ELSE REC_R1.NIT END;
						MCTYPE.MC_____DEBMONORI_B := 0  ;
						MCTYPE.MC_____CREMONORI_B := 0 ;
						MCTYPE.MC_____DEBMONLOC_B := 0;
						MCTYPE.MC_____CREMONLOC_B := REC_R1.VALOR_ITEM;
						VAL_AET :=VAL_AET+REC_R1.VALOR_ITEM;
						RAISE NOTICE 'VALOR ITEM:%',VAL_AET;
						MCTYPE.MC_____CODIGO____CU_____B := 'A1111F21401';
						MCTYPE.MC_____INDTIPMOV_B := 4  ;
						MCTYPE.MC_____INDMOVREV_B := 'N'  ;
						MCTYPE.MC_____OBSERVACI_B := CASE WHEN CHAR_LENGTH(REC_R1.DESCRIPCION)>255 THEN SUBSTR(REC_R1.DESCRIPCION,1,255) ELSE REC_R1.DESCRIPCION END;
						MCTYPE.MC_____FECHORCRE_B := REC_R1.CREATION_DATE::TIMESTAMP  ;
						MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
						MCTYPE.MC_____FEHOULMO__B := REC_R1.CREATION_DATE::TIMESTAMP  ;
						MCTYPE.MC_____AUTULTMOD_B := ''  ;
						MCTYPE.MC_____VALIMPCON_B := 0  ;
						MCTYPE.MC_____NUMERO_OPER_B := REC_R2.DOCUMENTO;
						MCTYPE.TERCER_CODIGO____TIT____B := REC_R1.TERCER_CODIGO____TIT____B  ;
						MCTYPE.TERCER_NOMBCORT__B := SUBSTR(REC_R1.TERCER_NOMBCORT__B,1,32)  ;
						MCTYPE.TERCER_NOMBEXTE__B := SUBSTR(REC_R1.TERCER_NOMBEXTE__B,1,64)  ;
						MCTYPE.TERCER_APELLIDOS_B := SUBSTR(REC_R1.TERCER_APELLIDOS_B,1,32)  ;
						MCTYPE.TERCER_CODIGO____TT_____B := REC_R1.TERCER_CODIGO____TT_____B  ;
						MCTYPE.TERCER_DIRECCION_B := SUBSTR(REC_R1.TERCER_DIRECCION_B,1,64)  ;
						MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_R1.TERCER_CODIGO____CIUDAD_B  ;
						MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_R1.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_R1.TERCER_TELEFONO1_B,1,15) ELSE REC_R1.TERCER_TELEFONO1_B END;
						MCTYPE.TERCER_TIPOGIRO__B := 1 ;
						MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
						MCTYPE.TERCER_SUCURSAL__B := ''  ;
						MCTYPE.TERCER_NUMECUEN__B := ''  ;
						MCTYPE.MC_____CODIGO____DS_____B := '';
						MCTYPE.MC_____NUMDOCSOP_B := '';
						MCTYPE.MC_____NUMEVENC__B := NULL;
						MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
						MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

						--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
						SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
						CONSEC:=CONSEC+1;
						--RAISE NOTICE 'CONSEC 13: %',CONSEC;

					END LOOP;
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', '13802608','', 1);
					--MCTYPE.MC_____CODIGO____CU_____B := 'A1111F22201';
					MCTYPE.MC_____DEBMONLOC_B := VAL_AET::NUMERIC;
					MCTYPE.MC_____CREMONLOC_B := 0;
					MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', '13802608','', 3);
					MCTYPE.MC_____NUMDOCSOP_B := REC_R2.DOCUMENTO;

					IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', '13802608','', 5)::INT=1)THEN
						MCTYPE.MC_____NUMEVENC__B := 1;
					ELSE
						MCTYPE.MC_____NUMEVENC__B := NULL;
					END IF;

					MCTYPE.MC_____FECHEMIS__B=FECHADOC_::DATE  ;
					MCTYPE.MC_____FECHVENC__B=FECHADOC_::DATE  ;

					--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;
					-----------------------------------------

					--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
					IF CON.SP_VALIDACIONES(MCTYPE,'LOGISTICA') ='N' THEN
						SW='N';

						--BORRAMOS EL COMPROBANTE DE ING
						DELETE FROM CON.MC____
						WHERE MC_____NUMERO____B = SECUENCIA_R AND MC_____CODIGO____CONTAB_B = 'FINT'
						 AND MC_____CODIGO____TD_____B = 'CXCN' AND  MC_____CODIGO____CD_____B = 'CRLG'  ;

						CONTINUE;
					END IF;

				--END IF;

			END LOOP;


	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION tem.interfaz_fintra_logistica_apoteosys_r_cxc_descuadre()
  OWNER TO postgres;
