-- Function: tem.interfaz_sl_contratista_cc_selectrik_apoteosys()

-- DROP FUNCTION tem.interfaz_sl_contratista_cc_selectrik_apoteosys();

CREATE OR REPLACE FUNCTION tem.interfaz_sl_contratista_cc_selectrik_apoteosys()
  RETURNS SETOF con.type_insert_mc AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION:
  *AUTOR		:=		@BTERRAZA
  *FECHA CREACION	:=ŕo 2018-04-12
  *LAST_UPDATE		:=
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/

_DOC RECORD;
INFOITEMS_ RECORD;
INFOCLIENTE RECORD;
LONGITUD NUMERIC;
SECUENCIA_GEN INTEGER;
SECUENCIA_INT INTEGER:= 1;
CUENTAS_IVA VARCHAR[] := '{}';
FECHADOC_ VARCHAR:= '';
MCTYPE CON.TYPE_INSERT_MC;
SW TEXT:='N';
VALIDACIONES TEXT;
CUOTA_INICIAL VARCHAR;
_EXISTE CHARACTER VARYING :='';
INFO_FECHAS RECORD;
_fecha boolean :=false;

BEGIN

	FOR _DOC IN

		SELECT
			A.TIPO_DOCUMENTO,
			A.FECHA_DOCUMENTO AS FECHA_FACTURA,
			A.FECHA_VENCIMIENTO,
			A.PERIODO,
			A.PROVEEDOR AS NIT,
			C.ID_SOLICITUD,
			C.ID_CLIENTE,
			CL.NIT AS NIT_CLIENTE,
			B.ID_ACCION,
			C.CENTRO_COSTOS_INGRESO,
			C.CENTRO_COSTOS_GASTOS,
			A.DESCRIPCION,
			C.NUM_OS,
			A.DOCUMENTO,
			B.CONTRATISTA, a.descripcion
		FROM FIN.CXP_DOC AS A
		INNER JOIN PROVEEDOR AS PRV ON (A.PROVEEDOR=PRV.NIT)
		INNER JOIN OPAV.ACCIONES AS B ON (A.REFERENCIA_1 = B.ID_ACCION)
		INNER JOIN OPAV.OFERTAS AS C ON (B.ID_SOLICITUD = C.ID_SOLICITUD)
		inner join cliente as CL on (CL.CODCLI=C.ID_CLIENTE)
		WHERE
			TIPO_DOCUMENTO		=	'FAP'
			AND HANDLE_CODE		=	'CI'
			--AND PERIODO		=	'201712'
			AND A.REG_STATUS	=	''
			AND C.CENTRO_COSTOS_INGRESO !=  ''
			AND DOCUMENTO 		LIKE 	'CC%'
			AND DOCUMENTO 		in 	 ('CC011-002227')
			AND COALESCE(PROCESADO, 'N' ) = 'N'


-- SELECT con.interfaz_sl_contratista_cc_selectrik_apoteosys()

	LOOP
		SELECT INTO SECUENCIA_GEN  NEXTVAL('CON.INTERFAZ_SECUENCIA_CXP_APOTEOSYS');

		MCTYPE.MC_____CODIGO____CONTAB_B := 'SELE';
		MCTYPE.MC_____CODIGO____TD_____B := 'CXPN';
		MCTYPE.MC_____CODIGO____CD_____B := 'CCSL';
		MCTYPE.MC_____NUMERO____B := SECUENCIA_GEN;

		_fecha:=false;

		/**BUSCAMOS LA INFORMACION COMPLETA QUE CONFORMARA EL ASIENTO CONTABLE PARA MANDARLO A APOTEOSYS*/
		FOR INFOITEMS_ IN
				  (
				    SELECT
						FACD.TIPO_DOCUMENTO,
						FACD.CODIGO_CUENTA_CONTABLE AS CUENTA,
						case when trim(substring(FACD.descripcion,1,16)) ='Bonificacion' THEN _DOC.NIT_CLIENTE ELSE _DOC.NIT END AS NIT,
						CASE WHEN FACD.VALOR_UNITARIO > 0 THEN FACD.VALOR_UNITARIO ELSE 0 END AS  VALOR_DEB,
						CASE WHEN FACD.VALOR_UNITARIO < 0 THEN FACD.VALOR_UNITARIO * -1 ELSE 0 END AS VALOR_CREDT,
						FACD.DESCRIPCION,
						FACD.DOCUMENTO
					FROM
						   CON.FACTURA FAC
					INNER JOIN CON.FACTURA_DETALLE FACD ON ( FACD.DSTRCT = FAC.DSTRCT AND FACD.TIPO_DOCUMENTO = FACD.TIPO_DOCUMENTO AND FACD.DOCUMENTO = FAC.DOCUMENTO )
					WHERE
						SUBSTRING(FACD.DOCUMENTO,1,2) = 'NM'
						AND FACD.REG_STATUS = ''
						and FAC.REG_STATUS=''
						AND FACD.REFERENCIA_1 =_DOC.ID_ACCION
						AND FACD.CODIGO_CUENTA_CONTABLE in ('28151001','28151006')

				  )
					UNION ALL
				  (
					--ESTE PASO SIMPRE ES BONIFICACION Y VA EN CABEZA DEL CLIENTE
					SELECT
						TIPO_DOCUMENTO,
						CODIGO_CUENTA AS CUENTA,
						_DOC.NIT_CLIENTE AS NIT,
						CASE WHEN VLR>0 THEN VLR ELSE 0 END AS  VALOR_DEB,
						CASE WHEN VLR<0 THEN VLR*-1 ELSE 0 END AS VALOR_CREDT,
						DESCRIPCION,
						DOCUMENTO
					FROM FIN.CXP_ITEMS_DOC
					WHERE  TIPO_DOCUMENTO='FAP' AND
						REG_STATUS = '' AND
						DOCUMENTO = _DOC.DOCUMENTO AND
						CODIGO_CUENTA = 'I010120064142' AND
						PROVEEDOR = _DOC.NIT

					UNION ALL

					SELECT
						CXP.TIPO_DOCUMENTO,
						CMC.CUENTA,
						CXP.PROVEEDOR AS NIT,
						0::NUMERIC AS VALOR_DEB,
						ROUND(CXP.VLR_NETO) AS VALOR_CREDT,
						CXP.DESCRIPCION,
						CXP.DOCUMENTO
					FROM FIN.CXP_DOC CXP
					INNER JOIN CON.CMC_DOC CMC ON (CMC.CMC=CXP.HANDLE_CODE AND CMC.TIPODOC=CXP.TIPO_DOCUMENTO)
					WHERE CXP.TIPO_DOCUMENTO='FAP' AND
					      CXP.REG_STATUS = ''  AND
					      CXP.DOCUMENTO =  _DOC.DOCUMENTO AND
					      CXP.PROVEEDOR = _DOC.NIT
				)

		LOOP

			--FECHA DOCUMENTO
			IF(INFOITEMS_.DOCUMENTO LIKE 'NM%' and _fecha=false)THEN

				FECHADOC_:=coalesce((SELECT MC_____FECHA_____B::DATE
				FROM CON.MC_SL_FAC_SEL
				WHERE MC_____NUMDOCSOP_B=INFOITEMS_.DOCUMENTO
				AND MC_____CODIGO____CD_____B='NMSL'
				AND MC_____CODIGO____CPC____B=CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL', 'FAP', INFOITEMS_.CUENTA,'', 1)
				AND MC_____IDENTIFIC_TERCER_B=SUBSTRING(REPLACE(INFOITEMS_.NIT,'-',''),1,9)
				GROUP BY MC_____FECHA_____B), _DOC.FECHA_FACTURA);

				RAISE NOTICE 'FECHA DOCUMENTO: %',replace(substring(FECHADOC_,1,7),'-','');
				RAISE NOTICE 'XXXXXXXXXX: %',_DOC.PERIODO;

				if(replace(substring(FECHADOC_,1,7),'-','') !=_DOC.PERIODO)then
					FECHADOC_:= _DOC.FECHA_FACTURA;
				end if;

				IF( _DOC.FECHA_VENCIMIENTO::DATE<FECHADOC_::DATE)THEN
					 _DOC.FECHA_VENCIMIENTO:=FECHADOC_;
				END IF;

				_fecha:=true;

			END IF;


			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','FAP', INFOITEMS_.CUENTA,'', 6)='S')THEN

				MCTYPE.MC_____FECHVENC__B = _DOC.FECHA_VENCIMIENTO; --FECHA VENCIMIENTO
				MCTYPE.MC_____FECHEMIS__B = FECHADOC_;



			-- 	IF (_DOC.FECHA_VENCIMIENTO < _DOC.FECHA_FACTURA)THEN /** SE VALIDA SI LA FECHA DE VENCIMEINTO ES MENOR A LA DE CREACION*/
-- 					MCTYPE.MC_____FECHEMIS__B = _DOC.FECHA_VENCIMIENTO; --FECHA CREACION
-- 				ELSE
-- 					MCTYPE.MC_____FECHEMIS__B = _DOC.FECHA_FACTURA; --FECHA CREACION
-- 				END IF;

			ELSE
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
 			END IF;

			--Busca la informacion cuando es un cliente
			IF (INFOITEMS_.DESCRIPCION LIKE 'Bonificacion %' AND INFOITEMS_.CUENTA IN ('I010120064142','28151001')) THEN
				raise notice 'debe entrar dos veces';
				SELECT INTO INFOCLIENTE
						'NIT' AS TIPO_DOC,
						'GCON'::TEXT AS CODIGO,
						(CASE
						WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
						ELSE '08001' END)::TEXT AS CODIGOCIU,
						NOMCLI::TEXT AS NOMBRE_CORTO,
						NOMCLI AS  NOMBRE,
						''::TEXT AS APELLIDOS,
						DIRECCION,
						TELEFONO,
						NIT
					FROM CLIENTE CL
					LEFT JOIN CIUDAD E ON(E.CODCIU=CL.CIUDAD)
					WHERE CODCLI =  _DOC.ID_CLIENTE
					AND NIT= INFOITEMS_.NIT;

			ELSE

				SELECT INTO INFOCLIENTE
					'NIT' AS TIPO_DOC,
					(CASE
					WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='N' THEN 'RCOM'
					WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='S' THEN 'RCAU'
					WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='N' THEN 'GCON'
					WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='S' THEN 'GCAU'
					ELSE 'PNAL' END) AS CODIGO,
					'08001'::TEXT AS CODIGOCIU,
					COALESCE((D.NOMBRE1||' '||D.NOMBRE2),PAYMENT_NAME) AS NOMBRE_CORTO,
					PAYMENT_NAME AS  NOMBRE,
					(D.APELLIDO1||' '||D.APELLIDO2) AS APELLIDOS,
					COALESCE(DIRECCION, '-' ) as DIRECCION,
					COALESCE(TELEFONO, '-') AS TELEFONO

				FROM PROVEEDOR PROV
				LEFT JOIN NIT D ON(D.CEDULA=PROV.NIT)
				LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
				WHERE NIT = _DOC.NIT;

			END IF;


			MCTYPE.MC_____FECHA_____B :=FECHADOC_;
			MCTYPE.MC_____SECUINTE__DCD____B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____SECUINTE__B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____REFERENCI_B := _DOC.ID_ACCION; --_DOC.ID_ACCION  _DOC.NUM_OS---CAMBIAR A MULTISERVICIO...
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING( _DOC.PERIODO,1,4)::INT;
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING( _DOC.PERIODO,5,2)::INT;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF';
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL', 'FAP', INFOITEMS_.CUENTA,'', 1);
			MCTYPE.MC_____CODIGO____CU_____B := _DOC.CENTRO_COSTOS_INGRESO;
			MCTYPE.MC_____IDENTIFIC_TERCER_B :=  SUBSTRING(REPLACE(INFOITEMS_.NIT,'-',''),1,9);
			MCTYPE.MC_____DEBMONORI_B := 0;
			MCTYPE.MC_____CREMONORI_B := 0;
			MCTYPE.MC_____DEBMONLOC_B := INFOITEMS_.VALOR_DEB::NUMERIC;
			MCTYPE.MC_____CREMONLOC_B := INFOITEMS_.VALOR_CREDT::NUMERIC;
			MCTYPE.MC_____INDTIPMOV_B := 4;
			MCTYPE.MC_____INDMOVREV_B := 'N';
			MCTYPE.MC_____OBSERVACI_B := SUBSTRING(INFOITEMS_.DESCRIPCION,1,249);
			MCTYPE.MC_____FECHORCRE_B := _DOC.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN';
			MCTYPE.MC_____FEHOULMO__B := _DOC.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTULTMOD_B := '';
			MCTYPE.MC_____VALIMPCON_B := 0;
			MCTYPE.MC_____NUMERO_OPER_B := '';
			MCTYPE.TERCER_CODIGO____TIT____B := INFOCLIENTE.TIPO_DOC;
			MCTYPE.TERCER_NOMBCORT__B := SUBSTRING(INFOCLIENTE.NOMBRE_CORTO,1,32);
			MCTYPE.TERCER_NOMBEXTE__B := SUBSTRING(INFOCLIENTE.NOMBRE,1,64);
			MCTYPE.TERCER_APELLIDOS_B := INFOCLIENTE.APELLIDOS;
			MCTYPE.TERCER_CODIGO____TT_____B := INFOCLIENTE.CODIGO;
			MCTYPE.TERCER_DIRECCION_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.DIRECCION)>64 THEN SUBSTR(INFOCLIENTE.DIRECCION,1,64) ELSE INFOCLIENTE.DIRECCION END;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := INFOCLIENTE.CODIGOCIU;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.TELEFONO)>15 THEN SUBSTR(INFOCLIENTE.TELEFONO,1,15) ELSE INFOCLIENTE.TELEFONO END;
			MCTYPE.TERCER_TIPOGIRO__B := 1;
			MCTYPE.TERCER_CODIGO____EF_____B := '';
			MCTYPE.TERCER_SUCURSAL__B := '';
			MCTYPE.TERCER_NUMECUEN__B := '';
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','FAP', INFOITEMS_.CUENTA,'', 3);
			MCTYPE.MC_____BASE______B:=0;

			IF(MCTYPE.MC_____FECHEMIS__B > MCTYPE.MC_____FECHA_____B) THEN
				MCTYPE.MC_____FECHEMIS__B :=  MCTYPE.MC_____FECHA_____B;
			END IF;


			IF(INFOITEMS_.CUENTA = ANY (CUENTAS_IVA))THEN
				IF(INFOITEMS_.VALOR_CREDT>0) THEN
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_CREDT/0.19;
				ELSE
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_DEB/0.19;
				END IF;
			END IF;

			MCTYPE.MC_____NUMDOCSOP_B := INFOITEMS_.DOCUMENTO;


			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL', 'FAP', INFOITEMS_.CUENTA,'', 5)::INT=1)THEN
				MCTYPE.MC_____NUMEVENC__B := 1;--NUMERO DE CUOTAS
			ELSE
				MCTYPE.MC_____NUMEVENC__B := NULL;
			END IF;


			RAISE NOTICE 'CC ====>>>> %',INFOITEMS_.CUENTA;
			--SW := CON.SP_INSERT_TABLE_MC_SL_FAC_CC_SEL(MCTYPE);
			SECUENCIA_INT :=SECUENCIA_INT+1;

			return next MCTYPE;

		END LOOP;

		RAISE NOTICE '<<<<==== TERMINO ====>>>> %',_DOC.DOCUMENTO;


		-- IF CON.SP_VALIDACIONES_SEL(MCTYPE,'FAC_CC') ='N' THEN
-- 			SW = 'N';
-- 			CONTINUE;
-- 		END IF;

		IF(SW = 'S')THEN
-- 	 	      UPDATE  FIN.CXP_DOC  SET PROCESADO = 'S'
-- 			WHERE DOCUMENTO  = _DOC.DOCUMENTO AND
-- 			      TIPO_DOCUMENTO = 'FAP' AND
-- 			      HANDLE_CODE =	'CI'  and
-- 			      REG_STATUS = ''	and
-- 			      PROVEEDOR = _DOC.NIT ;
		END IF;

		SECUENCIA_INT:=1;

	END LOOP;


--RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION tem.interfaz_sl_contratista_cc_selectrik_apoteosys()
  OWNER TO postgres;
