-- Function: tem.valida_descuadre_notas_ajuste(character varying, character varying, character varying, character varying)

-- DROP FUNCTION tem.valida_descuadre_notas_ajuste(character varying, character varying, character varying, character varying);

CREATE OR REPLACE FUNCTION tem.valida_descuadre_notas_ajuste(_ia_interes character varying, _ia_seguro character varying, _tipo character varying, _negocio character varying)
  RETURNS numeric AS
$BODY$
DECLARE

  _DIFERENCIA NUMERIC:=0.00;

BEGIN


SELECT  INTO _DIFERENCIA
       (VALOR_CONCEPTO-VALOR_APLICADO) AS DIFERENCIA
FROM (
	SELECT
	       ESTADO_CUOTA,
	       DESCRIPCION,
	       VALOR_CONCEPTO,
	       CASE WHEN ESTADO_CUOTA='PAGADA'  THEN  0.00
		  WHEN ESTADO_CUOTA='REVERSADA' AND DESCRIPCION IN ('CAPITAL') THEN 0.00
		  WHEN ESTADO_CUOTA='REVERSADA' AND DESCRIPCION IN ('INTERES') THEN VALOR_REVERSADO_INTERES
		  WHEN ESTADO_CUOTA='REVERSADA' AND DESCRIPCION IN ('SEGURO') THEN VALOR_REVERSADO_SEGURO
		ELSE 0.00 END AS VALOR_APLICADO

	FROM (
		SELECT ESTADO_CUOTA,
		       -- CUOTA::INTEGER,
-- 		       DOCUMENTO_SOPORTE,
		       DESCRIPCION,
		       SUM(VALOR_UNITARIO) AS VALOR_CONCEPTO,
		       CASE WHEN _tipo='SEGURO' THEN
		           (SELECT VLR_INGRESO FROM CON.INGRESO  WHERE NUM_INGRESO=_IA_SEGURO AND TIPO_DOCUMENTO='ICA' AND REG_STATUS='')
		       ELSE 0.00 END AS VALOR_REVERSADO_SEGURO, --INGRESOS SEGURTO
		       CASE WHEN _tipo='INTERES' THEN
		         (SELECT VLR_INGRESO FROM CON.INGRESO  WHERE NUM_INGRESO=_IA_INTERES AND TIPO_DOCUMENTO='ICA' AND REG_STATUS='' )
		       ELSE 0.00 END AS VALOR_REVERSADO_INTERES --INGRESO INTERES
		 FROM (
		SELECT
		       CASE WHEN ING.REG_STATUS='' THEN 'PAGADA' ELSE 'REVERSADA' END AS ESTADO_CUOTA,
		       FAC.NUM_DOC_FEN AS CUOTA,
		       CASE WHEN   FDET.DESCRIPCION='INTERES' THEN ING.COD ELSE  FAC.DOCUMENTO END AS DOCUMENTO_SOPORTE,
		       FDET.DESCRIPCION,
		       FDET.VALOR_UNITARIO
		 FROM ING_FENALCO ING
		INNER JOIN CON.FACTURA FAC ON (ING.FECHA_DOC=FAC.FECHA_VENCIMIENTO AND ING.CODNEG=FAC.NEGASOC)
		INNER JOIN CON.FACTURA_DETALLE FDET ON (FDET.DOCUMENTO=FAC.DOCUMENTO AND FAC.TIPO_DOCUMENTO=FDET.TIPO_DOCUMENTO)
		WHERE CODNEG =_negocio AND FDET.REG_STATUS=''
		) T
		GROUP BY
		ESTADO_CUOTA,
		-- CUOTA::INTEGER,
	        -- DOCUMENTO_SOPORTE,
		DESCRIPCION
		--ORDER BY ESTADO_CUOTA
	)T2
	WHERE ESTADO_CUOTA='REVERSADA' AND DESCRIPCION =_TIPO
)T3;


RAISE NOTICE '_DIFERENCIA :% ',_DIFERENCIA;

RETURN _DIFERENCIA;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION tem.valida_descuadre_notas_ajuste(character varying, character varying, character varying, character varying)
  OWNER TO postgres;
