-- Table: opav.sl_apoteosys_tabla_maestra

-- DROP TABLE opav.sl_apoteosys_tabla_maestra;

CREATE TABLE opav.sl_apoteosys_tabla_maestra
(
  id serial NOT NULL,
  ord_emp_empresa character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  ord_orden integer NOT NULL DEFAULT 0,
  ord_orden_interna character varying(20) NOT NULL DEFAULT ''::character varying,
  ord_fecha timestamp without time zone DEFAULT now(),
  ord_pro_proveedor character varying(16) NOT NULL DEFAULT ''::character varying,
  ord_pro_mon_moneda character varying(6) NOT NULL DEFAULT ''::character varying,
  ord_doc_documento character varying(6) NOT NULL DEFAULT ''::character varying,
  ord_documento character varying(10) NOT NULL DEFAULT ''::character varying,
  ord_tipo_orden character varying(1) NOT NULL DEFAULT 'I'::character varying,
  ord_tipo character varying(3) NOT NULL DEFAULT ''::character varying,
  ord_status character varying(3) NOT NULL DEFAULT ''::character varying,
  ord_cpa_condicion character varying(6) NOT NULL DEFAULT ''::character varying,
  ord_cpa_condicion2 character varying(6) NOT NULL DEFAULT ''::character varying,
  ord_cmp_comprador character varying(6) NOT NULL DEFAULT ''::character varying,
  ord_cat_categoria character varying(10) NOT NULL DEFAULT ''::character varying,
  ord_subtotal numeric(18,4),
  ord_pct_descuento_global numeric(8,4),
  ord_descuento numeric(18,4),
  ord_otro_impuesto numeric(18,4),
  ord_iva numeric(18,4),
  ord_total numeric(18,4),
  ord_autorizado character varying(1) NOT NULL DEFAULT 'N'::character varying,
  ord_fecha_autorizacion timestamp without time zone DEFAULT now(),
  rd_autorizado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  ord_verificacion character varying(1) NOT NULL DEFAULT 'N'::character varying,
  ord_creado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  ord_fecha_creacion timestamp without time zone DEFAULT now(),
  ord_modificado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  ord_fecha_modificacion timestamp without time zone DEFAULT now(),
  ord_dep_departamento character varying(20) NOT NULL DEFAULT ''::character varying,
  ord_ant_incluyeiva character varying(1) NOT NULL DEFAULT ''::character varying,
  ord_indejepre character varying(1) NOT NULL DEFAULT 'S'::character varying,
  ord_indcarini character varying(1) NOT NULL DEFAULT ''::character varying,
  ord_valotasa numeric(12,7),
  ord_reparable character varying(1) NOT NULL DEFAULT ''::character varying,
  ord_percamest character varying(1) NOT NULL DEFAULT ''::character varying,
  dor_ord_emp_empresa character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  dor_ord_orden integer,
  dor_linea integer,
  dor_sum_emp_empresa character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  dor_sum_suministro character varying(15) NOT NULL DEFAULT ''::character varying,
  dor_descripcion character varying(100) NOT NULL DEFAULT ''::character varying,
  dor_descripcion_alterna character varying(100) NOT NULL DEFAULT ''::character varying,
  dor_status character varying(2) NOT NULL DEFAULT ''::character varying,
  dor_cantidad_pedida numeric(17,2) DEFAULT 0,
  dor_cantidad_recibida numeric(17,2) DEFAULT 0,
  dor_cantidad_backorder numeric(17,2) DEFAULT 0,
  dor_cantidad_desecho numeric(17,2) DEFAULT 0,
  dor_cantidad_reclamo numeric(17,2) DEFAULT 0,
  dor_costo_fob numeric(18,4) DEFAULT 0,
  dor_descuento_linea numeric(8,4) DEFAULT 0,
  dor_descuento_monto numeric(18,4) DEFAULT 0,
  dor_otros_impuesto_monto numeric(18,4) DEFAULT 0,
  dor_impuesto_venta_monto numeric(18,4) DEFAULT 0,
  dor_total_linea numeric(18,4) DEFAULT 0,
  dor_med_medida_cantidad_medida character varying(6) NOT NULL DEFAULT ''::character varying,
  dor_creado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  dor_fecha_creacion timestamp without time zone DEFAULT now(),
  dor_incluir_anulacion character varying(1) NOT NULL DEFAULT 'N'::character varying,
  dor_cantidad_devuelta numeric(17,2) DEFAULT 0,
  dor_dep_emp_empresa character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  dor_dep_departamento character varying(20) NOT NULL DEFAULT ''::character varying,
  dor_pordes numeric(6,2) DEFAULT 0,
  dor_iva_simplificado numeric(18,4) DEFAULT 0,
  dpc_despacho numeric(10,0),
  dpc_emp_empresa_despacho character varying(6) NOT NULL DEFAULT ''::character varying,
  dpc_fecha timestamp without time zone DEFAULT now(),
  dpc_ord_emp_empresa character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  dpc_ord_orden integer,
  dpc_lcg_localizacion character varying(6) NOT NULL DEFAULT 'SELE'::character varying,
  dpc_creado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  dpc_fecha_creacion timestamp without time zone DEFAULT now(),
  dpc_dep_departamento character varying(20) NOT NULL DEFAULT ''::character varying,
  ddf_dpc_despacho numeric(10,0),
  ddf_linea numeric(10,0),
  ddf_dor_ord_emp_empresa character varying(6),
  ddf_dor_ord_orde numeric(10,0),
  ddf_dor_linea numeric(10,0),
  ddf_cantidad numeric(17,2) DEFAULT 0,
  ddf_cantidad_recibida numeric(17,2) DEFAULT 0,
  ddf_cantidad_backorder numeric(17,2) DEFAULT 0,
  ddf_cantidad_liquidada numeric(17,2) DEFAULT 0,
  ddf_creado_por character varying(30) NOT NULL DEFAULT ''::character varying,
  ddf_fecha_creacion timestamp without time zone DEFAULT now(),
  ddf_cantidad_devuelta numeric(17,2) DEFAULT 0,
  ddf_cancelado character varying(30) DEFAULT 'N'::character varying,
  ddf_dep_emp_empresa character varying(6),
  ddf_dep_departamento character varying(20),
  tercer_codigo____tit____b character varying(4),
  tercer_nombcort__b character varying(32),
  tercer_nombexte__b character varying(64),
  tercer_apellidos_b character varying(32),
  tercer_codigo____tt_____b character varying(4),
  tercer_direccion_b character varying(64),
  tercer_codigo____ciudad_b character varying(8),
  tercer_telefono1_b character varying(16),
  tercer_tipogiro__b numeric(1,0),
  tercer_sucursal__b character varying(16),
  id_sl_apoteosys_fase_oc integer,
  procesado character varying(1) DEFAULT 'N'::character varying
)
WITH (
  OIDS=FALSE
);
ALTER TABLE opav.sl_apoteosys_tabla_maestra
  OWNER TO postgres;
