

  -- View: opav_bkp.acciones_view_dblink

-- DROP VIEW opav_bkp.acciones_view_dblink;

CREATE OR REPLACE VIEW opav_bkp.acciones_view_dblink AS 
 SELECT acciones_view_dblink.id_accion, acciones_view_dblink.id_solicitud, acciones_view_dblink.estado, acciones_view_dblink.contratista, acciones_view_dblink.material, acciones_view_dblink.mano_obra, acciones_view_dblink.transporte, acciones_view_dblink.administracion, acciones_view_dblink.imprevisto, acciones_view_dblink.utilidad, acciones_view_dblink.porc_administracion, acciones_view_dblink.porc_imprevisto, acciones_view_dblink.porc_utilidad, acciones_view_dblink.descripcion, acciones_view_dblink.user_update, acciones_view_dblink.creation_user, acciones_view_dblink.reg_status, acciones_view_dblink.observaciones, acciones_view_dblink.tipo_trabajo, acciones_view_dblink.creation_date, acciones_view_dblink.last_update, acciones_view_dblink.alcances, acciones_view_dblink.adicionales, acciones_view_dblink.trabajo, acciones_view_dblink.fec_visita_planeada, acciones_view_dblink.fec_visita_hecha, acciones_view_dblink.user_visita_hecha, acciones_view_dblink.creation_fec_visita_hecha, acciones_view_dblink.aviso, acciones_view_dblink.factura_cliente, acciones_view_dblink.parcial, acciones_view_dblink.bonificacion, acciones_view_dblink.opav, acciones_view_dblink.fintra, acciones_view_dblink.interventoria, acciones_view_dblink.provintegral, acciones_view_dblink.eca, acciones_view_dblink.base_iva_contratista, acciones_view_dblink.iva_contratista, acciones_view_dblink.iva_bonificacion, acciones_view_dblink.iva_opav, acciones_view_dblink.iva_fintra, acciones_view_dblink.iva_interventoria, acciones_view_dblink.iva_provintegral, acciones_view_dblink.iva_eca, acciones_view_dblink.financiar_sin_iva, acciones_view_dblink.iva, acciones_view_dblink.financiar_con_iva, acciones_view_dblink.prefacturar, acciones_view_dblink.exestado, acciones_view_dblink.fecha_finalizacion, acciones_view_dblink.fecha_interventoria, acciones_view_dblink.observacion_recepcion, acciones_view_dblink.fec_creacion_recepcion, acciones_view_dblink.user_recepcion, acciones_view_dblink.prefacturar_contratista, acciones_view_dblink.prefactura_contratista, acciones_view_dblink.usuario_prefactura_contratista, acciones_view_dblink.factura_contratista, acciones_view_dblink.usuario_factura_contratista, acciones_view_dblink.factura_contratista_fintra, acciones_view_dblink.cod_iva_contratista, acciones_view_dblink.por_iva_contratista, acciones_view_dblink.val_base_iva_contratista, acciones_view_dblink.val_iva_contratista, acciones_view_dblink.cod_ret_material_contratista, acciones_view_dblink.por_ret_material_contratista, acciones_view_dblink.val_ret_mano_obra_contratista, acciones_view_dblink.val_ret_material_contratista, acciones_view_dblink.cod_ret_mano_obra_contratista, acciones_view_dblink.por_ret_mano_obra_contratista, acciones_view_dblink.cod_ret_otros_contratista, acciones_view_dblink.por_ret_otros_contratista, acciones_view_dblink.val_ret_otros_contratista, acciones_view_dblink.por_factoring_contratista, acciones_view_dblink.val_formula_contratista, acciones_view_dblink.val_factoring_contratista, acciones_view_dblink.por_formula_contratista, acciones_view_dblink.cod_ret_ica_contratista, acciones_view_dblink.por_ret_ica_contratista, acciones_view_dblink.val_ret_ica_contratista, acciones_view_dblink.cod_ret_iva_contratista, acciones_view_dblink.por_ret_iva_contratista, acciones_view_dblink.val_ret_iva_contratista, acciones_view_dblink.cod_ret_aiu_contratista, acciones_view_dblink.por_ret_aiu_contratista, acciones_view_dblink.val_ret_aiu_contratista, acciones_view_dblink.fact_conformada, acciones_view_dblink.fecha_factura_contratista, acciones_view_dblink.nota_credito_contratista, acciones_view_dblink.fecha_nota_credito_contratista, acciones_view_dblink.fecha_factura_contratista_final, acciones_view_dblink.fi_provintegral, acciones_view_dblink.liquidacion, acciones_view_dblink.informe, acciones_view_dblink.acta, acciones_view_dblink.fecha_documentacion, acciones_view_dblink.fecha_informe, acciones_view_dblink.fecha_liquidacion, acciones_view_dblink.fecha_acta, acciones_view_dblink.creation_fecha_factura_contratista, acciones_view_dblink.fc_provintegral, acciones_view_dblink.ff_provintegral, acciones_view_dblink.nc_provintegral, acciones_view_dblink.ft_provintegral, acciones_view_dblink.fc_fintra, acciones_view_dblink.fc_opav, acciones_view_dblink.dstrct, acciones_view_dblink.accion_principal, acciones_view_dblink.preparar_facturacion, acciones_view_dblink.facturado
   FROM dblink('dbname=selectrik port=5432 host=localhost user=postgres password=bdversion7'::text, '
			SELECT  
				  id_accion,
				  id_solicitud,
				  estado,
				  contratista,
				  material,
				  mano_obra,
				  transporte,
				  administracion,
				  imprevisto,
				  utilidad,
				  porc_administracion,
				  porc_imprevisto,
				  porc_utilidad,
				  descripcion,
				  user_update,
				  creation_user,
				  reg_status,
				  observaciones,
				  tipo_trabajo,
				  creation_date,
				  last_update,
				  alcances,
				  adicionales,
				  trabajo,
				  fec_visita_planeada,
				  fec_visita_hecha,
				  user_visita_hecha,
				  creation_fec_visita_hecha,
				  aviso,
				  factura_cliente,
				  parcial,
				  bonificacion,
				  opav,
				  fintra,
				  interventoria,
				  provintegral,
				  eca,
				  base_iva_contratista,
				  iva_contratista,
				  iva_bonificacion,
				  iva_opav,
				  iva_fintra,
				  iva_interventoria,
				  iva_provintegral,
				  iva_eca,
				  financiar_sin_iva,
				  iva,
				  financiar_con_iva,
				  prefacturar,
				  exestado,
				  fecha_finalizacion,
				  fecha_interventoria,
				  observacion_recepcion,
				  fec_creacion_recepcion,
				  user_recepcion,
				  prefacturar_contratista,
				  prefactura_contratista,
				  usuario_prefactura_contratista,
				  factura_contratista,
				  usuario_factura_contratista,
				  factura_contratista_fintra,
				  cod_iva_contratista,
				  por_iva_contratista,
				  val_base_iva_contratista,
				  val_iva_contratista,
				  cod_ret_material_contratista,
				  por_ret_material_contratista,
				  val_ret_mano_obra_contratista,
				  val_ret_material_contratista,
				  cod_ret_mano_obra_contratista,
				  por_ret_mano_obra_contratista,
				  cod_ret_otros_contratista,
				  por_ret_otros_contratista,
				  val_ret_otros_contratista,
				  por_factoring_contratista,
				  val_formula_contratista,
				  val_factoring_contratista,
				  por_formula_contratista,
				  cod_ret_ica_contratista,
				  por_ret_ica_contratista,
				  val_ret_ica_contratista,
				  cod_ret_iva_contratista,
				  por_ret_iva_contratista,
				  val_ret_iva_contratista,
				  cod_ret_aiu_contratista,
				  por_ret_aiu_contratista,
				  val_ret_aiu_contratista,
				  fact_conformada,
				  fecha_factura_contratista,
				  nota_credito_contratista,
				  fecha_nota_credito_contratista,
				  fecha_factura_contratista_final,
				  fi_provintegral,
				  liquidacion,
				  informe,
				  acta,
				  fecha_documentacion,
				  fecha_informe,
				  fecha_liquidacion,
				  fecha_acta,
				  creation_fecha_factura_contratista,
				  fc_provintegral,
				  ff_provintegral,
				  nc_provintegral,
				  ft_provintegral ,
				  fc_fintra,
				  fc_opav,
				  dstrct,
				  accion_principal,
				  preparar_facturacion,
				  facturado
			FROM opav.acciones where reg_status = ''''; 
			;
		'::text) acciones_view_dblink(id_accion character varying, id_solicitud character varying, estado character varying, contratista character varying, material numeric, mano_obra numeric, transporte numeric, administracion numeric, imprevisto numeric, utilidad numeric, porc_administracion numeric, porc_imprevisto numeric, porc_utilidad numeric, descripcion text, user_update character varying, creation_user character varying, reg_status character varying, observaciones text, tipo_trabajo character varying, creation_date timestamp without time zone, last_update timestamp without time zone, alcances text, adicionales text, trabajo text, fec_visita_planeada timestamp without time zone, fec_visita_hecha timestamp without time zone, user_visita_hecha character varying, creation_fec_visita_hecha timestamp without time zone, aviso character varying, factura_cliente character varying, parcial integer, bonificacion numeric, opav numeric, fintra numeric, interventoria numeric, provintegral numeric, eca numeric, base_iva_contratista numeric, iva_contratista numeric, iva_bonificacion numeric, iva_opav numeric, iva_fintra numeric, iva_interventoria numeric, iva_provintegral numeric, iva_eca numeric, financiar_sin_iva numeric, iva numeric, financiar_con_iva numeric, prefacturar character varying, exestado character varying, fecha_finalizacion timestamp without time zone, fecha_interventoria timestamp without time zone, observacion_recepcion text, fec_creacion_recepcion timestamp without time zone, user_recepcion character varying, prefacturar_contratista character varying, prefactura_contratista character varying, usuario_prefactura_contratista character varying, factura_contratista character varying, usuario_factura_contratista character varying, factura_contratista_fintra character varying, cod_iva_contratista character varying, por_iva_contratista numeric, val_base_iva_contratista numeric, val_iva_contratista numeric, cod_ret_material_contratista character varying, por_ret_material_contratista numeric, val_ret_mano_obra_contratista numeric, val_ret_material_contratista numeric, cod_ret_mano_obra_contratista character varying, por_ret_mano_obra_contratista numeric, cod_ret_otros_contratista character varying, por_ret_otros_contratista numeric, val_ret_otros_contratista numeric, por_factoring_contratista numeric, val_formula_contratista numeric, val_factoring_contratista numeric, por_formula_contratista numeric, cod_ret_ica_contratista character varying, por_ret_ica_contratista numeric, val_ret_ica_contratista numeric, cod_ret_iva_contratista character varying, por_ret_iva_contratista numeric, val_ret_iva_contratista numeric, cod_ret_aiu_contratista character varying, por_ret_aiu_contratista numeric, val_ret_aiu_contratista numeric, fact_conformada character varying, fecha_factura_contratista timestamp without time zone, nota_credito_contratista character varying, fecha_nota_credito_contratista timestamp without time zone, fecha_factura_contratista_final timestamp without time zone, fi_provintegral character varying, liquidacion character varying, informe character varying, acta character varying, fecha_documentacion timestamp without time zone, fecha_informe timestamp without time zone, fecha_liquidacion timestamp without time zone, fecha_acta timestamp without time zone, creation_fecha_factura_contratista timestamp without time zone, fc_provintegral character varying, ff_provintegral timestamp without time zone, nc_provintegral character varying, ft_provintegral timestamp without time zone, fc_fintra character varying, fc_opav character varying, dstrct character varying, accion_principal character varying, preparar_facturacion character varying, facturado character varying);

ALTER TABLE opav_bkp.acciones_view_dblink
  OWNER TO postgres;

