-- View: opav_bkp.ofertas_view_dblink

-- DROP VIEW opav_bkp.ofertas_view_dblink;

CREATE OR REPLACE VIEW opav_bkp.ofertas_view_dblink AS 
 SELECT sl_ofertas_dblink.id_solicitud, sl_ofertas_dblink.id_cliente, sl_ofertas_dblink.id_oferta, sl_ofertas_dblink.num_os, sl_ofertas_dblink.descripcion, sl_ofertas_dblink.last_update, sl_ofertas_dblink.creation_date, sl_ofertas_dblink.creation_user, sl_ofertas_dblink.user_update, sl_ofertas_dblink.reg_status, sl_ofertas_dblink.nic, sl_ofertas_dblink.fecha_entrega_oferta, sl_ofertas_dblink.creacion_fecha_entrega_oferta, sl_ofertas_dblink.usuario_entrega_oferta, sl_ofertas_dblink.tipo_solicitud, sl_ofertas_dblink.tipodistribucion, sl_ofertas_dblink.noesvaloragregado, sl_ofertas_dblink.nombre_solicitud, sl_ofertas_dblink.user_oferta, sl_ofertas_dblink.fecha_oferta, sl_ofertas_dblink.consecutivo_oferta, sl_ofertas_dblink.otras_consideraciones, sl_ofertas_dblink.consideraciones, sl_ofertas_dblink.esoficial, sl_ofertas_dblink.otras_anulaciones, sl_ofertas_dblink.user_generate, sl_ofertas_dblink.aviso, sl_ofertas_dblink.fecha_validacion_cartera, sl_ofertas_dblink.estudio_cartera, sl_ofertas_dblink.interventor, sl_ofertas_dblink.responsable, sl_ofertas_dblink.comentario, sl_ofertas_dblink.fecha_inicial_oferta, sl_ofertas_dblink.dstrct, sl_ofertas_dblink.num_os_rel, sl_ofertas_dblink.nombre_proyecto, sl_ofertas_dblink.trazabilidad, sl_ofertas_dblink.estado, sl_ofertas_dblink.tipo_proyecto, sl_ofertas_dblink.nuevo_modulo, sl_ofertas_dblink.id_tipo_trabajo, sl_ofertas_dblink.id_tipo_negocio, sl_ofertas_dblink.centro_costos_ingreso, sl_ofertas_dblink.centro_costos_gastos
   FROM dblink('dbname=selectrik port=5432 host=localhost user=postgres password=bdversion7'::text, '
			select 
				id_solicitud ,  id_cliente ,  id_oferta ,  num_os ,  descripcion  ,  last_update ,  creation_date ,  creation_user ,  user_update ,  reg_status ,  nic ,  fecha_entrega_oferta  ,  creacion_fecha_entrega_oferta  ,  usuario_entrega_oferta ,  tipo_solicitud ,  tipodistribucion ,  noesvaloragregado ,  nombre_solicitud ,  user_oferta ,  fecha_oferta  ,  consecutivo_oferta ,  otras_consideraciones  ,  consideraciones  ,  esoficial ,  otras_anulaciones ,  user_generate ,  aviso ,  fecha_validacion_cartera  ,  estudio_cartera ,  interventor ,  responsable ,  comentario  ,  fecha_inicial_oferta  ,  dstrct ,  num_os_rel ,  nombre_proyecto ,  trazabilidad ,  estado ,  tipo_proyecto ,  nuevo_modulo ,  id_tipo_trabajo ,  id_tipo_negocio ,  centro_costos_ingreso ,  centro_costos_gastos 
			from opav.ofertas
			where  reg_status = ''''  and tipo_proyecto !=''TPR00006''
			;
		'::text) sl_ofertas_dblink(id_solicitud character varying, id_cliente character varying, id_oferta character varying, num_os character varying, descripcion text, last_update timestamp without time zone, creation_date timestamp without time zone, creation_user character varying, user_update character varying, reg_status character varying, nic character varying, fecha_entrega_oferta timestamp without time zone, creacion_fecha_entrega_oferta timestamp without time zone, usuario_entrega_oferta character varying, tipo_solicitud character varying, tipodistribucion character varying, noesvaloragregado integer, nombre_solicitud character varying, user_oferta character varying, fecha_oferta timestamp without time zone, consecutivo_oferta character varying, otras_consideraciones text, consideraciones text, esoficial character varying, otras_anulaciones text, user_generate character varying, aviso character varying, fecha_validacion_cartera timestamp without time zone, estudio_cartera character varying, interventor character varying, responsable character varying, comentario text, fecha_inicial_oferta timestamp without time zone, dstrct character varying, num_os_rel character varying, nombre_proyecto character varying, trazabilidad character varying, estado integer, tipo_proyecto character varying, nuevo_modulo integer, id_tipo_trabajo integer, id_tipo_negocio integer, centro_costos_ingreso character varying, centro_costos_gastos character varying);

ALTER TABLE opav_bkp.ofertas_view_dblink
  OWNER TO postgres;	

