-- Table: con.factura_prueba

-- DROP TABLE con.factura_prueba;

CREATE TABLE con.factura_prueba
(
  reg_status character varying(1) NOT NULL DEFAULT ''::character varying,
  dstrct character varying(4) NOT NULL DEFAULT ''::character varying,
  tipo_documento character varying(5) NOT NULL DEFAULT ''::character varying,
  documento character varying(10) NOT NULL DEFAULT ''::character varying,
  nit character varying(15) DEFAULT ''::character varying,
  codcli character varying(10) NOT NULL DEFAULT ''::character varying,
  concepto character varying(6) NOT NULL DEFAULT ''::character varying,
  fecha_factura date DEFAULT '0099-01-01'::date,
  fecha_vencimiento date DEFAULT '0099-01-01'::date,
  fecha_ultimo_pago date DEFAULT '0099-01-01'::date,
  fecha_impresion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  descripcion text NOT NULL DEFAULT ''::text,
  observacion text NOT NULL DEFAULT ''::text,
  valor_factura moneda,
  valor_abono moneda,
  valor_saldo moneda,
  valor_facturame moneda,
  valor_abonome moneda,
  valor_saldome moneda,
  valor_tasa numeric(15,6) NOT NULL DEFAULT 0,
  moneda character varying(3) NOT NULL DEFAULT ''::character varying,
  cantidad_items numeric NOT NULL DEFAULT 0,
  forma_pago character varying(15) DEFAULT ''::character varying,
  agencia_facturacion character varying(6) DEFAULT ''::character varying,
  agencia_cobro character varying(6) DEFAULT ''::character varying,
  zona character varying(10) DEFAULT ''::character varying,
  clasificacion1 character varying(6) DEFAULT ''::character varying,
  clasificacion2 character varying(6) DEFAULT ''::character varying,
  clasificacion3 character varying(6) DEFAULT ''::character varying,
  transaccion integer NOT NULL DEFAULT 0,
  transaccion_anulacion integer NOT NULL DEFAULT 0,
  fecha_contabilizacion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  fecha_anulacion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  fecha_contabilizacion_anulacion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  base character varying(3) NOT NULL DEFAULT ''::character varying,
  last_update timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  user_update character varying(10) NOT NULL DEFAULT ''::character varying,
  creation_date timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  creation_user character varying(10) NOT NULL DEFAULT ''::character varying,
  fecha_probable_pago date DEFAULT '0099-01-01'::date,
  flujo character varying(1) NOT NULL DEFAULT 'S'::character varying,
  rif character varying(20) NOT NULL DEFAULT ''::character varying,
  cmc character varying(6) NOT NULL DEFAULT ''::character varying,
  usuario_anulo character varying(15) NOT NULL DEFAULT ''::character varying,
  formato character varying(6) NOT NULL DEFAULT ''::character varying,
  agencia_impresion character varying(6) NOT NULL DEFAULT ''::character varying,
  periodo character varying(6) NOT NULL DEFAULT ''::character varying,
  valor_tasa_remesa numeric(15,6) NOT NULL DEFAULT 0,
  negasoc character varying(15) NOT NULL DEFAULT ''::character varying,
  num_doc_fen character varying(20) DEFAULT '0'::character varying,
  obs character varying(3) NOT NULL DEFAULT '0'::character varying,
  pagado_fenalco character varying(15),
  corficolombiana character varying(1) DEFAULT ''::character varying,
  tipo_ref1 character varying(50) DEFAULT ''::character varying,
  ref1 text DEFAULT ''::character varying,
  tipo_ref2 character varying(50) DEFAULT ''::character varying,
  ref2 text DEFAULT ''::text,
  dstrct_ultimo_ingreso character varying(4) NOT NULL DEFAULT ''::character varying,
  tipo_documento_ultimo_ingreso character varying(5) NOT NULL DEFAULT ''::character varying,
  num_ingreso_ultimo_ingreso character varying(11) NOT NULL DEFAULT ''::character varying,
  item_ultimo_ingreso integer NOT NULL DEFAULT 0,
  fec_envio_fiducia timestamp without time zone DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  nit_enviado_fiducia character varying,
  tipo_referencia_1 character varying(5) NOT NULL DEFAULT ''::character varying,
  referencia_1 character varying(30) NOT NULL DEFAULT ''::character varying,
  tipo_referencia_2 character varying(5) NOT NULL DEFAULT ''::character varying,
  referencia_2 character varying(30) NOT NULL DEFAULT ''::character varying,
  tipo_referencia_3 character varying(5) NOT NULL DEFAULT ''::character varying,
  referencia_3 character varying(30) NOT NULL DEFAULT ''::character varying,
  nc_traslado character varying(1) NOT NULL DEFAULT 'N'::character varying,
  fecha_nc_traslado timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  tipo_nc character varying(5) NOT NULL DEFAULT ''::character varying,
  numero_nc character varying(11) NOT NULL DEFAULT ''::character varying,
  factura_traslado character varying(10) NOT NULL DEFAULT ''::character varying,
  factoring_formula_aplicada character varying(1) NOT NULL DEFAULT 'N'::character varying,
  nit_endoso character varying(15) NOT NULL DEFAULT ''::character varying,
  devuelta character varying(1) NOT NULL DEFAULT ''::character varying,
  fc_eca character varying(15) DEFAULT ''::character varying,
  fc_bonificacion character varying(15) DEFAULT ''::character varying,
  indicador_bonificacion character varying(1) DEFAULT ''::character varying,
  fi_bonificacion character varying(15) DEFAULT ''::character varying
)
WITH (
  OIDS=TRUE
);
ALTER TABLE con.factura_prueba
  OWNER TO postgres;
GRANT ALL ON TABLE con.factura_prueba TO postgres;
GRANT SELECT ON TABLE con.factura_prueba TO msoto;

