-- Function: apicredit.eg_clonar_solicitud_aval(integer, numeric, character varying, character varying)

-- DROP FUNCTION apicredit.eg_clonar_solicitud_aval(integer, numeric, character varying, character varying);

CREATE OR REPLACE FUNCTION apicredit.eg_clonar_solicitud_aval(_numerosolicitud integer, _valoraval numeric, _negocio character varying, usuario character varying)
  RETURNS text AS
$BODY$
DECLARE
  nuevoNumeroSolicitud integer:=0;
  retorno text:='OK';
BEGIN
     --nuevo numero de solicitud para el aval
     nuevoNumeroSolicitud:=get_lcod('SOLICITUD_AVAL');

     INSERT INTO solicitud_aval
                        (reg_status,
                         dstrct,
                         numero_solicitud,
                         fecha_consulta,
                         valor_solicitado,
                         agente,
                         afiliado,
                         codigo,
                         numero_aprobacion,
                         estado_sol,
                         tipo_persona,
                         valor_aprobado,
                         tipo_negocio,
                         num_tipo_negocio,
                         banco,
                         sucursal,
                         num_chequera,
                         cod_neg,
                         creation_date,
                         creation_user,
                         last_update,
                         user_update,
                         id_convenio,
                         producto,
                         servicio,
                         ciudad_matricula,
                         valor_producto,
                         asesor,
                         cod_sector,
                         cod_subsector,
                         plazo,
                         plazo_pr_cuota,
                         ciudad_cheque)
            (SELECT reg_status,
                    dstrct,
                    nuevoNumeroSolicitud,
                    fecha_consulta,
                    _valorAval,
                    agente,
                    afiliado,
                    codigo,
                    numero_aprobacion,
                    estado_sol,
                    tipo_persona,
                    _valorAval,
                    tipo_negocio,
                    num_tipo_negocio,
                    banco,
                    sucursal,
                    num_chequera,
                    _negocio,
                    creation_date,
                    creation_user,
                    last_update,
                    user_update,
                    id_convenio,
                    producto,
                    servicio,
                    ciudad_matricula,
                    _valorAval,
                    asesor,
                    cod_sector,
                    cod_subsector,
                    plazo,
                    plazo_pr_cuota,
                    ciudad_cheque
             FROM   solicitud_aval
             WHERE  numero_solicitud =_numeroSolicitud);


    -- solicitud_bienes
        INSERT INTO solicitud_bienes
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo,
                     secuencia,
                     tipo_de_bien,
                     hipoteca,
                     a_favor_de,
                     valor_comercial,
                     direccion,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo,
                secuencia,
                tipo_de_bien,
                hipoteca,
                a_favor_de,
                valor_comercial,
                direccion,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_bienes
         WHERE  numero_solicitud =_numeroSolicitud);

        --solicitud_cuentas
        INSERT INTO solicitud_cuentas
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     consecutivo,
                     tipo,
                     banco,
                     cuenta,
                     fecha_apertura,
                     numero_tarjeta,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                consecutivo,
                tipo,
                banco,
                cuenta,
                fecha_apertura,
                numero_tarjeta,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_cuentas
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_estudiante
        INSERT INTO solicitud_estudiante
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     parentesco_girador,
                     universidad,
                     programa,
                     fecha_ingreso_programa,
                     codigo,
                     semestre,
                     valor_semestre,
                     tipo_carrera,
                     trabaja,
                     nombre_empresa,
                     direccion_empresa,
                     telefono_empresa,
                     salario,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                parentesco_girador,
                universidad,
                programa,
                fecha_ingreso_programa,
                codigo,
                semestre,
                valor_semestre,
                tipo_carrera,
                trabaja,
                nombre_empresa,
                direccion_empresa,
                telefono_empresa,
                salario,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_estudiante
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_hijos
        INSERT INTO solicitud_hijos
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo,
                     secuencia,
                     nombre,
                     direccion,
                     telefono,
                     edad,
                     email,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo,
                secuencia,
                nombre,
                direccion,
                telefono,
                edad,
                email,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_hijos
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_laboral
        INSERT INTO solicitud_laboral
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo,
                     ocupacion,
                     actividad_economica,
                     nombre_empresa,
                     nit,
                     direccion,
                     ciudad,
                     departamento,
                     telefono,
                     extension,
                     cargo,
                     fecha_ingreso,
                     tipo_contrato,
                     salario,
                     celular,
                     email,
                     eps,
                     tipo_afiliacion,
                     direccion_cobro,
                     otros_ingresos,
                     concepto_otros_ing,
                     gastos_manutencion,
                     gastos_creditos,
                     gastos_arriendo,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo,
                ocupacion,
                actividad_economica,
                nombre_empresa,
                nit,
                direccion,
                ciudad,
                departamento,
                telefono,
                extension,
                cargo,
                fecha_ingreso,
                tipo_contrato,
                salario,
                celular,
                email,
                eps,
                tipo_afiliacion,
                direccion_cobro,
                otros_ingresos,
                concepto_otros_ing,
                gastos_manutencion,
                gastos_creditos,
                gastos_arriendo,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_laboral
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_negocio
        INSERT INTO solicitud_negocio
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     cod_sector,
                     cod_subsector,
                     nombre,
                     direccion,
                     departamento,
                     ciudad,
                     barrio,
                     telefono,
                     tiempo_local,
                     num_exp_negocio,
                     tiempo_microempresario,
                     num_trabajadores,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                cod_sector,
                cod_subsector,
                nombre,
                direccion,
                departamento,
                ciudad,
                barrio,
                telefono,
                tiempo_local,
                num_exp_negocio,
                tiempo_microempresario,
                num_trabajadores,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_negocio
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_persona
        INSERT INTO solicitud_persona
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo_persona,
                     tipo,
                     codcli,
                     primer_apellido,
                     segundo_apellido,
                     primer_nombre,
                     segundo_nombre,
                     nombre,
                     ciudad,
                     genero,
                     estado_civil,
                     direccion,
                     departamento,
                     barrio,
                     identificacion,
                     tipo_id,
                     fecha_expedicion_id,
                     ciudad_expedicion_id,
                     dpto_expedicion_id,
                     fecha_nacimiento,
                     ciudad_nacimiento,
                     dpto_nacimiento,
                     nivel_estudio,
                     profesion,
                     personas_a_cargo,
                     num_de_hijos,
                     total_grupo_familiar,
                     estrato,
                     tiempo_residencia,
                     tipo_vivienda,
                     telefono,
                     celular,
                     email,
                     telefono2,
                     primer_apellido_cony,
                     segundo_apellido_cony,
                     primer_nombre_cony,
                     segundo_nombre_cony,
                     tipo_id_cony,
                     id_cony,
                     empresa_cony,
                     direccion_cony,
                     telefono_cony,
                     salario_cony,
                     celular_cony,
                     email_cony,
                     cargo_cony,
                     ciiu,
                     fax,
                     tipo_empresa,
                     fecha_constitucion,
                     representante_legal,
                     genero_representante,
                     tipo_id_representante,
                     id_representante,
                     firmador_cheques,
                     genero_firmador,
                     tipo_id_firmador,
                     id_firmador,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo_persona,
                tipo,
                codcli,
                primer_apellido,
                segundo_apellido,
                primer_nombre,
                segundo_nombre,
                nombre,
                ciudad,
                genero,
                estado_civil,
                direccion,
                departamento,
                barrio,
                identificacion,
                tipo_id,
                fecha_expedicion_id,
                ciudad_expedicion_id,
                dpto_expedicion_id,
                fecha_nacimiento,
                ciudad_nacimiento,
                dpto_nacimiento,
                nivel_estudio,
                profesion,
                personas_a_cargo,
                num_de_hijos,
                total_grupo_familiar,
                estrato,
                tiempo_residencia,
                tipo_vivienda,
                telefono,
                celular,
                email,
                telefono2,
                primer_apellido_cony,
                segundo_apellido_cony,
                primer_nombre_cony,
                segundo_nombre_cony,
                tipo_id_cony,
                id_cony,
                empresa_cony,
                direccion_cony,
                telefono_cony,
                salario_cony,
                celular_cony,
                email_cony,
                cargo_cony,
                ciiu,
                fax,
                tipo_empresa,
                fecha_constitucion,
                representante_legal,
                genero_representante,
                tipo_id_representante,
                id_representante,
                firmador_cheques,
                genero_firmador,
                tipo_id_firmador,
                id_firmador,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_persona
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_referencias
        INSERT INTO solicitud_referencias
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo,
                     tipo_referencia,
                     secuencia,
                     nombre,
                     primer_apellido,
                     segundo_apellido,
                     primer_nombre,
                     segundo_nombre,
                     telefono1,
                     telefono2,
                     extension,
                     celular,
                     email,
                     direccion,
                     ciudad,
                     departamento,
                     tiempo_conocido,
                     parentesco,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo,
                tipo_referencia,
                secuencia,
                nombre,
                primer_apellido,
                segundo_apellido,
                primer_nombre,
                segundo_nombre,
                telefono1,
                telefono2,
                extension,
                celular,
                email,
                direccion,
                ciudad,
                departamento,
                tiempo_conocido,
                parentesco,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_referencias
         WHERE  numero_solicitud = _numeroSolicitud);

        --solicitud_vehiculo
        INSERT INTO solicitud_vehiculo
                    (reg_status,
                     dstrct,
                     numero_solicitud,
                     tipo,
                     secuencia,
                     marca,
                     tipo_vehiculo,
                     placa,
                     modelo,
                     valor_comercial,
                     cuota_mensual,
                     pignorado_a_favor_de,
                     creation_date,
                     creation_user,
                     last_update,
                     user_update)
        (SELECT reg_status,
                dstrct,
                nuevoNumeroSolicitud,
                tipo,
                secuencia,
                marca,
                tipo_vehiculo,
                placa,
                modelo,
                valor_comercial,
                cuota_mensual,
                pignorado_a_favor_de,
                creation_date,
                creation_user,
                last_update,
                user_update
         FROM   solicitud_vehiculo
         WHERE  numero_solicitud = _numeroSolicitud);


	/* ************************************
	* Documentos del formulario    *****
	**************************************/

	INSERT INTO solicitud_documentos(
	    numero_solicitud, num_titulo,valor, fecha,liquidacion,creation_user,creation_date,last_update)

	(
	 SELECT
		nuevoNumeroSolicitud,
		cuota ,
		valor_cuota,
		fecha,
		1,
		usuario,
		now(),
		now()
	FROM apicredit.pre_liquidacion_creditos_aval  where numero_solicitud=_numeroSolicitud
	);

	 /* ****************************************
	  * Actualizar el formulario aval  *********
	  *****************************************/

	UPDATE solicitud_aval SET
		user_update=usuario,
		last_update=now(),
		cod_neg=_negocio,
		estado_sol='P'
	WHERE numero_solicitud = nuevoNumeroSolicitud;


	return retorno;

EXCEPTION
	WHEN unique_violation THEN
	RAISE EXCEPTION 'Error Insertando en la bd, ya existe en la base de datos.';
	retorno='FAIL' ;
	return retorno;


END;$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION apicredit.eg_clonar_solicitud_aval(integer, numeric, character varying, character varying)
  OWNER TO postgres;
