-- Table: app_accord

-- DROP TABLE app_accord;

CREATE TABLE app_accord
(
  id_accion character varying(12) NOT NULL,
  id_orden numeric(10,0) NOT NULL,
  consecutivo character varying(30),
  id_contratista character varying(5) NOT NULL,
  acciones character varying(250) NOT NULL,
  total_prev1 numeric(15,0),
  last_update_finv timestamp without time zone,
  fecha_envio_ws timestamp without time zone,
  fecha_registro timestamp without time zone NOT NULL,
  por_actualizar numeric(1,0) NOT NULL DEFAULT 0,
  prefactura character varying(15) NOT NULL DEFAULT ''::character varying,
  total_prev1_mat numeric(15,0) DEFAULT 0,
  total_prev1_mob numeric(15,0) DEFAULT 0,
  total_prev1_otr numeric(15,0) DEFAULT 0,
  comision_ejecutiva numeric(8,0) NOT NULL DEFAULT 0,
  comision_canal numeric(8,0) NOT NULL DEFAULT 0,
  codigo_iva character varying(6) NOT NULL DEFAULT ''::character varying,
  vlr_iva moneda NOT NULL DEFAULT 0,
  fecha_prefactura timestamp without time zone DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  prefactura_user character varying(10) NOT NULL DEFAULT ''::character varying,
  fact_conformada character varying(40) NOT NULL DEFAULT ''::character varying,
  eca_oferta numeric(15,2) NOT NULL DEFAULT 0,
  oferta numeric(15,2) NOT NULL DEFAULT 0,
  f_facturado_cliente character varying(20) DEFAULT '0099-01-01'::character varying,
  codigo_rmat character varying(6) NOT NULL DEFAULT ''::character varying,
  codigo_rmob character varying(6) NOT NULL DEFAULT ''::character varying,
  codigo_rotr character varying(6) NOT NULL DEFAULT ''::character varying,
  vlr_rmat moneda NOT NULL DEFAULT 0,
  vlr_rmob moneda NOT NULL DEFAULT 0,
  vlr_rotr moneda NOT NULL DEFAULT 0,
  porcentaje_iva numeric(5,2) NOT NULL DEFAULT 0,
  porcentaje_rmat numeric(5,2) NOT NULL DEFAULT 0,
  porcentaje_rmob numeric(5,2) NOT NULL DEFAULT 0,
  porcentaje_rotr numeric(5,2) NOT NULL DEFAULT 0,
  valor_factoring numeric(15,2) NOT NULL DEFAULT 0,
  porcentaje_formula numeric(5,2) NOT NULL DEFAULT 0,
  valor_formula numeric(15,2) NOT NULL DEFAULT 0,
  administracion numeric(15,2) NOT NULL DEFAULT 0,
  imprevisto numeric(15,2) NOT NULL DEFAULT 0,
  utilidad numeric(15,2) NOT NULL DEFAULT 0,
  base_iva numeric(15,2) NOT NULL DEFAULT 0.00,
  factura_contratista character varying(20) NOT NULL DEFAULT ''::character varying,
  fecha_factura_contratista timestamp without time zone DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  factura_retencion character varying(20) NOT NULL DEFAULT ''::character varying,
  fecha_factura_retencion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  factura_bonificacion character varying(20) NOT NULL DEFAULT ''::character varying,
  fecha_factura_bonificacion timestamp without time zone NOT NULL DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  e_total_prev1 moneda NOT NULL DEFAULT 0,
  e_iva_total_prev1 moneda NOT NULL DEFAULT 0,
  e_comision_applus moneda NOT NULL DEFAULT 0,
  e_comision_provintegral moneda NOT NULL DEFAULT 0,
  e_comision_fintra moneda NOT NULL DEFAULT 0,
  e_iva_comision_applus moneda NOT NULL DEFAULT 0,
  e_iva_comision_provintegral moneda NOT NULL DEFAULT 0,
  e_iva_comision_fintra moneda NOT NULL DEFAULT 0,
  e_comision_eca moneda NOT NULL DEFAULT 0,
  e_eca_oferta_calculada moneda NOT NULL DEFAULT 0,
  e_financiacion_fintra moneda NOT NULL DEFAULT 0,
  e_cuotas_reales numeric(3,0) NOT NULL DEFAULT 0,
  e_dtf_semana numeric(7,4) NOT NULL DEFAULT 0,
  e_porcentaje_factoring numeric(7,4) NOT NULL DEFAULT 0,
  e_fecha_financiacion date NOT NULL DEFAULT '0099-01-01'::date,
  e_cuota_pago moneda NOT NULL DEFAULT 0,
  e_porcentaje_comision_applus numeric(7,4) NOT NULL DEFAULT 0,
  e_porcentaje_comision_provintegral numeric(7,4) NOT NULL DEFAULT 0,
  e_porcentaje_comision_fintra numeric(7,4) NOT NULL DEFAULT 0,
  e_porcentaje_comision_eca numeric(7,4) NOT NULL DEFAULT 0,
  e_porcentaje_iva numeric(7,4) NOT NULL DEFAULT 0,
  e_iva_comision_eca moneda NOT NULL DEFAULT 0,
  e_comision_factoring_fintra moneda NOT NULL DEFAULT 0,
  e_iva_comision_factoring_fintra moneda NOT NULL DEFAULT 0,
  e_porcentaje_factoring_fintra numeric(7,4) NOT NULL DEFAULT 0,
  e_puntos_dtf numeric(7,4) NOT NULL DEFAULT 0,
  total_financiacion moneda NOT NULL DEFAULT 0,
  ec_porcentaje_iva numeric(7,4) NOT NULL DEFAULT 0,
  ec_porcentaje_comision_provintegral numeric(7,4) NOT NULL DEFAULT 0,
  ec_porcentaje_factoring_fintra numeric(7,4) NOT NULL DEFAULT 0,
  ec_porcentaje_comision_applus numeric(7,4) NOT NULL DEFAULT 0,
  ec_porcentaje_comision_fintra numeric(7,4) NOT NULL DEFAULT 0,
  ec_porcentaje_comision_eca numeric(7,4) NOT NULL DEFAULT 0,
  ec_valor_mat moneda NOT NULL DEFAULT 0,
  ec_comision_applus moneda NOT NULL DEFAULT 0,
  ec_comision_provintegral moneda NOT NULL DEFAULT 0,
  ec_comision_factoring_fintra moneda NOT NULL DEFAULT 0,
  ec_comision_fintra moneda NOT NULL DEFAULT 0,
  ec_comision_eca moneda NOT NULL DEFAULT 0,
  ec_iva_valor_mat moneda NOT NULL DEFAULT 0,
  ec_iva_comision_applus moneda NOT NULL DEFAULT 0,
  ec_iva_comision_factoring_fintra moneda NOT NULL DEFAULT 0,
  ec_iva_comision_fintra moneda NOT NULL DEFAULT 0,
  ec_iva_comision_provintegral moneda NOT NULL DEFAULT 0,
  ec_iva_comision_eca moneda NOT NULL DEFAULT 0,
  ec_financiacion_fintra moneda NOT NULL DEFAULT 0,
  ec_cuota_pago moneda NOT NULL DEFAULT 0,
  ec_total_financiacion moneda NOT NULL DEFAULT 0,
  exprefactura character varying(15) NOT NULL DEFAULT ''::character varying,
  valor_formula_provintegral numeric(15,2) NOT NULL DEFAULT 0,
  factura_formula_provintegral character varying(20) NOT NULL DEFAULT ''::character varying,
  fecha_factura_formula_provintegral timestamp without time zone DEFAULT '0099-01-01 00:00:00'::timestamp without time zone,
  cxc_ab character varying(25) DEFAULT ''::character varying,
  cxc_pf character varying(25) DEFAULT ''::character varying,
  cxc_ar character varying(25) DEFAULT ''::character varying,
  iva_bonificacion moneda DEFAULT 0,
  dstrct character varying(4) NOT NULL DEFAULT ''::character varying
)
WITH (
  OIDS=FALSE
);
ALTER TABLE app_accord
  OWNER TO postgres;
GRANT ALL ON TABLE app_accord TO postgres;
GRANT SELECT ON TABLE app_accord TO msoto;

