-- Table: importacion_applus

-- DROP TABLE importacion_applus;

CREATE TABLE importacion_applus
(
  num_os character varying(10) NOT NULL DEFAULT ''::character varying,
  id_orden character varying(10) NOT NULL DEFAULT ''::character varying,
  consecutivo character varying(40) NOT NULL DEFAULT ''::character varying,
  mes character varying(40) NOT NULL DEFAULT ''::character varying,
  f_recepcion character varying(25) NOT NULL DEFAULT ''::character varying,
  f_ejecucion_orden character varying(25) NOT NULL DEFAULT ''::character varying,
  f_contratista character varying(25) NOT NULL DEFAULT ''::character varying,
  pedido_sga character varying(10) NOT NULL DEFAULT ''::character varying,
  servicios character varying(10) NOT NULL DEFAULT ''::character varying,
  forma_pago_1 character varying(45) NOT NULL DEFAULT ''::character varying,
  observaciones text NOT NULL DEFAULT ''::text,
  sector character varying(30) NOT NULL DEFAULT ''::character varying,
  tipo_orden character varying(30) NOT NULL DEFAULT ''::character varying,
  auditoria character varying(3) NOT NULL DEFAULT ''::character varying,
  facturado_1 character varying(3) NOT NULL DEFAULT ''::character varying,
  id_zona character varying(3) NOT NULL DEFAULT ''::character varying,
  ejecutivo_cuenta character varying(45) NOT NULL DEFAULT ''::character varying,
  id_cliente character varying(10) NOT NULL DEFAULT ''::character varying,
  nic character varying(10) NOT NULL DEFAULT ''::character varying,
  cliente character varying(60) NOT NULL DEFAULT ''::character varying,
  tipo_clientes character varying(3) NOT NULL DEFAULT ''::character varying,
  contacto character varying(45) NOT NULL DEFAULT ''::character varying,
  cargo character varying(40) NOT NULL DEFAULT ''::character varying,
  id_ciudad character varying(60) NOT NULL DEFAULT ''::character varying,
  direccion character varying(80) NOT NULL DEFAULT ''::character varying,
  telefono character varying(25) NOT NULL DEFAULT ''::character varying,
  acciones text NOT NULL DEFAULT ''::text,
  contratista character varying(40) NOT NULL DEFAULT ''::character varying,
  costo numeric(15,2) NOT NULL DEFAULT 0.00,
  utili numeric(15,2) NOT NULL DEFAULT 0.00,
  total_prev1 numeric(15,2) NOT NULL DEFAULT 0.00,
  base_iva_ct numeric(15,2) NOT NULL DEFAULT 0.00,
  iva numeric(15,2) NOT NULL DEFAULT 0.00,
  val_contratista numeric(15,2) NOT NULL DEFAULT 0.00,
  comision_cyma numeric(15,2) NOT NULL DEFAULT 0.00,
  iva_comision_cyma numeric(15,2) NOT NULL DEFAULT 0.00,
  costos_dir numeric(15,2) NOT NULL DEFAULT 0.00,
  utili_o numeric(15,2) NOT NULL DEFAULT 0.00,
  oferta numeric(15,2) NOT NULL DEFAULT 0.00,
  base_iva_of numeric(15,2) NOT NULL DEFAULT 0.00,
  iva_o numeric(15,2) NOT NULL DEFAULT 0.00,
  valor_venta numeric(15,2) NOT NULL DEFAULT 0.00,
  comision_eco_eca numeric(15,2) NOT NULL DEFAULT 0.00,
  f_facturado_contratista_1 character varying(25) NOT NULL DEFAULT ''::character varying,
  m_facturado_cliente character varying(10) NOT NULL DEFAULT ''::character varying,
  f_facturado_cliente character varying(25) NOT NULL DEFAULT ''::character varying,
  id_accion character varying(10) NOT NULL DEFAULT ''::character varying,
  facturado_2 numeric(15,2) NOT NULL DEFAULT 0.00,
  facturado_3 numeric(15,2) NOT NULL DEFAULT 0.00,
  tipo_servicios character varying(10) NOT NULL DEFAULT ''::character varying,
  proveedor_nc character varying(20) NOT NULL DEFAULT ''::character varying,
  estado character varying(20) NOT NULL DEFAULT ''::character varying,
  f_facturado_contratista_2 character varying(25) NOT NULL DEFAULT ''::character varying,
  num_factura_contratista character varying(20) NOT NULL DEFAULT ''::character varying,
  f_aceptacion character varying(25) NOT NULL DEFAULT ''::character varying,
  estudio_economico character varying(60) NOT NULL DEFAULT ''::character varying,
  importe_oferta numeric(15,2) NOT NULL DEFAULT 0.00,
  iva_oferta numeric(15,2) NOT NULL DEFAULT 0.00,
  subtotal_oferta numeric(15,2) NOT NULL DEFAULT 0.00,
  por_dtf numeric(15,2) NOT NULL DEFAULT 0.00,
  por_interes_financiacion numeric(15,2) NOT NULL DEFAULT 0.00,
  por_riesgo_cartera numeric(15,2) NOT NULL DEFAULT 0.00,
  por_total_interes numeric(15,2) NOT NULL DEFAULT 0.00,
  intereses_financiados numeric(15,2) NOT NULL DEFAULT 0.00,
  importe_total numeric(15,2) NOT NULL DEFAULT 0.00,
  cuotas numeric(5,0) NOT NULL DEFAULT 0,
  por_cuota_inicial numeric(15,2) NOT NULL DEFAULT 0.00,
  valor_cuotas_restantes numeric(15,2) NOT NULL DEFAULT 0.00,
  forma_pago_2 character varying(35) NOT NULL DEFAULT ''::character varying,
  eca_costo numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_materiales numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_materiales numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_mo numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_mo numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_trans numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_trans numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_costos_dir numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_aiu numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_administr numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_administr numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_imprev numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_imprev numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_por_utili numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_utili numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_oferta numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_iva numeric(15,2) NOT NULL DEFAULT 0.00,
  eca_valor_venta numeric(15,2) NOT NULL DEFAULT 0.00,
  vlr_fac numeric(15,2) NOT NULL DEFAULT 0.00,
  vlr_fac_edificio text NOT NULL DEFAULT ''::text,
  sv text NOT NULL DEFAULT ''::text,
  fecha_factura character varying(10) NOT NULL DEFAULT ''::character varying,
  no_cuotas numeric(5,0) NOT NULL DEFAULT 0,
  consorcio_eca character varying(15) NOT NULL DEFAULT ''::character varying,
  observacion_1 text NOT NULL DEFAULT ''::text,
  observacion_2 text NOT NULL DEFAULT ''::text,
  observacion_3 text NOT NULL DEFAULT ''::text,
  observacion_cuota character varying(50) NOT NULL DEFAULT ''::character varying,
  ci numeric(5,2) NOT NULL DEFAULT 0.00,
  facturita character varying(10) DEFAULT ''::character varying,
  fechita_factura character varying(10) DEFAULT ''::character varying,
  llaveprimaria1 serial NOT NULL,
  dstrct character varying(4) NOT NULL DEFAULT ''::character varying
)
WITH (
  OIDS=FALSE
);
ALTER TABLE importacion_applus
  OWNER TO postgres;
GRANT ALL ON TABLE importacion_applus TO postgres;
GRANT SELECT ON TABLE importacion_applus TO msoto;

