-- Table: not_nit_geotech

-- DROP TABLE not_nit_geotech;

CREATE TABLE not_nit_geotech
(
  estado character(1),
  codcli character varying(10),
  nomcli character varying(160),
  notas text,
  agduenia character varying(3),
  reg_status character varying(1),
  creation_date timestamp without time zone,
  last_update timestamp without time zone,
  base character varying(3),
  texto_oc text,
  nit character varying(15),
  cedagente character varying(12),
  rentabilidad numeric(5,2),
  soportes_fac text,
  fiduciaria character varying(1),
  dstrct character varying(4),
  moneda character varying(3),
  forma_pago character varying(15),
  plazo numeric(3,0),
  zona character varying(6),
  branch_code character varying(15),
  bank_account_no character varying(30),
  cmc character varying(6),
  unidad text,
  codigo_impuesto character varying(6),
  agfacturacion character varying(3),
  direccion character varying(100),
  telefono character varying(100),
  nomcontacto character varying(100),
  telcontacto character varying(100),
  email_contacto character varying(100),
  dir_factura character varying(100),
  ma_prefactura character varying(3),
  tiempoprefac character varying,
  tiempo_leg character varying,
  tiempo_re_fact character varying,
  diapago character varying,
  for_facturacion character varying(100),
  direccion_contacto character varying,
  agencia_cobro character varying(3),
  sec_standard numeric,
  hc character varying(2),
  rif character varying(20),
  ciudad character varying(6),
  ciudad_factura character varying(3),
  pais character varying(3),
  pais_envio character varying(2),
  agimpresion character varying(3),
  demora_exp numeric(3,0),
  demora_imp numeric(3,0),
  tipo_id character varying(3),
  dapp character varying(1),
  nit_enviado_fiducia character varying,
  estado_gestion_cartera character varying(6),
  nit_fiducia_actualizado character varying(1),
  cargo_contacto character varying(50),
  cliente_eca character varying(1),
  id_ejecutivo character varying(10),
  esoficial character varying(1),
  tipo character varying(2),
  nombre_representante character varying(160),
  tel_representante character varying(100),
  celular_representante character varying(15),
  sector character varying(50),
  creation_user character varying(50),
  user_update character varying(50),
  cel_contacto character varying(50),
  edificio character varying(2),
  tipo_cliente character varying(8),
  digito_verificacion character varying(1),
  observaciones character varying(500)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE not_nit_geotech
  OWNER TO postgres;

