-- Type: etes.rs_anticipo_gasolina

-- DROP TYPE etes.rs_anticipo_gasolina;

CREATE TYPE etes.rs_anticipo_gasolina AS
   (reg_status character varying(1),
    id integer,
    dstrct character varying(4),
    agency_id character varying(10),
    pla_owner character varying(15),
    planilla character varying(10),
    supplier character varying(10),
    proveedor_anticipo character varying(15),
    concept_code character varying(12),
    vlr numeric(15,2),
    vlr_for numeric(15,2),
    currency character varying(3),
    fecha_anticipo timestamp without time zone,
    aprobado character varying(1),
    fecha_autorizacion timestamp without time zone,
    user_autorizacion character varying(10),
    transferido character varying(1),
    fecha_transferencia timestamp without time zone,
    banco_transferencia character varying(30),
    cuenta_transferencia character varying(20),
    tcta_transferencia character varying(4),
    user_transferencia character varying(10),
    banco character varying(30),
    sucursal character varying(30),
    nombre_cuenta character varying(50),
    cuenta character varying(20),
    tipo_cuenta character varying(2),
    nit_cuenta character varying(20),
    fecha_migracion timestamp without time zone,
    user_migracion character varying(10),
    factura_mims character varying(15),
    vlr_mims_tercero numeric(15,2),
    vlr_mims_propietario numeric(15,2),
    estado_pago_tercero character varying(30),
    estado_desc_propietario character varying(30),
    fecha_pago_tercero timestamp without time zone,
    fecha_desc_propietario timestamp without time zone,
    cheque_pago_tercero character varying(15),
    cheque_desc_propietario character varying(15),
    corrida_pago_tercero character varying(15),
    corrida_desc_propietario character varying(15),
    last_update timestamp without time zone,
    user_update character varying(10),
    creation_date timestamp without time zone,
    creation_user character varying(10),
    base character varying(3),
    porcentaje numeric(5,3),
    vlr_descuento moneda,
    vlr_neto moneda,
    vlr_combancaria moneda,
    vlr_consignacion moneda,
    reanticipo character varying(1),
    cedcon character varying(15),
    transferencia character varying(15),
    liquidacion character varying(12),
    secuencia integer,
    factura_tercero character varying(8),
    tipo_anticipo character varying(30),
    vlr_gasolina moneda,
    vlr_efectivo moneda,
    enviado_fintra character varying(2),
    fecha_envio_fintra timestamp without time zone,
    nombre_conductor character varying(60),
    nombre_propietario character varying(60),
    nombre_agencia character varying(30),
    con_ant_tercero character varying(4),
    observacion text,
    vlr_neto_real numeric(11,2),
    tipo_anticipo_busqueda text);
ALTER TYPE etes.rs_anticipo_gasolina
  OWNER TO postgres;
