-- Function: con.interfaz_fianza_negocios(integer)

-- DROP FUNCTION con.interfaz_fianza_negocios(integer);

CREATE OR REPLACE FUNCTION con.interfaz_fianza_negocios(_unidadnegocio integer)
  RETURNS text AS
$BODY$

DECLARE

 _RECORDFIANZA RECORD;
 _RECORDCONTABLE RECORD;
SECUENCIA_GEN INTEGER;
FECHADOC_ TEXT:='';
MCTYPE CON.TYPE_INSERT_MC;
SW TEXT:='N';
CONSEC INTEGER:=1;


BEGIN
	--BUSCAMOS LAS FIANZAS PENDIENTES POR PROCESAR
	FOR _RECORDFIANZA IN (

				SELECT
					FZ.PERIODO_CORTE,
					FZ.NIT_EMPRESA_FIANZA,
					ARRAY(SELECT F.DOCUMENTO_RELACIONADO FROM ADMINISTRATIVO.HISTORICO_DEDUCCIONES_FIANZA F WHERE F.DOCUMENTO_CXP=FZ.DOCUMENTO_CXP AND F.PERIODO_CORTE=FZ.PERIODO_CORTE /*AND F.REG_STATUS=''*/) AS DOCUMENTO_RELACIONADOS ,
					ARRAY(SELECT F.NEGOCIO FROM ADMINISTRATIVO.HISTORICO_DEDUCCIONES_FIANZA F WHERE F.DOCUMENTO_CXP=FZ.DOCUMENTO_CXP AND F.PERIODO_CORTE=FZ.PERIODO_CORTE /* AND F.REG_STATUS=''*/) AS NEGOCIOS ,
					SUM(FZ.SUBTOTAL_FIANZA) AS SUBTOTAL_FIANZA,
					SUM(FZ.VALOR_IVA) AS VALOR_IVA,
					SUM(FZ.VALOR_FIANZA) AS VALOR_FIANZA,
					FZ.DOCUMENTO_CXP,
					FZ.AGENCIA,
					NEG.ESTADO_NEG,
					CXP.FECHA_DOCUMENTO,
					CXP.FECHA_VENCIMIENTO,
					CXP.CREATION_DATE::DATE,
					'FI'||SUBSTRING(NEG.COD_NEG,1,2) AS PRE_NEGOCIO,
					COUNT(*) AS ITEMS
				FROM ADMINISTRATIVO.HISTORICO_DEDUCCIONES_FIANZA  FZ
				INNER JOIN NEGOCIOS NEG ON (NEG.COD_NEG=FZ.NEGOCIO)
				INNER JOIN FIN.CXP_DOC CXP ON (CXP.DOCUMENTO=FZ.DOCUMENTO_CXP AND CXP.TIPO_DOCUMENTO='FAP' AND CXP.PROVEEDOR=FZ.NIT_EMPRESA_FIANZA AND CXP.REG_STATUS='')
				INNER JOIN REL_UNIDADNEGOCIO_CONVENIOS RUC ON (NEG.ID_CONVENIO = RUC.ID_CONVENIO)
				INNER JOIN UNIDAD_NEGOCIO UNEG ON (UNEG.ID = RUC.ID_UNID_NEGOCIO)
				WHERE NEG.ESTADO_NEG IN ('T')
				AND uneg.id = _unidadnegocio --1 --22
				AND REPLACE(SUBSTRING(NEG.F_DESEM,1,7),'-','') =REPLACE(SUBSTRING(CURRENT_DATE,1,7),'-','')
				AND FZ.DOCUMENTO_CXP !=''
				AND (NEG.PROCESADO_MC='S' OR NEG.PROCESADO_LIB='S')
				AND FZ.PROCESADO_APOT='N' --CAMPO DE CONTROL OJO
				AND FZ.REG_STATUS=''
				--AND SUBSTR(FZ.DOCUMENTO_CXP,1,3) = 'FZD'
				GROUP BY
				FZ.PERIODO_CORTE,
				FZ.NIT_EMPRESA_FIANZA,
				FZ.DOCUMENTO_CXP,
				FZ.AGENCIA,
				NEG.ESTADO_NEG,
				CXP.FECHA_DOCUMENTO,
				CXP.FECHA_VENCIMIENTO,
				CXP.CREATION_DATE::DATE,
				SUBSTRING(NEG.COD_NEG,1,2)

	) LOOP

		RAISE NOTICE 'recordFianza : %',_RECORDFIANZA;

		SELECT INTO SECUENCIA_GEN NEXTVAL('CON.INTERFAZ_SECUENCIA_CXP_APOTEOSYS');

		--CREAMOS LA TRANSACCION CONTABLE POR NEGOCIO PARA PODER RELACIONAR TODO AL NEGOCIO.

		FOR _RECORDCONTABLE IN (SELECT
						T.PERIODO,
						T.PROVEEDOR,
						T.TIPO_DOCUMENTO,
						T.DOCUMENTO,
						T.DESCRIPCION,
						T.REFERENCIA,
						T.HANDLE_CODE,
						T.CTA_PASIVO,
						T.CTA_DEBITO_APO,
						T.FECHA_DOCUMENTO,
						T.FECHA_VENCIMIENTO,
						T.CREATION_DATE::DATE,
						T.VALOR_DEBITO,
						T.VALOR_CREDITO,
						T.TERCER_CODIGO____TIT____B,
						T.TERCER_DIGICHEQ__B,
						T.TERCER_NOMBCORT__B,
						T.TERCER_APELLIDOS_B,
						T.TERCER_NOMBEXTE__B,
						T.TERCER_CODIGO____TT_____B,
						T.TERCER_DIRECCION_B,
						T.TERCER_CODIGO____CIUDAD_B,
						T.TERCER_TELEFONO1_B
					FROM (
							SELECT
								CXP.PERIODO,
								CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE CXP.PROVEEDOR END AS PROVEEDOR,
								CXP.TIPO_DOCUMENTO,
								CXP.DOCUMENTO,
								CXP.DESCRIPCION||' => Negocio: '||CXP.REFERENCIA_1 AS DESCRIPCION,
								CXP.REFERENCIA_1 AS REFERENCIA,
								CXP.HANDLE_CODE,
								CXPDET.CODIGO_CUENTA AS CTA_PASIVO,
								CMC.CUENTA AS CTA_DEBITO_APO,
								_RECORDFIANZA.FECHA_DOCUMENTO::DATE AS FECHA_DOCUMENTO ,
								_RECORDFIANZA.FECHA_VENCIMIENTO::DATE AS FECHA_VENCIMIENTO,
								_RECORDFIANZA.CREATION_DATE::DATE AS CREATION_DATE,
								CXP.VLR_NETO AS VALOR_DEBITO,
								0.00::NUMERIC AS VALOR_CREDITO,
								(CASE
								 WHEN D.TIPO_IDEN='CED' THEN 'CC'
								 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
								 WHEN D.TIPO_IDEN='' THEN 'CC'
								 WHEN D.TIPO_IDEN='NIT' THEN 'NIT'
								 ELSE
								 'CC' END) AS TERCER_CODIGO____TIT____B,
								 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
								 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
								 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
								 D.NOMBRE AS TERCER_NOMBEXTE__B,
								 (CASE
								 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
								 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
								 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
								 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
								 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
								 D.DIRECCION AS TERCER_DIRECCION_B,
								 (CASE
								 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
								 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
								 D.TELEFONO AS TERCER_TELEFONO1_B
							FROM FIN.CXP_DOC  CXP
							INNER JOIN FIN.CXP_ITEMS_DOC CXPDET ON (CXP.DOCUMENTO=CXPDET.DOCUMENTO AND CXP.TIPO_DOCUMENTO=CXPDET.TIPO_DOCUMENTO AND CXP.PROVEEDOR=CXPDET.PROVEEDOR)
							INNER JOIN CON.CMC_DOC CMC ON (CMC.CMC=CXP.HANDLE_CODE AND CMC.TIPODOC=CXP.TIPO_DOCUMENTO)
							LEFT JOIN PROVEEDOR C ON(C.NIT='9002207536')
							LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
							LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
							LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA='9002207536')
							WHERE
							--CXP.REG_STATUS='' AND
							 CXP.TIPO_DOCUMENTO ='FAP'
							AND CXP.REFERENCIA_1 = ANY(_RECORDFIANZA.NEGOCIOS)
							AND CXP.DOCUMENTO = ANY(_RECORDFIANZA.DOCUMENTO_RELACIONADOS)

							UNION ALL

							SELECT
								CXP.PERIODO,
								CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE CXP.PROVEEDOR END AS PROVEEDOR,
								CXP.TIPO_DOCUMENTO,
								CXP.DOCUMENTO,
								CXP.DESCRIPCION ||'=> Negocio: '||CXPDET.REFERENCIA_2 AS DESCRIPCION,
								CXPDET.REFERENCIA_2 AS REFERENCIA,
								CXP.HANDLE_CODE,
								CXPDET.CODIGO_CUENTA AS CTA_PASIVO,
								CMC.CUENTA AS CTA_DEBITO_APO,
								CXP.FECHA_DOCUMENTO::DATE,
								CXP.FECHA_VENCIMIENTO::DATE,
								CXP.CREATION_DATE::DATE,
								0.00::NUMERIC AS VALOR_DEBITO,
								CXPDET.VLR AS VALOR_CREDITO,
								(CASE
								 WHEN D.TIPO_IDEN='CED' THEN 'CC'
								 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
								 WHEN D.TIPO_IDEN='' THEN 'CC'
								 WHEN D.TIPO_IDEN='NIT' THEN 'NIT'
								 ELSE
								 'CC' END) AS TERCER_CODIGO____TIT____B,
								 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
								 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
								 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
								 D.NOMBRE AS TERCER_NOMBEXTE__B,
								 (CASE
								 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
								 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
								 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
								 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
								 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
								 D.DIRECCION AS TERCER_DIRECCION_B,
								 (CASE
								 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
								 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
								 D.TELEFONO AS TERCER_TELEFONO1_B
							FROM FIN.CXP_DOC  CXP
							INNER JOIN FIN.CXP_ITEMS_DOC CXPDET ON (CXP.DOCUMENTO=CXPDET.DOCUMENTO AND CXP.TIPO_DOCUMENTO=CXPDET.TIPO_DOCUMENTO AND CXP.PROVEEDOR=CXPDET.PROVEEDOR)
							INNER JOIN CON.CMC_DOC CMC ON (CMC.CMC=CXP.HANDLE_CODE AND CMC.TIPODOC=CXP.TIPO_DOCUMENTO)
							LEFT JOIN PROVEEDOR C ON(C.NIT='9002207536')
							LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
							LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
							LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA='9002207536')
							WHERE
							CXP.REG_STATUS=''
							AND CXP.TIPO_DOCUMENTO ='FAP'
							AND CXP.DOCUMENTO = _RECORDFIANZA.DOCUMENTO_CXP
						)T
					ORDER BY REFERENCIA,VALOR_CREDITO,VALOR_DEBITO
					)

		LOOP
			RAISE NOTICE '_RECORDCONTABLE: %',_RECORDCONTABLE;

			FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(_RECORDFIANZA.FECHA_DOCUMENTO::DATE,1,7),'-','')=_RECORDFIANZA.PERIODO_CORTE THEN _RECORDFIANZA.FECHA_DOCUMENTO::DATE ELSE CON.SP_FECHA_CORTE_MES(SUBSTRING(_RECORDFIANZA.PERIODO_CORTE,1,4),SUBSTRING(_RECORDFIANZA.PERIODO_CORTE,5,2)::INT)::DATE END ;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 6)='S')then
				MCTYPE.MC_____FECHEMIS__B = FECHADOC_::DATE;
				MCTYPE.MC_____FECHVENC__B = FECHADOC_::DATE;
			else
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

			end if;

			------------------------------------------------------
			MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
 			MCTYPE.MC_____CODIGO____TD_____B := 'CXPN' ;
 			MCTYPE.MC_____CODIGO____CD_____B := _RECORDFIANZA.PRE_NEGOCIO  ;
			MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
			MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE  ;
			MCTYPE.MC_____NUMERO____B := SECUENCIA_GEN  ;
			MCTYPE.MC_____SECUINTE__B := CONSEC  ;
 			MCTYPE.MC_____REFERENCI_B := _RECORDCONTABLE.REFERENCIA;
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(_RECORDFIANZA.PERIODO_CORTE,1,4)::INT;
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(_RECORDFIANZA.PERIODO_CORTE,5,2)::INT;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 1)  ;
			MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 2)  ;
			MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(_RECORDCONTABLE.PROVEEDOR)>10 THEN SUBSTR(_RECORDCONTABLE.PROVEEDOR,1,10) ELSE _RECORDCONTABLE.PROVEEDOR END;
			MCTYPE.MC_____DEBMONORI_B := 0  ;
			MCTYPE.MC_____CREMONORI_B := 0 ;
			MCTYPE.MC_____DEBMONLOC_B := _RECORDCONTABLE.VALOR_DEBITO::NUMERIC  ;
			MCTYPE.MC_____CREMONLOC_B := _RECORDCONTABLE.VALOR_CREDITO::NUMERIC  ;
			MCTYPE.MC_____INDTIPMOV_B := 4  ;
			MCTYPE.MC_____INDMOVREV_B := 'N'  ;
			MCTYPE.MC_____OBSERVACI_B := _RECORDCONTABLE.DESCRIPCION  ;
			MCTYPE.MC_____FECHORCRE_B := FECHADOC_::TIMESTAMP  ;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
			MCTYPE.MC_____FEHOULMO__B := FECHADOC_::TIMESTAMP  ;
			MCTYPE.MC_____AUTULTMOD_B := ''  ;
			MCTYPE.MC_____VALIMPCON_B := 0  ;
			MCTYPE.MC_____NUMERO_OPER_B := _RECORDFIANZA.DOCUMENTO_CXP;
			MCTYPE.TERCER_CODIGO____TIT____B := _RECORDCONTABLE.TERCER_CODIGO____TIT____B  ;
			MCTYPE.TERCER_NOMBCORT__B := _RECORDCONTABLE.TERCER_NOMBCORT__B  ;
			MCTYPE.TERCER_NOMBEXTE__B := CASE WHEN CHAR_LENGTH(_RECORDCONTABLE.TERCER_NOMBEXTE__B)>64 then SUBSTR(_RECORDCONTABLE.TERCER_NOMBEXTE__B,1,64) ELSE _RECORDCONTABLE.TERCER_NOMBEXTE__B END;
			MCTYPE.TERCER_APELLIDOS_B := _RECORDCONTABLE.TERCER_APELLIDOS_B  ;
			MCTYPE.TERCER_CODIGO____TT_____B := _RECORDCONTABLE.TERCER_CODIGO____TT_____B  ;
			MCTYPE.TERCER_DIRECCION_B := CASE WHEN CHAR_LENGTH(_RECORDCONTABLE.TERCER_DIRECCION_B)>64 then SUBSTR(_RECORDCONTABLE.TERCER_DIRECCION_B,1,64) ELSE _RECORDCONTABLE.TERCER_DIRECCION_B END;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := _RECORDCONTABLE.TERCER_CODIGO____CIUDAD_B  ;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(_RECORDCONTABLE.TERCER_TELEFONO1_B)>15 THEN SUBSTR(_RECORDCONTABLE.TERCER_TELEFONO1_B,1,15) ELSE _RECORDCONTABLE.TERCER_TELEFONO1_B END;
			MCTYPE.TERCER_TIPOGIRO__B := 1 ;
			MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
			MCTYPE.TERCER_SUCURSAL__B := ''  ;
			MCTYPE.TERCER_NUMECUEN__B := ''  ;
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 3);
			--MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
			MCTYPE.MC_____NUMEVENC__B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 5)::INT;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 4)='S')then
				MCTYPE.MC_____NUMDOCSOP_B := _RECORDCONTABLE.DOCUMENTO;
			else
				MCTYPE.MC_____NUMDOCSOP_B := '';
			end if;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FIANZA', _RECORDCONTABLE.TIPO_DOCUMENTO, _RECORDCONTABLE.CTA_DEBITO_APO,_RECORDFIANZA.AGENCIA, 5)::int=1)then
				MCTYPE.MC_____NUMEVENC__B := 1;
			else
				MCTYPE.MC_____NUMEVENC__B := null;
			end if;

			-- Insertamos en la tabla de Apoteosys
			--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
			SW:=CON.SP_INSERT_TABLE_MC_FIANZA____(MCTYPE);
			CONSEC:=CONSEC+1;
			------------------------------------------------------

		END LOOP; --FIN LOOP DE LA TRANSACCION INTERNA

		CONSEC:=1;


		--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
		 IF CON.SP_VALIDACIONES(MCTYPE, 'FIANZA') ='N' THEN
			SW='N';

			--BORRAMOS EL COMPROBANTE DE EXT
			DELETE FROM con.mc_fianza____
			WHERE MC_____NUMERO____B = SECUENCIA_GEN AND MC_____CODIGO____CONTAB_B = 'FINT'
			 AND MC_____CODIGO____TD_____B = 'CXPN' AND  MC_____CODIGO____CD_____B = _RECORDFIANZA.PRE_NEGOCIO ;

			CONTINUE;
		END IF;

		-- ACTUALIZAMOS EL CAMPO DE APOTEOSYS DE LA CABECERA DEL CRéDITO PARA INDICAR QUE YA SE ENVíO
		IF(SW='S')THEN

			UPDATE
				ADMINISTRATIVO.HISTORICO_DEDUCCIONES_FIANZA
			SET
				PROCESADO_APOT='S'
			WHERE
				PERIODO_CORTE = _RECORDFIANZA.PERIODO_CORTE and
				NIT_EMPRESA_FIANZA = _RECORDFIANZA.NIT_EMPRESA_FIANZA and
				DOCUMENTO_CXP = _RECORDFIANZA.DOCUMENTO_CXP and
				AGENCIA = _RECORDFIANZA.AGENCIA;

			SW:='N';
		END IF;




	END LOOP; --FIN LOOP PRINCIPAL


RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fianza_negocios(integer)
  OWNER TO postgres;
