-- Function: con.interfaz_fintra_logistica_apoteosys_cadena(character varying, character varying)

-- DROP FUNCTION con.interfaz_fintra_logistica_apoteosys_cadena(character varying, character varying);

CREATE OR REPLACE FUNCTION con.interfaz_fintra_logistica_apoteosys_cadena(numero_operacion_ character varying, periodo_ character varying)
  RETURNS character varying[] AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION:
  *DOCUMENTACION:=
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-05-24
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_OS RECORD;
 CADENA TEXT:='';
 COMA 	TEXT:='';
 DATO 	TEXT:='';
 _ARR VARCHAR[] :='{}';
 FECHA_EMISION_CXP_ TEXT := '';
 FECHA_VENCIMIENTO_CXP_ TEXT := '';
 FECHA_EMISION_CXC_ TEXT := '';
 FECHA_VENCIMIENTO_CXC_ TEXT := '';

 BEGIN

	FOR REC_OS IN
		SELECT
				B.FACTURA_CXC,
				C.FECHA_DOCUMENTO AS FECHA_EMISION_CXP,
				C.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXP,
				D.FECHA_FACTURA AS FECHA_EMISION_CXC,
				D.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXC

			FROM
				FIN.ORDEN_SERVICIO A
			INNER JOIN
				FIN.ORDEN_SERVICIO_DETALLE B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_OPERACION=A.TIPO_OPERACION AND B.NUMERO_OPERACION=A.NUMERO_OPERACION)
			INNER JOIN
				FIN.CXP_DOC C ON(C.DSTRCT='FINV' AND C.TIPO_DOCUMENTO='FAP' AND C.DOCUMENTO=A.FACTURA_CXP)
			INNER JOIN
				CON.FACTURA D ON(D.DSTRCT='FINV' AND D.TIPO_DOCUMENTO='FAC' AND D.DOCUMENTO=B.FACTURA_CXC)
			WHERE
				A.REG_STATUS!='A' AND
				A.DSTRCT='FINV' AND
				A.TIPO_OPERACION ='EXT' AND
				A.GRUPO_TRANSACCION_OS!=0 AND
				A.PERIODO_OS!='' AND
				A.FECHA_CONTABILIZACION_OS::DATE >= '2014-01-01' AND
				C.FECHA_CONTABILIZACION!='0099-01-01 00:00:00' AND
				D.FECHA_CONTABILIZACION!='0099-01-01 00:00:00' AND
				A.PERIODO_OS = PERIODO_ AND --SOLO PARA PRUEBA
				A.NUMERO_OPERACION = NUMERO_OPERACION_
				LIMIT 1

	LOOP
		/*CADENA := CADENA||COMA||REC_OS.FACTURA_CXC;
		COMA := ',';*/
		FECHA_EMISION_CXP_ := REC_OS.FECHA_EMISION_CXP;
		FECHA_VENCIMIENTO_CXP_ := REC_OS.FECHA_VENCIMIENTO_CXP;
		FECHA_EMISION_CXC_ := REC_OS.FECHA_EMISION_CXC;
		FECHA_VENCIMIENTO_CXC_ := REC_OS.FECHA_VENCIMIENTO_CXC;
	END LOOP;

	--_ARR[1]:=CADENA;
	_ARR[2]:=FECHA_EMISION_CXP_;
	_ARR[3]:=FECHA_VENCIMIENTO_CXP_;
	_ARR[4]:=FECHA_EMISION_CXC_;
	_ARR[5]:=FECHA_VENCIMIENTO_CXC_;


	RETURN _ARR;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_logistica_apoteosys_cadena(character varying, character varying)
  OWNER TO postgres;
