-- Function: con.interfaz_fintra_logistica_apoteosys_gasolina()

-- DROP FUNCTION con.interfaz_fintra_logistica_apoteosys_gasolina();

CREATE OR REPLACE FUNCTION con.interfaz_fintra_logistica_apoteosys_gasolina()
  RETURNS text AS
$BODY$

DECLARE


 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LAS ORDENES DE SERVICIO Y
  *OBTIENE LOS ANTICIPOS POR GASOLINA Y CONSTRUYE EL ASIENTO
  *CONTABLE QUE MAS ADELANTE SE TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:= EL ARRAY _ARRCUENTASAET HACE REFERENCIA A LAS CUENTAS PARA
  *REALIZAR LA VERIFICACION DE LAS TRANSACCIONES ASI:
  *AET:=I010030024154, EGR:=23050118, FAC:=13802704.
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-05-23
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_OS RECORD;
 REC_AGA RECORD;
 REC_EGR RECORD;
 SECUENCIA_GR INTEGER;
 SECUENCIA_EG INTEGER;
 CONSEC INTEGER:=1;
 PLANILLA_ TEXT:='';
 RESUL_ TEXT:='';
 SW TEXT:='N';
 FECHADOC_ TEXT:='';
 _ARRCUENTASAET VARCHAR[] :='{I010030024154,23050118,13802704}';--IDEAL UN TABLA OJO!!
 MCTYPE CON.TYPE_INSERT_MC;

BEGIN

--SE CONSULTAN LOS REGISTROS QUE SE VAN A TRANSPORTAR PARA GASOLINA

	FOR REC_OS IN

		SELECT A.NUMERO_OPERACION,
			A.CREATION_DATE,
			A.FACTURA_CXP,
			B.FACTURA_CXC,
			A.EGRESO,
			A.TIPO_OPERACION,
			A.CMC,
			A.PROVEEDOR,
			A.VLR_EXTRACTO,
			A.PORCENTAJE,
			A.VLR_DESCUENTO,
			A.VLR_COMBANCARIA,
			A.VLR_CONSIGNACION_CALCULADA,
			A.VLR_AJUSTE,
			C.FECHA_DOCUMENTO AS FECHA_EMISION_CXP,
			C.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXP,
			D.FECHA_FACTURA AS FECHA_EMISION_CXC,
			D.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXC,
			A.PERIODO_OS
		FROM
			FIN.ORDEN_SERVICIO A
		INNER JOIN
			FIN.ORDEN_SERVICIO_DETALLE B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_OPERACION=A.TIPO_OPERACION AND B.NUMERO_OPERACION=A.NUMERO_OPERACION)
		LEFT JOIN
			FIN.CXP_DOC C ON(C.TIPO_DOCUMENTO='FAP' AND C.DOCUMENTO=A.FACTURA_CXP AND C.DSTRCT='FINV' AND C.REG_STATUS='')
		LEFT JOIN
			CON.FACTURA D ON(D.TIPO_DOCUMENTO='FAC' AND D.DOCUMENTO=B.FACTURA_CXC AND D.DSTRCT='FINV' AND D.REG_STATUS='' AND C.PERIODO=A.PERIODO_OS)
		LEFT JOIN
			FIN.ANTICIPOS_PAGOS_TERCEROS E ON(E.REG_STATUS='' AND E.DSTRCT='FINV' AND E.TIPO_OPERACION=A.TIPO_OPERACION AND E.NUMERO_OPERACION=A.NUMERO_OPERACION)
		WHERE
			A.REG_STATUS!='A' AND
			A.DSTRCT='FINV' AND
			A.TIPO_OPERACION ='AGA' AND
			A.GRUPO_TRANSACCION_OS!=0 AND
			A.PERIODO_OS!='' AND
			A.PERIODO_OS =REPLACE(SUBSTRING(CURRENT_DATE,1,7),'-','')
			AND A.VLR_EXTRACTO != 0.00
			AND A.PROCESADO = 'N'

	LOOP
			--------------------------------------------------------------------------------------------------------------------------------------------
			--SE CONSULTA LA TRANSACCION
			--TIPODOC FAC Y CUENTA 13802704, GASOLINA
			--TIPODOC AGA Y CUENTA I010030024154, GASOLINA
			--TIPODOC EGR Y CUENTA 23050118, GASOLINA

			SECUENCIA_GR:=0;
			SECUENCIA_EG:=0;
			PLANILLA_:='';
			CONSEC :=1;

			RAISE notice 'Numero Operacion: %',REC_OS.numero_operacion;

			--SECUENCIA DE LA TRANSACCION
			SELECT INTO SECUENCIA_GR NEXTVAL('CON.INTERFAZ_SECUENCIA_OPER_APOTEOSYS');

			--CONSULTAMOS LA PLANILLA DE LA ORDEN DE SERVICIO PARA UTILIZARLO COMO REFERENCIA
			SELECT INTO PLANILLA_ PLANILLA FROM FIN.ANTICIPOS_PAGOS_TERCEROS WHERE TIPO_OPERACION='AGA' AND NUMERO_OPERACION=REC_OS.NUMERO_OPERACION;

			--SE CONSTRUYE EL ASIENTO POR EL NUMERO DE LA OPERACION
			FOR REC_AGA IN

				SELECT A.FECHADOC,
				 B.TIPODOC,
				 B.GRUPO_TRANSACCION,
				 B.PERIODO,
				 B.CUENTA,
				 CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE A.TERCERO END AS TERCERO,
				 --A.TERCERO,
				 TRUNC(B.VALOR_DEBITO,0) AS VALOR_DEBITO,
				 TRUNC(B.VALOR_CREDITO,0) AS VALOR_CREDITO,
				 B.DETALLE,
				 B.CREATION_DATE,
				 B.CREATION_USER,
				 B.LAST_UPDATE,
				 B.USER_UPDATE,
				 (CASE
				 WHEN D.TIPO_IDEN='CED' THEN 'CC'
				 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
				 WHEN D.TIPO_IDEN='' THEN 'CC'
				 WHEN D.TIPO_IDEN='NIT' THEN 'NIT'
				 ELSE
				 'CC' END) AS TERCER_CODIGO____TIT____B,
				 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
				 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
				 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
				 D.NOMBRE AS TERCER_NOMBEXTE__B,
				 (CASE
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
				 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
				 D.DIRECCION AS TERCER_DIRECCION_B,
				 (CASE
				 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
				 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
				 D.TELEFONO AS TERCER_TELEFONO1_B
				FROM
				 CON.COMPROBANTE A
				INNER JOIN CON.COMPRODET B ON(B.DSTRCT=A.DSTRCT AND B.TIPODOC=A.TIPODOC AND B.NUMDOC=A.NUMDOC AND B.GRUPO_TRANSACCION=A.GRUPO_TRANSACCION)
				LEFT JOIN PROVEEDOR C ON(C.NIT=A.TERCERO)
				LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
				LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
				LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=A.TERCERO)
				WHERE
				 A.DSTRCT='FINV' AND
				 ((A.TIPODOC, A.NUMDOC, CUENTA) =('AGA',REC_OS.NUMERO_OPERACION, _ARRCUENTASAET[1]) OR
				 (A.TIPODOC, A.NUMDOC, CUENTA) =('EGR',REC_OS.EGRESO,  _ARRCUENTASAET[2]) OR
				 (A.TIPODOC, A.NUMDOC, CUENTA) =('FAC',REC_OS.FACTURA_CXC,  _ARRCUENTASAET[3]))

			LOOP
				--MCTYPE:=REC_AGA;

				FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_OS.CREATION_DATE::DATE,1,7),'-','')=REC_OS.PERIODO_OS THEN REC_OS.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_OS.PERIODO_OS,1,4),SUBSTRING(REC_OS.PERIODO_OS,5,2)::INT)::DATE END ;

				FECHADOC_ := CASE WHEN FECHADOC_::DATE<'2016-12-01'::DATE THEN '2016-12-31'::DATE ELSE FECHADOC_::DATE END;

				if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 6)='S')then
					MCTYPE.MC_____FECHEMIS__B = FECHADOC_::DATE;
					--CASE WHEN REPLACE(SUBSTRING(REC_OS.FECHA_EMISION_CXC,1,7),'-','')=REC_AGA.PERIODO THEN REC_OS.FECHA_EMISION_CXC::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_AGA.PERIODO,1,4),SUBSTRING(REC_AGA.PERIODO,5,2)::INT)::DATE END ;
					MCTYPE.MC_____FECHVENC__B = CASE WHEN REC_OS.FECHA_VENCIMIENTO_CXC<'2016-12-01' THEN FECHADOC_::DATE ELSE REC_OS.FECHA_VENCIMIENTO_CXC::DATE END;
				else
					MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
					MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

				end if;

				if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 6)='S')then
					MCTYPE.MC_____FECHEMIS__B = FECHADOC_::DATE;
					--CASE WHEN REPLACE(SUBSTRING(REC_OS.FECHA_EMISION_CXC,1,7),'-','')=REC_AGA.PERIODO THEN REC_OS.FECHA_EMISION_CXC::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_AGA.PERIODO,1,4),SUBSTRING(REC_AGA.PERIODO,5,2)::INT)::DATE END ;
					MCTYPE.MC_____FECHVENC__B=CASE WHEN REC_OS.FECHA_VENCIMIENTO_CXC<'2016-12-01' THEN FECHADOC_::DATE ELSE REC_OS.FECHA_VENCIMIENTO_CXC::DATE END;
				else
					MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
					MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
				end if;

				MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
				MCTYPE.MC_____CODIGO____TD_____B := 'OPER' ;
				MCTYPE.MC_____CODIGO____CD_____B := 'AGA'  ;
				MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
				MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE  ;
				MCTYPE.MC_____NUMERO____B := SECUENCIA_GR  ;
				MCTYPE.MC_____SECUINTE__B := CONSEC  ;
				MCTYPE.MC_____REFERENCI_B := PLANILLA_  ;
				MCTYPE.MC_____CODIGO____PF_____B := CASE WHEN REC_AGA.PERIODO::INT<201612 THEN 2016 ELSE SUBSTRING(REC_OS.PERIODO_OS,1,4)::INT END  ;
				MCTYPE.MC_____NUMERO____PERIOD_B := CASE WHEN REC_AGA.PERIODO::INT<201612 THEN 12 ELSE SUBSTRING(REC_OS.PERIODO_OS,5,2)::INT END  ;
				MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
				MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 1)  ;
				MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 2)  ;
				MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(REC_AGA.TERCERO)>10 THEN SUBSTR(REC_AGA.TERCERO,1,10) ELSE REC_AGA.TERCERO END;
				MCTYPE.MC_____DEBMONORI_B := 0  ;
				MCTYPE.MC_____CREMONORI_B := 0 ;
				MCTYPE.MC_____DEBMONLOC_B := REC_AGA.VALOR_DEBITO::NUMERIC  ;
				MCTYPE.MC_____CREMONLOC_B := REC_AGA.VALOR_CREDITO::NUMERIC  ;
				MCTYPE.MC_____INDTIPMOV_B := 4  ;
				MCTYPE.MC_____INDMOVREV_B := 'N'  ;
				MCTYPE.MC_____OBSERVACI_B := REC_AGA.DETALLE  ;
				MCTYPE.MC_____FECHORCRE_B := REC_AGA.CREATION_DATE::TIMESTAMP  ;
				MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
				MCTYPE.MC_____FEHOULMO__B := REC_AGA.LAST_UPDATE::TIMESTAMP  ;
				MCTYPE.MC_____AUTULTMOD_B := ''  ;
				MCTYPE.MC_____VALIMPCON_B := 0  ;
				MCTYPE.MC_____NUMERO_OPER_B := REC_OS.NUMERO_OPERACION;
				MCTYPE.TERCER_CODIGO____TIT____B := REC_AGA.TERCER_CODIGO____TIT____B  ;
				MCTYPE.TERCER_NOMBCORT__B := REC_AGA.TERCER_NOMBCORT__B  ;
				MCTYPE.TERCER_NOMBEXTE__B := REC_AGA.TERCER_NOMBEXTE__B  ;
				MCTYPE.TERCER_APELLIDOS_B := REC_AGA.TERCER_APELLIDOS_B  ;
				MCTYPE.TERCER_CODIGO____TT_____B := REC_AGA.TERCER_CODIGO____TT_____B  ;
				MCTYPE.TERCER_DIRECCION_B := REC_AGA.TERCER_DIRECCION_B  ;
				MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_AGA.TERCER_CODIGO____CIUDAD_B  ;
				MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_AGA.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_AGA.TERCER_TELEFONO1_B,1,15) ELSE REC_AGA.TERCER_TELEFONO1_B END;
				MCTYPE.TERCER_TIPOGIRO__B := 1 ;
				MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
				MCTYPE.TERCER_SUCURSAL__B := ''  ;
				MCTYPE.TERCER_NUMECUEN__B := ''  ;
				MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 3);
				MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
				MCTYPE.MC_____NUMEVENC__B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 5)::INT;

				if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 4)='S')then
					MCTYPE.MC_____NUMDOCSOP_B := 'AGA'||REC_OS.NUMERO_OPERACION;
				else
					MCTYPE.MC_____NUMDOCSOP_B := '';
				end if;

				if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('GASOLINA', REC_AGA.TIPODOC, REC_AGA.CUENTA,'', 5)::int=1)then
					MCTYPE.MC_____NUMEVENC__B := 1;
				else
					MCTYPE.MC_____NUMEVENC__B := null;
				end if;

				--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
				SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
				CONSEC:=CONSEC+1;

			END LOOP;

			--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
			IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
				SW='N';
				CONTINUE;
			END IF;


			--select INTO RESUL_ con.interfaz_fintra_logistica_apoteosys_gasolina_eds(PLANILLA_);

			--ACTUALIZAMOS EL REGISTRO EN OS PARA SABER QUE SE PROCESO
			IF(SW='S')THEN
				UPDATE
					FIN.ORDEN_SERVICIO
				SET
					PROCESADO='S'
				WHERE
					DSTRCT='FINV' AND
					TIPO_OPERACION='AGA' AND
					NUMERO_OPERACION=REC_OS.NUMERO_OPERACION;

				SW:='N';
			END IF;

	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_logistica_apoteosys_gasolina()
  OWNER TO postgres;
