-- Function: con.interfaz_fintra_logistica_apoteosys_pp_ica_r()

-- DROP FUNCTION con.interfaz_fintra_logistica_apoteosys_pp_ica_r();

CREATE OR REPLACE FUNCTION con.interfaz_fintra_logistica_apoteosys_pp_ica_r()
  RETURNS text AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LAS NOTAS DE AJUSTE QUE SE LES GENERA A LAS R Y
  *CONTRUYE EL ASIENTO CONTABLE QUE MAS ADELANTE SE TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:= EL ARRAY _ARRCUENTASAET HACE REFERENCIA A LAS CUENTAS PARA
  *REALIZAR LA VERIFICACION DE LAS TRANSACCIONES ASI:
  *28050508,13802602
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-12-04
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_OS RECORD;
 SECUENCIA_EXT INTEGER;
 CONSEC INTEGER:=1;
 FECHADOC_ TEXT:='';
 SW TEXT:='N';
 MCTYPE CON.TYPE_INSERT_MC;

BEGIN

--SE CONSULTAN LOS REGISTROS QUE SE VAN A TRANSPORTAR PARA TRANSFERENCIAS
--select * from con.ingreso where num_ingreso='IA522779'
	FOR REC_OS IN

		SELECT
			A.PROCESADO,
			A.NUM_INGRESO,
			A.CREATION_DATE,
			CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE A.NITCLI END AS NITCLI,
			--A.NITCLI,
			A.VALOR_INGRESO,
			A.PERIODO,
			A.TIPO_DOCUMENTO,
			A.DOCUMENTO,
			A.DESCRIPCION,
			B.CUENTA AS CUENTA_PLA,
			A.CUENTA,
			A.DESCRIPCION,
			(CASE
			 WHEN D.TIPO_IDEN='CED' THEN 'CC'
			 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
			 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
			 'CC' END) AS TERCER_CODIGO____TIT____B,
			 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
			 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
			 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
			 D.NOMBRE AS TERCER_NOMBEXTE__B,
			 (CASE
			 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
			 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
			 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
			 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
			 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
			 D.DIRECCION AS TERCER_DIRECCION_B,
			 (CASE
			 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
			 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
			 D.TELEFONO AS TERCER_TELEFONO1_B
		FROM
			CON.INGRESO_DETALLE A
		INNER JOIN
			CON.INGRESO B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.NUM_INGRESO=A.NUM_INGRESO)
		LEFT JOIN
			PROVEEDOR C ON(c.dstrct=B.DSTRCT and C.NIT=A.NITCLI)
		LEFT JOIN
			NIT D ON(D.CEDULA=C.NIT)
		LEFT JOIN
			CIUDAD E ON(E.CODCIU=D.CODCIU)
		LEFT JOIN
			CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=A.NITCLI)
		WHERE
			A.REG_STATUS='' AND
			B.REG_STATUS='' AND
			A.DSTRCT='FINV'
			AND A.TIPO_DOCUMENTO='ICA'
			and A.NUM_INGRESO in('IA532433')
			--AND (A.PROCESADO='N' OR A.PROCESADO IS NULL)

--SELECT con.interfaz_fintra_logistica_apoteosys_pp_ica_R();
/***
SELECT MC_____NUMERO____PERIOD_B, MC_____CREMONLOC_B, mc_____codigo____cu_____b from con.mc____ where MC_____CODIGO____CONTAB_B = 'FINT'  and MC_____CODIGO____TD_____B = 'ICRN' and
MC_____CODIGO____CD_____B = 'IAR0' AND PROCESADO='N' --AND NUM_PROCESO='9071'
SELECT max(mc_____numero____b) from con.mc____ where MC_____CODIGO____CONTAB_B = 'FINT'  and MC_____CODIGO____TD_____B = 'ICRN' and
MC_____CODIGO____CD_____B = 'IAR0' AND PROCESADO='S'
and procesado='S' AND mc_____numero____period_b IN(6) and mc_____numdocsop_b IN('385004');
DELETE from con.mc____ where MC_____CODIGO____CONTAB_B = 'FINT'  and MC_____CODIGO____TD_____B = 'ICRN' and MC_____CODIGO____CD_____B = 'IAR0' AND PROCESADO='N'
and mc_____numero____b='5554'
SELECT MC_____NUMERO____PERIOD_B, count(*) from con.mc____ where MC_____CODIGO____CONTAB_B = 'FINT'  and MC_____CODIGO____TD_____B = 'ICRN' and MC_____CODIGO____CD_____B = 'IAR0'
and procesado='N' GROUP BY MC_____NUMERO____PERIOD_B
update con.mc____ set procesado='N' where MC_____CODIGO____CONTAB_B = 'FINT'  and MC_____CODIGO____TD_____B = 'ICRN' and
MC_____CODIGO____CD_____B = 'IAR0' AND PROCESADO='R' and mc_____numero____b IN(5667,
5668,
5669,
5670,
5671,
5672,
5673,
5674,
5675,
5676,
5677,
5678,
5679)
*/

	LOOP
		--------------------------------------------------------------------------------------------------------------------------------------------
		--SE CONSULTA LA TRANSACCION

		--raise notice 'cadena:%',CADENA_;
		SECUENCIA_EXT:=0;
		CONSEC :=1;

		--SECUENCIA DE LA TRANSACCION
		SELECT INTO SECUENCIA_EXT NEXTVAL('CON.INTERFAZ_SECUENCIA_ICA_APOTEOSYS');

		--SE CONSTRUYE EL ASIENTO

		--MCTYPE:=REC_EXT;

		FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_OS.CREATION_DATE,1,7),'-','')=REC_OS.PERIODO THEN REC_OS.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_OS.PERIODO,1,4),SUBSTRING(REC_OS.PERIODO,5,2)::INT)::DATE END ;

		FECHADOC_ := CASE WHEN FECHADOC_::DATE<'2016-12-01'::DATE THEN '2016-12-31'::DATE ELSE FECHADOC_::DATE END;

		if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 6)='S')then
			MCTYPE.MC_____FECHEMIS__B=REC_OS.CREATION_DATE::DATE;
			MCTYPE.MC_____FECHVENC__B=REC_OS.CREATION_DATE::DATE;
		else
			MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
			MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

		end if;

		MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
		MCTYPE.MC_____CODIGO____TD_____B := 'ICRN' ;
		MCTYPE.MC_____CODIGO____CD_____B := 'IAR0'  ;
		MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
		MCTYPE.MC_____FECHA_____B := FECHADOC_;
		--MCTYPE.MC_____FECHA_____B := REC_OS.CREATION_DATE::DATE  ;
		MCTYPE.MC_____NUMERO____B := SECUENCIA_EXT  ;
		MCTYPE.MC_____SECUINTE__B := CONSEC  ;
		MCTYPE.MC_____REFERENCI_B := REC_OS.NUM_INGRESO  ;
		MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_OS.PERIODO,1,4)::INT  ;
		MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_OS.PERIODO,5,2)::INT  ;
		MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
		MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 1)  ;
		MCTYPE.MC_____CODIGO____CU_____B := 	'A1111F21401';
							--'A1111F22201'
							--'A1111F21501';

		--CON.OBTENER_HOMOLOGACION_APOTEOSYS('NOTAAJUSTE', 'FAC', _ARRCUENTASAET[2],'', 2)  ;
		MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(REC_OS.NITCLI)>10 THEN SUBSTR(REC_OS.NITCLI,1,10) ELSE REC_OS.NITCLI END;
		MCTYPE.MC_____DEBMONORI_B := 0  ;
		MCTYPE.MC_____CREMONORI_B := 0 ;

		IF(REC_OS.VALOR_INGRESO<0)THEN
			MCTYPE.MC_____DEBMONLOC_B := REC_OS.valor_ingreso::NUMERIC*-1;
			MCTYPE.MC_____CREMONLOC_B := 0;
		ELSE
			MCTYPE.MC_____DEBMONLOC_B :=0 ;
			MCTYPE.MC_____CREMONLOC_B := REC_OS.valor_ingreso::NUMERIC;
		END IF;

		MCTYPE.MC_____INDTIPMOV_B := 4  ;
		MCTYPE.MC_____INDMOVREV_B := 'N'  ;
		MCTYPE.MC_____OBSERVACI_B := REC_OS.DESCRIPCION||'-'||REC_OS.DOCUMENTO||'-'||REC_OS.NUM_INGRESO;
		MCTYPE.MC_____FECHORCRE_B := REC_OS.CREATION_DATE::TIMESTAMP  ;
		MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
		MCTYPE.MC_____FEHOULMO__B := REC_OS.CREATION_DATE::TIMESTAMP  ;
		MCTYPE.MC_____AUTULTMOD_B := ''  ;
		MCTYPE.MC_____VALIMPCON_B := 0  ;
		MCTYPE.MC_____NUMERO_OPER_B := REC_OS.DOCUMENTO;
		MCTYPE.TERCER_CODIGO____TIT____B := REC_OS.TERCER_CODIGO____TIT____B  ;
		MCTYPE.TERCER_NOMBCORT__B := SUBSTR(REC_OS.TERCER_NOMBCORT__B,1,32)  ;
		MCTYPE.TERCER_NOMBEXTE__B := SUBSTR(REC_OS.TERCER_NOMBEXTE__B,1,64)  ;
		MCTYPE.TERCER_APELLIDOS_B := SUBSTR(REC_OS.TERCER_APELLIDOS_B,1,32)  ;
		MCTYPE.TERCER_CODIGO____TT_____B := REC_OS.TERCER_CODIGO____TT_____B  ;
		MCTYPE.TERCER_DIRECCION_B := SUBSTR(REC_OS.TERCER_DIRECCION_B,1,64)  ;
		MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_os.TERCER_CODIGO____CIUDAD_B  ;
		MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_OS.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_OS.TERCER_TELEFONO1_B,1,15) ELSE REC_OS.TERCER_TELEFONO1_B END;
		MCTYPE.TERCER_TIPOGIRO__B := 1 ;
		MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
		MCTYPE.TERCER_SUCURSAL__B := ''  ;
		MCTYPE.TERCER_NUMECUEN__B := ''  ;
		MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 3);
		--MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
		MCTYPE.MC_____NUMEVENC__B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 5)::INT;

		if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 4)='S')then
			MCTYPE.MC_____NUMDOCSOP_B := REC_OS.DOCUMENTO;
		else
			MCTYPE.MC_____NUMDOCSOP_B := '';
		end if;

		if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA,'', 5)::int=1)then
			MCTYPE.MC_____NUMEVENC__B := 1;
		else
			MCTYPE.MC_____NUMEVENC__B := null;
		end if;

		--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
		SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
		CONSEC:=CONSEC+1;

		MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
		MCTYPE.MC_____SECUINTE__B := CONSEC  ;
		MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA_PLA,'', 1)  ;
		--MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_OS.CUENTA_PLA,'', 2)  ;
		MCTYPE.MC_____OBSERVACI_B :='';

		IF(REC_OS.valor_ingreso<0)THEN
			MCTYPE.MC_____DEBMONLOC_B := 0;
			MCTYPE.MC_____CREMONLOC_B := REC_OS.valor_ingreso::NUMERIC*-1;
		ELSE
			MCTYPE.MC_____DEBMONLOC_B := REC_OS.valor_ingreso::NUMERIC;
			MCTYPE.MC_____CREMONLOC_B := 0;
		END IF;

		MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
		MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
		MCTYPE.MC_____CODIGO____DS_____B:='';
		MCTYPE.MC_____NUMDOCSOP_B := '';
		MCTYPE.MC_____NUMEVENC__B := null;

		SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
		CONSEC:=1;

		IF(SW='S')THEN

			--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
			IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
				SW='N';

				--BORRAMOS EL COMPROBANTE DE EXT
				DELETE FROM CON.MC____
				WHERE MC_____NUMERO____B = SECUENCIA_EXT AND MC_____CODIGO____CONTAB_B = 'FINT'
				 AND MC_____CODIGO____TD_____B = 'ICRN' AND  MC_____CODIGO____CD_____B = 'IAR0'  ;

				CONTINUE;
			END IF;

			--CONSEC:=1;

		END IF;

		--ACTUALIZAMOS EL REGISTRO EN OS PARA SABER QUE SE PROCESO
		IF(SW='S')THEN
			UPDATE
				CON.INGRESO_DETALLE
			SET
				PROCESADO='S'
			WHERE
				DSTRCT='FINV' AND
				TIPO_DOCUMENTO='ICA' AND
				NUM_INGRESO=REC_OS.NUM_INGRESO;

			SW:='N';
		END IF;

	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_logistica_apoteosys_pp_ica_r()
  OWNER TO postgres;
