-- Function: con.interfaz_fintra_logistica_apoteosys_r_cxp_descuadre()

-- DROP FUNCTION con.interfaz_fintra_logistica_apoteosys_r_cxp_descuadre();

CREATE OR REPLACE FUNCTION con.interfaz_fintra_logistica_apoteosys_r_cxp_descuadre()
  RETURNS text AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LOS INGRESOS Y
  *CONTRUYE EL ASIENTO CONTABLE(R) QUE MAS ADELANTE SE TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:= EL ARRAY _ARRCUENTASAET HACE REFERENCIA A LAS CUENTAS PARA
  *REALIZAR LA VERIFICACION DE LAS TRANSACCIONES ASI:
  *13101002,11050508
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-07-11
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_OS RECORD;
 REC_R0 RECORD;
 REC_R1 RECORD;
 REC_R2 RECORD;
 REC_R3 RECORD;
 REC_R RECORD;
 REC_R4 RECORD;
 REC_R5 RECORD;
 REC_R6 RECORD;
 SECUENCIA_R INTEGER;
 CONSEC INTEGER:=1;
 VAL_AET NUMERIC:=0;
 VAL_AGA NUMERIC:=0;
 VAL_EXT NUMERIC:=0;
 PLANILLA_ TEXT:='';
 FECHADOC_ TEXT:='';
 _VAR_CU TEXT:='';
 SW TEXT:='N';
 _ARRCUENTASAET VARCHAR[] :='{13101002,13101001,11050508,13802608}';--IDEAL UN TABLA OJO!!
 MCTYPE CON.TYPE_INSERT_MC;
 CADENA_ TEXT:= '';

BEGIN

--SE CONSULTAN LOS REGISTROS QUE SE VAN A TRANSPORTAR PARA EL BOTON DE INGRESO

	FOR REC_OS IN

		SELECT
			EGRE.NUM_INGRESO, CXP.CORRIDA
		FROM
			EGRESO_TSP EGRE
		INNER JOIN EGRESODET_TSP DETEGRE ON(DETEGRE.reg_status=EGRE.reg_status AND DETEGRE.dstrct=EGRE.dstrct AND DETEGRE.branch_code=EGRE.branch_code
										AND DETEGRE.bank_account_no =EGRE.bank_account_no AND DETEGRE.document_no=EGRE.document_no)
		INNER JOIN FIN.CXP_DOC_TSP  CXP ON(CXP.DSTRCT='TSP' AND CXP.PROVEEDOR=EGRE.NIT AND CXP.TIPO_DOCUMENTO='010' AND CXP.DOCUMENTO=DETEGRE.DOCUMENTO)
		WHERE
		CXP.DSTRCT='TSP' AND
		--CXP.PERIODO='201802' AND
		CXP.REG_STATUS=''
		--AND CXP.DOCUMENTO LIKE 'MT%'
		--AND EGRE.PROCESADO='S'
		--AND DETEGRE.PROCESADO_R='N'
		AND EGRE.NUM_INGRESO IN('IC306075')
		GROUP BY
			EGRE.NUM_INGRESO,  CXP.CORRIDA
		ORDER BY
			EGRE.NUM_INGRESO
		--LIMIT 1

--SELECT con.interfaz_fintra_logistica_apoteosys_r_CXP_descuadre();
--SELECT * FROM con.comprodet where numdoc='NC_CXPIC297688'
/**286439091
SELECT * FROM con.mc____ where mc_____codigo____contab_b='FINT' AND procesado='N' AND MC_____CODIGO____TD_____B = 'CXPN' and num_proceso=8132--AND mc_____codigo____cd_____b='AG'
DELETE FROM con.mc____ where mc_____codigo____contab_b='FINT' and MC_____CODIGO____TD_____B = 'CXPN' AND MC_____NUMERO____B=42803 and procesado='S'
SELECT MC_____NUMERO____PERIOD_B, MC_____NUMERO____B, MC_____CODIGO____CU_____B, count(*) FROM con.mc____ where mc_____codigo____contab_b='FINT' and procesado='N' and
MC_____CODIGO____TD_____B = 'CXPN' group by MC_____NUMERO____PERIOD_B, MC_____NUMERO____B, MC_____CODIGO____CU_____B
delete FROM con.mc____ where mc_____codigo____contab_b='FINT' AND procesado='N' AND MC_____CODIGO____TD_____B = 'CXPN' and num_proceso=8132 AND mc_____codigo____cd_____b='AGLG'
and mc_____secuinte__b in(3,4) AND MC_____CODIGO____TD_____B = 'CXCN' and mc_____codigo____cu_____b='A1111F21501'
UPDATE con.mc____ SET mc_____cremonloc_b=286439091 where mc_____codigo____contab_b='FINT' AND MC_____CODIGO____TD_____B = 'CXCN' and procesado='R'  and mc_____secuinte__b=1
UPDATE con.mc____ SET
--MC_____FECHA_____B='2017-07-31'
--MC_____FECHEMIS__B='2017-07-31',
--MC_____FECHVENC__B='2017-07-31'
procesado='S'
 where mc_____codigo____contab_b='FINT' and procesado='R' AND MC_____NUMERO____B !=43036 AND NUM_PROCESO=8203 and mc_____secuinte__b=2 AND mc_____codigo____cd_____b='NCLG'
*/

	LOOP

			--CXP DE DESCUADRES
			FOR REC_R4 IN
				SELECT
					DOCUMENTO, TIPO_DOCUMENTO, handle_code
				FROM
					FIN.CXP_DOC
				WHERE
					DOCUMENTO LIKE '%'||REC_OS.NUM_INGRESO||'%'
					AND DOCUMENTO IN('NC_CXPIC306075')
					ORDER BY DOCUMENTO

			LOOP

				--SECUENCIA DE LA R
				SELECT INTO SECUENCIA_R NEXTVAL('CON.INTERFAZ_SECUENCIA_CXP_APOTEOSYS');
				VAL_AET :=0;
				VAL_AGA :=0;
				VAL_EXT :=0;
				CONSEC:=1;

				FOR REC_R5 IN

					SELECT
						B.CREATION_DATE,
						--A.PERIODO,
						REPLACE(SUBSTRING(A.FECHA_DOCUMENTO,1,7),'-','') AS PERIODO,
						B.CODIGO_CUENTA AS CUENTA,
						B.VLR,
						CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE B.PROVEEDOR END AS PROVEEDOR,
						(CASE
						 WHEN D.TIPO_IDEN='CED' THEN 'CC'
						 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
						 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
						 'CC' END) AS TERCER_CODIGO____TIT____B,
						C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
						(D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
						(D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
						D.NOMBRE AS TERCER_NOMBEXTE__B,
						 (CASE
						 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
						 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
						 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
						 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
						 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
						D.DIRECCION AS TERCER_DIRECCION_B,
						 (CASE
						 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
						 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
						D.TELEFONO AS TERCER_TELEFONO1_B,
						(SELECT DISTINCT TIPO_OPERACION FROM FIN.ANTICIPOS_PAGOS_TERCEROS
						--WHERE PLANILLA IN(SUBSTR(B.DESCRIPCION, 10, CHAR_LENGTH(B.DESCRIPCION)))
						WHERE PLANILLA IN (
						replace(replace(replace(replace(replace(replace(
						(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
						,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
						)
						AND TIPO_OPERACION!='' limit 1)
						AS TIPO,
						(SELECT CASE WHEN CONCEPT_CODE='01' THEN 'AET'
							WHEN CONCEPT_CODE='10' THEN 'AGA'
							WHEN CONCEPT_CODE='50' THEN 'EXT'
							ELSE '' END
							FROM FIN.ANTICIPOS_PAGOS_TERCEROS
						--WHERE PLANILLA IN(SUBSTR(B.DESCRIPCION, 10, CHAR_LENGTH(B.DESCRIPCION)))
						WHERE PLANILLA IN
						(
						replace(replace(replace(replace(replace(replace(
						(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
						,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
						)
						 limit 1) AS CONCEPT_CODE,
						(select CONCEPTO
						from
						tem.homologacion_planillas_concepto
						WHERE
						-- PLANILLA IN
-- 						(--B.DESCRIPCION
-- 						 replace(replace(replace(replace(replace(replace(
-- 						(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
-- 						,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
-- 						) AND
						DOCUMENTO=A.DOCUMENTO
						limit 1
						) AS CONCEPT_CODE2,
						(
						replace(replace(replace(replace(replace(replace(
						(SUBSTR(B.DESCRIPCION, position('PLANILLA' in UPPER(B.DESCRIPCION))+8, CHAR_LENGTH(B.DESCRIPCION)))
						,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'')
						) AS PLANILLA,
						B.DESCRIPCION,
						A.DOCUMENTO
					FROM
						FIN.CXP_DOC A
					INNER JOIN
						FIN.CXP_ITEMS_DOC B ON(B.DSTRCT=A.DSTRCT AND B.PROVEEDOR=A.PROVEEDOR AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.DOCUMENTO=A.DOCUMENTO)
					LEFT JOIN
						PROVEEDOR C ON(C.NIT=B.PROVEEDOR)
					LEFT JOIN
						NIT D ON(D.CEDULA=C.NIT)
					LEFT JOIN
						CIUDAD E ON(E.CODCIU=D.CODCIU)
					LEFT JOIN
						CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=B.PROVEEDOR)
					WHERE
						A.REG_STATUS='' AND
						A.DOCUMENTO in(REC_R4.DOCUMENTO)

				LOOP

				-- AET	-	DT --> TRANSFERENCIA
				-- AGA	-	DG --> GASOLINA
				-- EXT	-	DA --> PRONTOPAGO

					IF(REC_R4.TIPO_DOCUMENTO in('FAP','ND'))THEN
						MCTYPE.MC_____CODIGO____CD_____B := 'AGLG'  ;
						MCTYPE.MC_____DEBMONLOC_B := REC_R5.VLR;
						IF(REC_R4.HANDLE_CODE IN('DT','DG','DA'))THEN
							IF(REC_R4.HANDLE_CODE='DT')THEN
								VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F21401' ;
							ELSIF(REC_R4.HANDLE_CODE='DG')THEN
								VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F21501';
							ELSIF(REC_R4.HANDLE_CODE='DA')THEN
								VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F22201';
							END IF;
						ELSE
							IF(REC_R5.CONCEPT_CODE2!='')THEN
								IF(REC_R5.CONCEPT_CODE2='AET')THEN
									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21401' ;
								ELSIF(REC_R5.CONCEPT_CODE2='AGA')THEN
									VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21501';
								ELSIF(REC_R5.CONCEPT_CODE2='EXT')THEN
									VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F22201';
-- 								else
-- 									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
-- 									_VAR_CU := 'A1111F21401' ;
								END IF;
							ELSE
								IF(REC_R5.TIPO='AET')THEN
									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21401' ;
								ELSIF(REC_R5.TIPO='AGA')THEN
									VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21501';
								ELSIF(REC_R5.TIPO='EXT')THEN
									VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F22201';
-- 								else
-- 									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
-- 									_VAR_CU := 'A1111F21401' ;
								END IF;
							END IF;
						END IF;

						MCTYPE.MC_____CREMONLOC_B := 0;
					ELSIF(REC_R4.TIPO_DOCUMENTO='NC')THEN
						MCTYPE.MC_____CODIGO____CD_____B := 'NCLG'  ;
						MCTYPE.MC_____CREMONLOC_B := REC_R5.VLR;
-- 						IF(REC_R4.HANDLE_CODE='DT')THEN
-- 							VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
-- 						ELSIF(REC_R4.HANDLE_CODE='DG')THEN
-- 							VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
-- 						ELSIF(REC_R4.HANDLE_CODE='DA')THEN
-- 							VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
-- 						END IF;
						IF(REC_R4.HANDLE_CODE IN('DT','DG','DA'))THEN
							IF(REC_R4.HANDLE_CODE='DT')THEN
								VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F21401' ;
							ELSIF(REC_R4.HANDLE_CODE='DG')THEN
								VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F21501';
							ELSIF(REC_R4.HANDLE_CODE='DA')THEN
								VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
								_VAR_CU := 'A1111F22201';
							END IF;
						ELSE
							IF(REC_R5.CONCEPT_CODE2!='')THEN
								IF(REC_R5.CONCEPT_CODE2='AET')THEN
									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21401' ;
								ELSIF(REC_R5.CONCEPT_CODE2='AGA')THEN
									VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21501';
								ELSIF(REC_R5.CONCEPT_CODE2='EXT')THEN
									VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F22201';
-- 								else
-- 									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
-- 									_VAR_CU := 'A1111F21401' ;
								END IF;
							ELSE
								IF(REC_R5.TIPO='AET')THEN
									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21401' ;
								ELSIF(REC_R5.TIPO='AGA')THEN
									VAL_AGA := VAL_AGA+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21501';
								ELSIF(REC_R5.TIPO='EXT')THEN
									VAL_EXT := VAL_EXT+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F22201';
								else
									VAL_AET := VAL_AET+REC_R5.VLR::NUMERIC;
									_VAR_CU := 'A1111F21401' ;
								END IF;
							END IF;
						END IF;
						MCTYPE.MC_____DEBMONLOC_B := 0;
					END IF;

					FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_R5.CREATION_DATE,1,7),'-','')=REC_R5.PERIODO THEN REC_R5.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_R5.PERIODO,1,4),SUBSTRING(REC_R5.PERIODO,5,2)::INT)::DATE END ;

					MCTYPE.MC_____REFERENCI_B := SUBSTR(REC_OS.NUM_INGRESO,3,CHAR_LENGTH(REC_OS.NUM_INGRESO))||';'||REC_OS.CORRIDA  ;
					MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
					MCTYPE.MC_____CODIGO____TD_____B := 'CXPN' ;
					--MCTYPE.MC_____CODIGO____CD_____B := 'AGLG'  ;
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE  ;
					MCTYPE.MC_____NUMERO____B := SECUENCIA_R  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_R5.PERIODO,1,4)::INT  ;
					MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_R5.PERIODO,5,2)::INT  ;
					MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
					MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('FUNCIONR', 'FAC', REC_R5.CUENTA,'', 1)  ;
					MCTYPE.MC_____CODIGO____CU_____B := _VAR_CU;
					MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(REC_R5.PROVEEDOR)>10 THEN SUBSTR(REC_R5.PROVEEDOR,1,10) ELSE REC_R5.PROVEEDOR END;
					MCTYPE.MC_____DEBMONORI_B := 0  ;
					MCTYPE.MC_____CREMONORI_B := 0 ;
					MCTYPE.MC_____INDTIPMOV_B := 4  ;
					MCTYPE.MC_____INDMOVREV_B := 'N'  ;
					MCTYPE.MC_____OBSERVACI_B := REC_R5.DESCRIPCION||'-'||REC_R4.DOCUMENTO  ;
					MCTYPE.MC_____FECHORCRE_B := REC_R5.CREATION_DATE::TIMESTAMP  ;
					MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
					MCTYPE.MC_____FEHOULMO__B := REC_R5.CREATION_DATE::TIMESTAMP  ;
					MCTYPE.MC_____AUTULTMOD_B := ''  ;
					MCTYPE.MC_____VALIMPCON_B := 0  ;
					MCTYPE.MC_____NUMERO_OPER_B := REC_OS.NUM_INGRESO;
					MCTYPE.TERCER_CODIGO____TIT____B := REC_R5.TERCER_CODIGO____TIT____B  ;
					MCTYPE.TERCER_NOMBCORT__B := SUBSTR(REC_R5.TERCER_NOMBCORT__B,1,32)  ;
					MCTYPE.TERCER_NOMBEXTE__B := SUBSTR(REC_R5.TERCER_NOMBEXTE__B,1,64)  ;
					MCTYPE.TERCER_APELLIDOS_B := SUBSTR(REC_R5.TERCER_APELLIDOS_B,1,32)  ;
					MCTYPE.TERCER_CODIGO____TT_____B := REC_R5.TERCER_CODIGO____TT_____B  ;
					MCTYPE.TERCER_DIRECCION_B := SUBSTR(REC_R5.TERCER_DIRECCION_B,1,64)  ;
					MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_R5.TERCER_CODIGO____CIUDAD_B  ;
					MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_R5.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_R5.TERCER_TELEFONO1_B,1,15) ELSE REC_R5.TERCER_TELEFONO1_B END;
					MCTYPE.TERCER_TIPOGIRO__B := 1 ;
					MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
					MCTYPE.TERCER_SUCURSAL__B := ''  ;
					MCTYPE.TERCER_NUMECUEN__B := ''  ;
					MCTYPE.MC_____CODIGO____DS_____B := '';
					MCTYPE.MC_____NUMDOCSOP_B := '';
					MCTYPE.MC_____NUMEVENC__B := NULL;
					MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
					MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

					--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;
					--RAISE NOTICE 'CONSEC 13: %',CONSEC;

				END LOOP;

				MCTYPE.MC_____CODIGO____DS_____B := 'CXPA';
				MCTYPE.MC_____NUMDOCSOP_B := REC_OS.CORRIDA;
				MCTYPE.MC_____NUMEVENC__B := 1;
				MCTYPE.MC_____OBSERVACI_B := 'DESCUENTO PLANILLA'  ;

				MCTYPE.MC_____FECHEMIS__B=FECHADOC_::DATE;
				MCTYPE.MC_____FECHVENC__B=FECHADOC_::DATE;
				MCTYPE.MC_____CODIGO____CPC____B := '23050103'  ;

				IF(VAL_AET>0)THEN
					-----------------------------------------
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____CODIGO____CU_____B := 'A1111F21401';

					IF(REC_R4.TIPO_DOCUMENTO in('FAP','ND'))THEN
						MCTYPE.MC_____CREMONLOC_B := VAL_AET::NUMERIC;
						MCTYPE.MC_____DEBMONLOC_B := 0;
					ELSIF(REC_R4.TIPO_DOCUMENTO='NC')THEN
						MCTYPE.MC_____CREMONLOC_B := 0;
						MCTYPE.MC_____DEBMONLOC_B := VAL_AET::NUMERIC;

					END IF;

					--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;
					-----------------------------------------
				END IF;

				IF(VAL_AGA>0)THEN
					-----------------------------------------
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____CODIGO____CU_____B := 'A1111F21501';

					IF(REC_R4.TIPO_DOCUMENTO in('FAP','ND'))THEN
						MCTYPE.MC_____CREMONLOC_B := VAL_AGA::NUMERIC;
						MCTYPE.MC_____DEBMONLOC_B := 0;
					ELSIF(REC_R4.TIPO_DOCUMENTO='NC')THEN
						MCTYPE.MC_____CREMONLOC_B := 0;
						MCTYPE.MC_____DEBMONLOC_B := VAL_AGA::NUMERIC;

					END IF;

					--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;
					-----------------------------------------
				END IF;

				IF(VAL_EXT>0)THEN
					-----------------------------------------
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____CODIGO____CU_____B := 'A1111F22201';

					IF(REC_R4.TIPO_DOCUMENTO in('FAP','ND'))THEN
						MCTYPE.MC_____CREMONLOC_B := VAL_EXT::NUMERIC;
						MCTYPE.MC_____DEBMONLOC_B := 0;
					ELSIF(REC_R4.TIPO_DOCUMENTO='NC')THEN
						MCTYPE.MC_____CREMONLOC_B := 0;
						MCTYPE.MC_____DEBMONLOC_B := VAL_EXT::NUMERIC;

					END IF;

					--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;
					-----------------------------------------
				END IF;

				--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
				IF CON.SP_VALIDACIONES(MCTYPE,'LOGISTICA') ='N' THEN
					SW='N';

					--BORRAMOS EL COMPROBANTE DE ING
					IF(REC_R4.TIPO_DOCUMENTO in('FAP','ND'))THEN
						DELETE FROM CON.MC____
						WHERE MC_____NUMERO____B = SECUENCIA_R AND MC_____CODIGO____CONTAB_B = 'FINT'
						 AND MC_____CODIGO____TD_____B = 'CXPN' AND  MC_____CODIGO____CD_____B = 'AGLG'  ;
					ELSIF(REC_R4.TIPO_DOCUMENTO='NC')THEN
						DELETE FROM CON.MC____
						WHERE MC_____NUMERO____B = SECUENCIA_R AND MC_____CODIGO____CONTAB_B = 'FINT'
						 AND MC_____CODIGO____TD_____B = 'CXPN' AND  MC_____CODIGO____CD_____B = 'NCLG'  ;

					END IF;

					CONTINUE;
				END IF;

			END LOOP;

			--------------------------------------------------------------------------------------------------------------------------------------------

			--ACTUALIZAMOS EL REGISTRO EN OS PARA SABER QUE SE PROCESO
			IF(SW='S')THEN
				UPDATE
					EGRESODET_TSP
				SET
					PROCESADO_R='S'
				WHERE
					NUM_INGRESO=REC_OS.NUM_INGRESO;

				SW:='N';
			END IF;
		SW:='N';
	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_logistica_apoteosys_r_cxp_descuadre()
  OWNER TO postgres;
