-- Function: con.interfaz_fintra_logistica_apoteosys_transacciones()

-- DROP FUNCTION con.interfaz_fintra_logistica_apoteosys_transacciones();

CREATE OR REPLACE FUNCTION con.interfaz_fintra_logistica_apoteosys_transacciones()
  RETURNS text AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LAS ORDENES DE SERVICIO Y
  *OBTIENE LOS ANTICIPOS POR TRANSFERENCIA Y CONTRUYE EL ASIENTO
  *CONTABLE QUE MAS ADELANTE SE TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:= EL ARRAY _ARRCUENTASAET HACE REFERENCIA A LAS CUENTAS PARA
  *REALIZAR LA VERIFICACION DE LAS TRANSACCIONES ASI:
  *AET:=I010030024153, FAP:=22050401, FAC:=13802702.
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2017-05-19
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


 REC_OS RECORD;
 REC_AET RECORD;
 REC_EGR RECORD;
 SECUENCIA_TR INTEGER;
 SECUENCIA_EG INTEGER;
 CONSEC INTEGER:=1;
 PLANILLA_ TEXT:='';
 FECHADOC_ TEXT:='';
 SW TEXT:='N';
 _ARRCUENTASAET VARCHAR[] :='{I010030024153,22050401,13802702}';--IDEAL UN TABLA OJO!!
 MCTYPE CON.TYPE_INSERT_MC;

BEGIN

--SE CONSULTAN LOS REGISTROS QUE SE VAN A TRANSPORTAR PARA TRANSFERENCIAS

	FOR REC_OS IN

		SELECT A.NUMERO_OPERACION,
			A.CREATION_DATE,
			A.FACTURA_CXP,
			B.FACTURA_CXC,
			A.EGRESO,
			A.TIPO_OPERACION,
			A.CMC,
			A.PROVEEDOR,
			A.VLR_EXTRACTO,
			A.PORCENTAJE,
			A.VLR_DESCUENTO,
			A.VLR_COMBANCARIA,
			A.VLR_CONSIGNACION_CALCULADA,
			A.VLR_AJUSTE,
			C.FECHA_DOCUMENTO AS FECHA_EMISION_CXP,
			C.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXP,
			D.FECHA_FACTURA AS FECHA_EMISION_CXC,
			D.FECHA_VENCIMIENTO AS FECHA_VENCIMIENTO_CXC,
			A.PROCESADO
		FROM
			FIN.ORDEN_SERVICIO A
		INNER JOIN
			FIN.ORDEN_SERVICIO_DETALLE B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_OPERACION=A.TIPO_OPERACION AND B.NUMERO_OPERACION=A.NUMERO_OPERACION)
		INNER JOIN
			FIN.CXP_DOC C ON(C.TIPO_DOCUMENTO='FAP' AND C.DOCUMENTO=A.FACTURA_CXP AND C.DSTRCT='FINV' AND C.REG_STATUS='')
 		INNER JOIN
 			CON.FACTURA D ON(D.TIPO_DOCUMENTO='FAC' AND D.DOCUMENTO=B.FACTURA_CXC AND D.DSTRCT='FINV' AND D.REG_STATUS='')
		WHERE
			A.REG_STATUS!='A' AND
			A.DSTRCT='FINV' AND
			A.TIPO_OPERACION ='AET' AND
			A.GRUPO_TRANSACCION_OS!=0 AND
			A.PERIODO_OS!='' AND
			A.FECHA_CONTABILIZACION_OS::DATE >= '2014-01-01' AND
			C.FECHA_CONTABILIZACION!='0099-01-01 00:00:00' AND
			D.FECHA_CONTABILIZACION!='0099-01-01 00:00:00' AND
			A.PERIODO_OS = REPLACE(SUBSTRING(CURRENT_DATE,1,7),'-','')
			--AND A.NUMERO_OPERACION='10039897'
			AND A.PROCESADO = 'N'
			ORDER BY A.NUMERO_OPERACION

	LOOP
			--------------------------------------------------------------------------------------------------------------------------------------------
			--SE CONSULTA LA TRANSACCION
			--TIPODOC FAC Y CUENTA 13802702, TRANSFERENCIAS
			--TIPODOC AET Y CUENTA I010030024153, TRANSFERENCIAS
			--TIPODOC FAP Y CUENTA 22050401, TRANSFERENCIAS

			raise notice 'Numero Operacion:%',REC_OS.NUMERO_OPERACION;

			SECUENCIA_TR:=0;
			SECUENCIA_EG:=0;
			PLANILLA_:='';
			CONSEC :=1;

			--SECUENCIA DE LA TRANSACCION
			SELECT INTO SECUENCIA_TR NEXTVAL('CON.INTERFAZ_SECUENCIA_OPER_APOTEOSYS');
			--SECUENCIA DEL EGRESO
			SELECT INTO SECUENCIA_EG NEXTVAL('CON.INTERFAZ_SECUENCIA_EGRESO_APOTEOSYS');

			--CONSULTAMOS LA PLANILLA DE LA ORDEN DE SERVICIO PARA UTILIZARLO COMO REFERENCIA
			SELECT INTO PLANILLA_ PLANILLA FROM FIN.ANTICIPOS_PAGOS_TERCEROS WHERE TIPO_OPERACION='AET' AND NUMERO_OPERACION=REC_OS.NUMERO_OPERACION;

			--SE CONSTRUYE EL ASIENTO POR EL NUMERO DE LA OPERACION
			FOR REC_AET IN

				SELECT
				 A.FECHADOC,
				 B.TIPODOC,
				 B.GRUPO_TRANSACCION,
				 B.PERIODO,
				 B.CUENTA,
				 CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE A.TERCERO END AS TERCERO,
				 --A.TERCERO,
				 B.VALOR_DEBITO,
				 B.VALOR_CREDITO,
				 B.DETALLE,
				 B.CREATION_DATE,
				 B.CREATION_USER,
				 B.LAST_UPDATE,
				 B.USER_UPDATE,
				 (CASE
				 WHEN D.TIPO_IDEN='CED' THEN 'CC'
				 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
				 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
				 'CC' END) AS TERCER_CODIGO____TIT____B,
				 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
				 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
				 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
				 D.NOMBRE AS TERCER_NOMBEXTE__B,
				 (CASE
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
				 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
				 D.DIRECCION AS TERCER_DIRECCION_B,
				 (CASE
				 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
				 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
				 D.TELEFONO AS TERCER_TELEFONO1_B
				FROM
				 CON.COMPROBANTE A
				INNER JOIN CON.COMPRODET B ON(B.DSTRCT=A.DSTRCT AND B.TIPODOC=A.TIPODOC AND B.NUMDOC=A.NUMDOC AND B.GRUPO_TRANSACCION=A.GRUPO_TRANSACCION)
				LEFT JOIN PROVEEDOR C ON(C.NIT=A.TERCERO)
				LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
				LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
				LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=A.TERCERO)
				WHERE
				 A.DSTRCT='FINV' AND
				 ((A.TIPODOC, A.NUMDOC, CUENTA) =('AET',REC_OS.NUMERO_OPERACION, _ARRCUENTASAET[1]) OR
				 (A.TIPODOC, A.NUMDOC, CUENTA) =('FAP',REC_OS.FACTURA_CXP,  _ARRCUENTASAET[2]) OR
				 (A.TIPODOC, A.NUMDOC, CUENTA) =('FAC',REC_OS.FACTURA_CXC,  _ARRCUENTASAET[3]))
				 order by valor_debito desc,tipodoc

			LOOP
				--MCTYPE:=REC_AET;

				FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_OS.CREATION_DATE,1,7),'-','')=REC_AET.PERIODO THEN REC_OS.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_AET.PERIODO,1,4),SUBSTRING(REC_AET.PERIODO,5,2)::INT)::DATE END ;

				IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 6)='S')THEN
					MCTYPE.MC_____FECHEMIS__B=FECHADOC_::DATE;
					MCTYPE.MC_____FECHVENC__B=FECHADOC_::DATE;
				ELSE
					MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
					MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

				END IF;

				--FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_OS.CREATION_DATE,1,7),'-','')=REC_AET.PERIODO THEN REC_OS.CREATION_DATE::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_AET.PERIODO,1,4),SUBSTRING(REC_AET.PERIODO,5,2)::INT)::DATE END ;


				MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
				MCTYPE.MC_____CODIGO____TD_____B := 'OPER' ;
				MCTYPE.MC_____CODIGO____CD_____B := 'AET'  ;
				MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
				MCTYPE.MC_____FECHA_____B := CASE WHEN (REC_OS.CREATION_DATE::DATE > FECHADOC_::DATE AND REPLACE(SUBSTRING(REC_OS.CREATION_DATE,1,7),'-','')=REC_AET.PERIODO)  THEN REC_OS.CREATION_DATE::DATE ELSE FECHADOC_::DATE END;
				--MCTYPE.MC_____FECHA_____B := REC_OS.CREATION_DATE::DATE  ;
				MCTYPE.MC_____NUMERO____B := SECUENCIA_TR  ;
				MCTYPE.MC_____SECUINTE__B := CONSEC  ;
				MCTYPE.MC_____REFERENCI_B := PLANILLA_  ;
				MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_AET.PERIODO,1,4)::INT  ;
				MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_AET.PERIODO,5,2)::INT  ;
				MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
				MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 1)  ;
				MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 2)  ;
				MCTYPE.MC_____IDENTIFIC_TERCER_B := CASE WHEN CHAR_LENGTH(REC_AET.TERCERO)>10 THEN SUBSTR(REC_AET.TERCERO,1,10) ELSE REC_AET.TERCERO END;
				MCTYPE.MC_____DEBMONORI_B := 0  ;
				MCTYPE.MC_____CREMONORI_B := 0 ;
				MCTYPE.MC_____DEBMONLOC_B := REC_AET.VALOR_DEBITO::NUMERIC  ;
				MCTYPE.MC_____CREMONLOC_B := REC_AET.VALOR_CREDITO::NUMERIC  ;
				MCTYPE.MC_____INDTIPMOV_B := 4  ;
				MCTYPE.MC_____INDMOVREV_B := 'N'  ;
				MCTYPE.MC_____OBSERVACI_B := REC_AET.DETALLE  ;
				MCTYPE.MC_____FECHORCRE_B := REC_AET.CREATION_DATE::TIMESTAMP  ;
				MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
				MCTYPE.MC_____FEHOULMO__B := REC_AET.LAST_UPDATE::TIMESTAMP  ;
				MCTYPE.MC_____AUTULTMOD_B := ''  ;
				MCTYPE.MC_____VALIMPCON_B := 0  ;
				MCTYPE.MC_____NUMERO_OPER_B := REC_OS.NUMERO_OPERACION;
				MCTYPE.TERCER_CODIGO____TIT____B := REC_AET.TERCER_CODIGO____TIT____B  ;
				MCTYPE.TERCER_NOMBCORT__B := case when char_length(REC_AET.TERCER_NOMBCORT__B)>32 then substr(REC_AET.TERCER_NOMBCORT__B,1,32) else REC_AET.TERCER_NOMBCORT__B end;
				MCTYPE.TERCER_NOMBEXTE__B := REC_AET.TERCER_NOMBEXTE__B  ;
				MCTYPE.TERCER_APELLIDOS_B := case when char_length(REC_AET.TERCER_APELLIDOS_B)>32 then substr(REC_AET.TERCER_APELLIDOS_B,1,32) else REC_AET.TERCER_APELLIDOS_B end;
				MCTYPE.TERCER_CODIGO____TT_____B := REC_AET.TERCER_CODIGO____TT_____B  ;
				MCTYPE.TERCER_DIRECCION_B := REC_AET.TERCER_DIRECCION_B  ;
				MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_AET.TERCER_CODIGO____CIUDAD_B  ;
				MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_AET.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_AET.TERCER_TELEFONO1_B,1,15) ELSE REC_AET.TERCER_TELEFONO1_B END;
				MCTYPE.TERCER_TIPOGIRO__B := 1 ;
				MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
				MCTYPE.TERCER_SUCURSAL__B := ''  ;
				MCTYPE.TERCER_NUMECUEN__B := ''  ;
				MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 3);
				MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
				MCTYPE.MC_____NUMEVENC__B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 5)::INT;

				IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 4)='S')THEN
					MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
				ELSE
					MCTYPE.MC_____NUMDOCSOP_B := '';
				END IF;

				IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_AET.TIPODOC, REC_AET.CUENTA,'', 5)::INT=1)THEN
					MCTYPE.MC_____NUMEVENC__B := 1;
				ELSE
					MCTYPE.MC_____NUMEVENC__B := NULL;
				END IF;

				--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
				SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
				CONSEC:=CONSEC+1;

			END LOOP;

			--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
			IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
				SW='N';
				CONTINUE;
			END IF;

			CONSEC:=1;

			--------------------------------------------------------------------------------------------------------------------------------------------
			--SE CONSULTA LA TRANSACCION TIPODOC EGR, TRANSFERENCIAS. ESTA TRANSACCION SE PASA COMPLETA
			IF(SW='S')THEN

				FOR REC_EGR IN
					SELECT 	 A.FECHADOC,
						 B.TIPODOC,
						 B.GRUPO_TRANSACCION,
						 B.PERIODO,
						 B.CUENTA,
						 CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE A.TERCERO END AS TERCERO,
						 A.TERCERO,
						 B.VALOR_DEBITO,
						 B.VALOR_CREDITO,
						 B.DETALLE,
						 B.CREATION_DATE,
						 B.CREATION_USER,
						 B.LAST_UPDATE,
						 B.USER_UPDATE,
						 (CASE
						 WHEN D.TIPO_IDEN='CED' THEN 'CC'
						 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
						 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
						 'CC' END) AS TERCER_CODIGO____TIT____B,
						 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
						 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
						 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
						 D.NOMBRE AS TERCER_NOMBEXTE__B,
						 (CASE
						 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
						 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
						 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
						 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
						 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
						 D.DIRECCION AS TERCER_DIRECCION_B,
						 (CASE
						 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
						 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
						 D.TELEFONO AS TERCER_TELEFONO1_B
					FROM
						CON.COMPROBANTE A
					INNER JOIN CON.COMPRODET B ON(B.DSTRCT=A.DSTRCT AND B.TIPODOC=A.TIPODOC AND B.NUMDOC=A.NUMDOC AND B.GRUPO_TRANSACCION=A.GRUPO_TRANSACCION)
					LEFT JOIN PROVEEDOR C ON(C.NIT=A.TERCERO)
					LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
					LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
					LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=A.TERCERO)
					WHERE
					 A.DSTRCT='FINV' AND
					 A.TIPODOC='EGR' AND
					 A.NUMDOC=REC_OS.EGRESO
					 order by valor_debito desc,tipodoc

				LOOP

					IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 6)='S')THEN
						MCTYPE.MC_____FECHEMIS__B=REC_OS.FECHA_EMISION_CXP;
						MCTYPE.MC_____FECHVENC__B=REC_OS.FECHA_VENCIMIENTO_CXP;
					ELSE
						MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
						MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
					END IF;

					FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_EGR.FECHADOC,1,7),'-','')=REC_EGR.PERIODO THEN REC_EGR.FECHADOC::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_EGR.PERIODO,1,4),SUBSTRING(REC_EGR.PERIODO,5,2)::INT)::DATE END ;

					MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
					MCTYPE.MC_____CODIGO____TD_____B := 'EGRN' ;
					MCTYPE.MC_____CODIGO____CD_____B := 'TR'  ;
					MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
					MCTYPE.MC_____FECHA_____B := CASE WHEN (REC_OS.CREATION_DATE::DATE > FECHADOC_::DATE AND REPLACE(SUBSTRING(REC_OS.CREATION_DATE,1,7),'-','')=REC_EGR.PERIODO)  THEN REC_OS.CREATION_DATE::DATE ELSE FECHADOC_::DATE END;
					MCTYPE.MC_____NUMERO____B := SECUENCIA_EG  ;
					MCTYPE.MC_____SECUINTE__B := CONSEC  ;
					MCTYPE.MC_____REFERENCI_B := PLANILLA_  ;
					MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_EGR.PERIODO,1,4)::INT  ;
					MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_EGR.PERIODO,5,2)::INT  ;
					MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
					MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 1)  ;
					MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 2)  ;
					MCTYPE.MC_____IDENTIFIC_TERCER_B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCERO)>10 THEN SUBSTR(REC_EGR.TERCERO,1,10) ELSE REC_EGR.TERCERO END;
					MCTYPE.MC_____DEBMONORI_B := 0  ;
					MCTYPE.MC_____CREMONORI_B := 0 ;
					MCTYPE.MC_____DEBMONLOC_B := REC_EGR.VALOR_DEBITO::NUMERIC  ;
					MCTYPE.MC_____CREMONLOC_B := REC_EGR.VALOR_CREDITO::NUMERIC  ;
					MCTYPE.MC_____INDTIPMOV_B := 4  ;
					MCTYPE.MC_____INDMOVREV_B := 'N'  ;
					MCTYPE.MC_____OBSERVACI_B := REC_EGR.DETALLE  ;
					MCTYPE.MC_____FECHORCRE_B := REC_EGR.CREATION_DATE::TIMESTAMP  ;
					MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
					MCTYPE.MC_____FEHOULMO__B := REC_EGR.LAST_UPDATE::TIMESTAMP  ;
					MCTYPE.MC_____AUTULTMOD_B := ''  ;
					MCTYPE.MC_____VALIMPCON_B := 0  ;
					MCTYPE.MC_____NUMERO_OPER_B := REC_OS.NUMERO_OPERACION;
					MCTYPE.TERCER_CODIGO____TIT____B := REC_EGR.TERCER_CODIGO____TIT____B  ;
					MCTYPE.TERCER_NOMBCORT__B := case when char_length(REC_EGR.TERCER_NOMBCORT__B)>32 then substr(REC_EGR.TERCER_NOMBCORT__B,1,32) else REC_EGR.TERCER_NOMBCORT__B end;
					MCTYPE.TERCER_NOMBEXTE__B := REC_EGR.TERCER_NOMBEXTE__B  ;
					MCTYPE.TERCER_APELLIDOS_B := case when char_length(REC_EGR.TERCER_APELLIDOS_B)>32 then substr(REC_EGR.TERCER_APELLIDOS_B,1,32) else REC_EGR.TERCER_APELLIDOS_B end;
					MCTYPE.TERCER_CODIGO____TT_____B := REC_EGR.TERCER_CODIGO____TT_____B  ;
					MCTYPE.TERCER_DIRECCION_B := REC_EGR.TERCER_DIRECCION_B  ;
					MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_EGR.TERCER_CODIGO____CIUDAD_B  ;
					MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_EGR.TERCER_TELEFONO1_B,1,15) ELSE REC_EGR.TERCER_TELEFONO1_B END;
					MCTYPE.TERCER_TIPOGIRO__B := 1 ;
					MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
					MCTYPE.TERCER_SUCURSAL__B := ''  ;
					MCTYPE.TERCER_NUMECUEN__B := ''  ;
					MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 3);

					IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 4)='S')THEN
						MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
					ELSE
						MCTYPE.MC_____NUMDOCSOP_B := '';
					END IF;

					IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 5)::INT=1)THEN
						MCTYPE.MC_____NUMEVENC__B := 1;
					ELSE
						MCTYPE.MC_____NUMEVENC__B := NULL;
					END IF;


					--FUNCION PARA INSERTAR EL REGISTRO EN LA TABLA TEMPORAL DE FINTRA
					SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
					CONSEC:=CONSEC+1;

				END LOOP;

				--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
				IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
					SW='N';

					--BORRAMOS EL COMPROBANTE DE AET
					DELETE FROM CON.MC____
					WHERE MC_____NUMERO____B = SECUENCIA_TR AND MC_____CODIGO____CONTAB_B = 'FINT'
				         AND MC_____CODIGO____TD_____B = 'OPER' AND  MC_____CODIGO____CD_____B = 'AET'  ;

					CONTINUE;
				END IF;

				--CONSEC:=1;

			END IF;

			--ACTUALIZAMOS EL REGISTRO EN OS PARA SABER QUE SE PROCESO
			IF(SW='S')THEN
				UPDATE
					FIN.ORDEN_SERVICIO
				SET
					PROCESADO='S'
				WHERE
					DSTRCT='FINV' AND
					TIPO_OPERACION='AET' AND
					NUMERO_OPERACION=REC_OS.NUMERO_OPERACION;

				SW:='N';
			END IF;

	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_logistica_apoteosys_transacciones()
  OWNER TO postgres;
