-- Function: con.interfaz_fintra_ut_apoteosys_egresos()

-- DROP FUNCTION con.interfaz_fintra_ut_apoteosys_egresos();

CREATE OR REPLACE FUNCTION con.interfaz_fintra_ut_apoteosys_egresos()
  RETURNS text AS
$BODY$

DECLARE

 /************************************************
  *DESCRIPCION: ESTA FUNCION TOMA LOS EGRESOS DE UT Y
  *CONTRUYE EL ASIENTO CONTABLE QUE MAS ADELANTE SE
  *TRASLADARA A APOTEOSYS.
  *DOCUMENTACION:=
  *AUTOR:=@JZAPATA
  *FECHA CREACION:=2018-01-18
  *LAST_UPDATE
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/

 REC_OS RECORD;
 REC_EGR RECORD;
 SECUENCIA_EG INTEGER;
 CONSEC INTEGER:=1;
 FECHADOC_ TEXT:='';
 SW TEXT:='N';
 MCTYPE CON.TYPE_INSERT_MC;


 BEGIN

	FOR REC_OS IN

		SELECT
			EGRESO
		FROM
			CON.PLANILLAS_PROCESADAS_UT
		WHERE
			PROCESADO_NACIMIENTO='S' AND
			PROCESADO_EGRESO='N' AND
			replace(substring(CREATION_DATE_PLANILLA,1,7),'-','')=replace(substring(now(),1,7),'-','')
			--replace(substring(CREATION_DATE_PLANILLA,1,7),'-','')='201802'
		group by egreso


/**
select con.interfaz_fintra_ut_apoteosys_egresos();
select * from con.comprodet where numdoc='PT00008_4'
SELECT * FROM con.planillas_procesadas_ut;
update con.planillas_procesadas_ut set egreso='N';
delete from con.mc____ where MC_____CODIGO____TD_____B = 'OPER' and MC_____CODIGO____CD_____B = 'AET' and procesado IN('R','N','S') and MC_____OBSERVACI_B like '%-UT';
DELETE FROM CON.PLANILLAS_PROCESADAS_UT ;
delete from con.mc____ where MC_____CODIGO____TD_____B = 'EGRN' and MC_____CODIGO____CD_____B = 'TR' and procesado='S' and MC_____OBSERVACI_B like '%-UT';
*/

	LOOP

		raise notice 'Egreso: %',REC_OS.EGRESO;

		SECUENCIA_EG:=0;
		CONSEC :=1;

		--SECUENCIA DE LA TRANSACCION
		SELECT INTO SECUENCIA_EG NEXTVAL('CON.INTERFAZ_SECUENCIA_EGRESO_APOTEOSYS');

		FOR REC_EGR IN

			SELECT 	 A.FECHADOC,
				 B.TIPODOC,
				 B.GRUPO_TRANSACCION,
				 B.PERIODO,
				 B.CUENTA,
				 B.DOCUMENTO_REL,
				 CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE B.TERCERO END AS TERCERO,
				 A.TERCERO,
				 B.VALOR_DEBITO,
				 B.VALOR_CREDITO,
				 B.DETALLE,
				 B.CREATION_DATE,
				 B.CREATION_USER,
				 B.LAST_UPDATE,
				 B.USER_UPDATE,
				 (CASE
				 WHEN D.TIPO_IDEN='CED' THEN 'CC'
				 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
				 WHEN D.TIPO_IDEN='NIT' THEN 'NIT' ELSE
				 'CC' END) AS TERCER_CODIGO____TIT____B,
				 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
				 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
				 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
				 D.NOMBRE AS TERCER_NOMBEXTE__B,
				 (CASE
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
				 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
				 D.DIRECCION AS TERCER_DIRECCION_B,
				 (CASE
				 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
				 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
				 D.TELEFONO AS TERCER_TELEFONO1_B
			FROM
				CON.COMPROBANTE A
			INNER JOIN CON.COMPRODET B ON(B.DSTRCT=A.DSTRCT AND B.TIPODOC=A.TIPODOC AND B.NUMDOC=A.NUMDOC AND B.GRUPO_TRANSACCION=A.GRUPO_TRANSACCION)
			LEFT JOIN PROVEEDOR C ON(C.NIT=B.TERCERO)
			LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
			LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
			LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=B.TERCERO)
			WHERE
			 A.DSTRCT='FINV' AND
			 A.TIPODOC='EGR' AND
			 A.NUMDOC=REC_OS.EGRESO
			 order by valor_debito desc,tipodoc

		LOOP

			raise notice 'Documento Relacionado: %',REC_EGR.DOCUMENTO_REL;

			FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(REC_EGR.FECHADOC,1,7),'-','')=REC_EGR.PERIODO THEN REC_EGR.FECHADOC::DATE ELSE con.sp_fecha_corte_mes(SUBSTRING(REC_EGR.PERIODO,1,4),SUBSTRING(REC_EGR.PERIODO,5,2)::INT)::DATE END ;

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 6)='S')THEN
				MCTYPE.MC_____FECHEMIS__B=FECHADOC_;
				MCTYPE.MC_____FECHVENC__B=FECHADOC_;
			ELSE
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
			END IF;

			MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
			MCTYPE.MC_____CODIGO____TD_____B := 'EGRN' ;
			MCTYPE.MC_____CODIGO____CD_____B := 'TR'  ;
			MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
			MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE;
			MCTYPE.MC_____NUMERO____B := SECUENCIA_EG  ;
			MCTYPE.MC_____SECUINTE__B := CONSEC  ;
			MCTYPE.MC_____REFERENCI_B := REC_OS.EGRESO ;
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(REC_EGR.PERIODO,1,4)::INT  ;
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(REC_EGR.PERIODO,5,2)::INT  ;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 1)  ;
			MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 2)  ;
			MCTYPE.MC_____IDENTIFIC_TERCER_B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCERO)>10 THEN SUBSTR(REC_EGR.TERCERO,1,10) ELSE REC_EGR.TERCERO END;
			MCTYPE.MC_____DEBMONORI_B := 0  ;
			MCTYPE.MC_____CREMONORI_B := 0 ;
			MCTYPE.MC_____DEBMONLOC_B := REC_EGR.VALOR_DEBITO::NUMERIC  ;
			MCTYPE.MC_____CREMONLOC_B := REC_EGR.VALOR_CREDITO::NUMERIC  ;
			MCTYPE.MC_____INDTIPMOV_B := 4  ;
			MCTYPE.MC_____INDMOVREV_B := 'N'  ;
			MCTYPE.MC_____OBSERVACI_B := REC_EGR.DETALLE||';'||REC_EGR.DOCUMENTO_REL||'-UT';
			MCTYPE.MC_____FECHORCRE_B := REC_EGR.CREATION_DATE::TIMESTAMP  ;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
			MCTYPE.MC_____FEHOULMO__B := REC_EGR.LAST_UPDATE::TIMESTAMP  ;
			MCTYPE.MC_____AUTULTMOD_B := ''  ;
			MCTYPE.MC_____VALIMPCON_B := 0  ;
			MCTYPE.MC_____NUMERO_OPER_B := REC_OS.EGRESO;
			MCTYPE.TERCER_CODIGO____TIT____B := REC_EGR.TERCER_CODIGO____TIT____B  ;
			MCTYPE.TERCER_NOMBCORT__B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCER_NOMBCORT__B)>32 THEN SUBSTR(REC_EGR.TERCER_NOMBCORT__B,1,32) ELSE REC_EGR.TERCER_NOMBCORT__B END;
			MCTYPE.TERCER_NOMBEXTE__B := REC_EGR.TERCER_NOMBEXTE__B  ;
			MCTYPE.TERCER_APELLIDOS_B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCER_APELLIDOS_B)>32 THEN SUBSTR(REC_EGR.TERCER_APELLIDOS_B,1,32) ELSE REC_EGR.TERCER_APELLIDOS_B END;
			MCTYPE.TERCER_CODIGO____TT_____B := REC_EGR.TERCER_CODIGO____TT_____B  ;
			MCTYPE.TERCER_DIRECCION_B := REC_EGR.TERCER_DIRECCION_B  ;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := REC_EGR.TERCER_CODIGO____CIUDAD_B  ;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(REC_EGR.TERCER_TELEFONO1_B)>15 THEN SUBSTR(REC_EGR.TERCER_TELEFONO1_B,1,15) ELSE REC_EGR.TERCER_TELEFONO1_B END;
			MCTYPE.TERCER_TIPOGIRO__B := 1 ;
			MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
			MCTYPE.TERCER_SUCURSAL__B := ''  ;
			MCTYPE.TERCER_NUMECUEN__B := ''  ;
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 3);

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 4)='S')THEN
				MCTYPE.MC_____NUMDOCSOP_B := REC_EGR.DOCUMENTO_REL;
			ELSE
				MCTYPE.MC_____NUMDOCSOP_B := '';
			END IF;

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('TRANSFERENCIA', REC_EGR.TIPODOC, REC_EGR.CUENTA,'', 5)::INT=1)THEN
				MCTYPE.MC_____NUMEVENC__B := 1;
			ELSE
				MCTYPE.MC_____NUMEVENC__B := NULL;
			END IF;


			--FUNCION PARA INSERTAR EL REGISTRO EN LA TABLA TEMPORAL DE FINTRA
			SW:=CON.SP_INSERT_TABLE_MC( MCTYPE);
			CONSEC:=CONSEC+1;

		END LOOP;

		--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
		IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
			SW='N';

			--BORRAMOS EL COMPROBANTE DE AET
			DELETE FROM CON.MC____
			WHERE MC_____NUMERO____B = SECUENCIA_EG AND MC_____CODIGO____CONTAB_B = 'FINT'
			 AND MC_____CODIGO____TD_____B = 'OPER' AND  MC_____CODIGO____CD_____B = 'EGRN'  ;

			CONTINUE;
		END IF;

		--ACTUALIZAMOS EL REGISTRO EN OS PARA SABER QUE SE PROCESO
		IF(SW='S')THEN
			UPDATE
				con.planillas_procesadas_ut
			SET
				PROCESADO_EGRESO='S'
			WHERE
				egreso=rec_os.EGRESO;

			SW:='N';
		END IF;

	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_fintra_ut_apoteosys_egresos()
  OWNER TO postgres;
