-- Function: con.interfaz_logistica_cdiario_apoteosys()

-- DROP FUNCTION con.interfaz_logistica_cdiario_apoteosys();

CREATE OR REPLACE FUNCTION con.interfaz_logistica_cdiario_apoteosys()
  RETURNS text AS
$BODY$

DECLARE
	r_cdiario record;
	r_asiento record;
	SECUENCIA_GEN INTEGER;
	FECHADOC_ TEXT:='';
	MCTYPE CON.TYPE_INSERT_MC;
	SW TEXT:='N';
	CONSEC INTEGER:=1;

BEGIN

	FOR r_cdiario IN

		SELECT
			TIPODOC,
			NUMDOC,
			PERIODO,
			FECHADOC,
			TOTAL_DEBITO
		FROM
			CON.COMPROBANTE
		WHERE
			--NUMDOC='CD17056363' AND
			REG_STATUS=''
			-- AND DSTRCT='FINV'
 			AND TIPODOC='CDIAR'
-- 			AND DETALLE ILIKE '%ANTICIPOS%'
			--AND PERIODO='201707'--REPLACE(SUBSTRING(CURRENT_DATE,1,7),'-','')
			--AND (REF_2='N' OR REF_2='')
			AND NUMDOC='CD17090015'
		ORDER BY
			NUMDOC
--SELECT * FROM con.factura where documento='R0033815'

/**
SELECT con.interfaz_logistica_cdiario_apoteosys();
*/

/**
select MC_____CODIGO____CD_____B, MC_____NUMERO____PERIOD_B, mc_____numero____b, COUNT(*) from con.mc____  where procesado in('N') and MC_____CODIGO____TD_____B='DIAR'
GROUP BY MC_____CODIGO____CD_____B, MC_____NUMERO____PERIOD_B, mc_____numero____b;
select * from con.mc____  where procesado in('N') and MC_____CODIGO____TD_____B='DIAR';
DELETE from con.mc____  where procesado='N' and MC_____CODIGO____TD_____B='DIAR';
update con.mc____  set procesado='X' where procesado='N' and MC_____CODIGO____TD_____B='DIAR';
*/

	LOOP

		SELECT INTO SECUENCIA_GEN NEXTVAL('CON.INTERFAZ_SECUENCIA_EGRESO_APOTEOSYS');

		For r_asiento in

			SELECT
				com.numdoc,
				comp.cuenta,
				substr(com.tipodoc,1,3) as tipo_documento,
				com.creation_date,
				com.periodo,
				com.detalle as descripcion,
				--com.tercero,
				comp.valor_debito,
				comp.valor_credito,
				--comp.tercero,
				CASE WHEN HT.NIT_APOTEOSYS IS NOT NULL THEN HT.NIT_APOTEOSYS ELSE comp.tercero END AS tercero,
				comp.detalle,
				(CASE
				 WHEN D.TIPO_IDEN='CED' THEN 'CC'
				 WHEN D.TIPO_IDEN='RIF' THEN 'CE'
				 WHEN D.TIPO_IDEN='' THEN 'CC'
				 WHEN D.TIPO_IDEN='NIT' THEN 'NIT'
				 ELSE
				 'CC' END) AS TERCER_CODIGO____TIT____B,
				 C.DIGITO_VERIFICACION AS TERCER_DIGICHEQ__B,
				 (D.NOMBRE1||' '||D.NOMBRE2) AS TERCER_NOMBCORT__B,
				 (D.APELLIDO1||' '||D.APELLIDO2) AS TERCER_APELLIDOS_B,
				 D.NOMBRE AS TERCER_NOMBEXTE__B,
				 (CASE
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='N' THEN 'RCOM'
				 WHEN C.GRAN_CONTRIBUYENTE='N' AND C.AGENTE_RETENEDOR='S' THEN 'RCAU'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='N' THEN 'GCON'
				 WHEN C.GRAN_CONTRIBUYENTE='S' AND C.AGENTE_RETENEDOR='S' THEN 'GCAU'
				 ELSE 'PNAL' END) AS TERCER_CODIGO____TT_____B,
				 D.DIRECCION AS TERCER_DIRECCION_B,
				 (CASE
				 WHEN E.CODIGO_DANE2!='' THEN E.CODIGO_DANE2
				 ELSE '08001' END) AS TERCER_CODIGO____CIUDAD_B,
				 D.TELEFONO AS TERCER_TELEFONO1_B
			FROM
				con.comprobante com
			INNER JOIN con.comprodet comp on(comp.tipodoc=com.tipodoc and comp.numdoc=com.numdoc)
			LEFT JOIN PROVEEDOR C ON(C.NIT=comp.tercero)
			LEFT JOIN NIT D ON(D.CEDULA=C.NIT)
			LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
			LEFT JOIN CON.HOMOLOGA_TERCEROS HT ON(HT.NIT_FINTRA=COMP.TERCERO)
			WHERE
				COM.TIPODOC='CDIAR' AND
				COM.NUMDOC=r_cdiario.numdoc AND
				(COMP.VALOR_DEBITO!=0 OR COMP.VALOR_CREDITO!=0)

		LOOP

			FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(r_cdiario.FECHADOC::DATE,1,7),'-','')=r_cdiario.PERIODO THEN r_cdiario.FECHADOC::DATE ELSE CON.SP_FECHA_CORTE_MES(SUBSTRING(r_cdiario.PERIODO,1,4),SUBSTRING(r_cdiario.PERIODO,5,2)::INT)::DATE END ;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 6)='S')then
				MCTYPE.MC_____FECHEMIS__B = FECHADOC_::DATE;
				MCTYPE.MC_____FECHVENC__B = FECHADOC_::DATE;
			else
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';

			end if;

			MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT' ;
			MCTYPE.MC_____CODIGO____TD_____B := 'DIAR' ;
			MCTYPE.MC_____CODIGO____CD_____B := 'CDLG'  ;
			MCTYPE.MC_____SECUINTE__DCD____B := CONSEC  ;
			MCTYPE.MC_____FECHA_____B := FECHADOC_::DATE  ;
			MCTYPE.MC_____NUMERO____B := SECUENCIA_GEN  ;
			MCTYPE.MC_____SECUINTE__B := CONSEC  ;
			MCTYPE.MC_____REFERENCI_B := R_CDIARIO.NUMDOC;
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING(R_ASIENTO.PERIODO,1,4)::INT;
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING(R_ASIENTO.PERIODO,5,2)::INT;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF' ;
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 1)  ;
			MCTYPE.MC_____CODIGO____CU_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 2)  ;
			MCTYPE.MC_____IDENTIFIC_TERCER_B :=  CASE WHEN CHAR_LENGTH(R_ASIENTO.tercero)>10 THEN SUBSTR(R_ASIENTO.tercero,1,10) ELSE R_ASIENTO.tercero END;
			MCTYPE.MC_____DEBMONORI_B := 0  ;
			MCTYPE.MC_____CREMONORI_B := 0 ;
			MCTYPE.MC_____DEBMONLOC_B := R_ASIENTO.VALOR_DEBITO::NUMERIC  ;
			MCTYPE.MC_____CREMONLOC_B := R_ASIENTO.VALOR_CREDITO::NUMERIC  ;
			MCTYPE.MC_____INDTIPMOV_B := 4  ;
			MCTYPE.MC_____INDMOVREV_B := 'N'  ;
			MCTYPE.MC_____OBSERVACI_B := R_ASIENTO.DESCRIPCION  ;
			MCTYPE.MC_____FECHORCRE_B := R_ASIENTO.CREATION_DATE::TIMESTAMP  ;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN'  ;
			MCTYPE.MC_____FEHOULMO__B := R_ASIENTO.CREATION_DATE::TIMESTAMP  ;
			MCTYPE.MC_____AUTULTMOD_B := ''  ;
			MCTYPE.MC_____VALIMPCON_B := 0  ;
			MCTYPE.MC_____NUMERO_OPER_B := r_cdiario.numdoc;
			MCTYPE.TERCER_CODIGO____TIT____B := R_ASIENTO.TERCER_CODIGO____TIT____B  ;
			MCTYPE.TERCER_NOMBCORT__B := R_ASIENTO.TERCER_NOMBCORT__B  ;
			MCTYPE.TERCER_NOMBEXTE__B := R_ASIENTO.TERCER_NOMBEXTE__B  ;
			MCTYPE.TERCER_APELLIDOS_B := R_ASIENTO.TERCER_APELLIDOS_B  ;
			MCTYPE.TERCER_CODIGO____TT_____B := R_ASIENTO.TERCER_CODIGO____TT_____B  ;
			MCTYPE.TERCER_DIRECCION_B := R_ASIENTO.TERCER_DIRECCION_B  ;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := R_ASIENTO.TERCER_CODIGO____CIUDAD_B  ;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(R_ASIENTO.TERCER_TELEFONO1_B)>15 THEN SUBSTR(R_ASIENTO.TERCER_TELEFONO1_B,1,15) ELSE R_ASIENTO.TERCER_TELEFONO1_B END;
			MCTYPE.TERCER_TIPOGIRO__B := 1 ;
			MCTYPE.TERCER_CODIGO____EF_____B := ''  ;
			MCTYPE.TERCER_SUCURSAL__B := ''  ;
			MCTYPE.TERCER_NUMECUEN__B := ''  ;
			MCTYPE.MC_____BASE______B := CASE WHEN R_ASIENTO.cuenta in('23680107','23653507') THEN r_cdiario.total_debito ELSE 0 END;
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 3);
			--MCTYPE.MC_____NUMDOCSOP_B := REC_OS.NUMERO_OPERACION;
			MCTYPE.MC_____NUMEVENC__B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 5)::INT;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 4)='S')then
				MCTYPE.MC_____NUMDOCSOP_B := 'AGA'||replace(replace(replace(replace(replace(replace(
						--(SUBSTR(r_asiento.detalle, position('PLANILLA' in UPPER(r_asiento.detalle))+8, 8))
						r_asiento.detalle
						,chr(10),''),chr(11),''),chr(13),''),chr(27),''),chr(32),''),chr(39),'');
			else
				MCTYPE.MC_____NUMDOCSOP_B := '';
			end if;

			if(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CDIARIO_R', R_ASIENTO.TIPO_DOCUMENTO, R_ASIENTO.CUENTA,'', 5)::int=1)then
				MCTYPE.MC_____NUMEVENC__B := 1;
			else
				MCTYPE.MC_____NUMEVENC__B := null;
			end if;

			-- Insertamos en la tabla de Apoteosys
			--FUNCION QUE TRANSACCION POR TIPO DE DOCUMENTO EN TABLA TEMPORAL EN FINTRA.
			SW:=CON.SP_INSERT_TABLE_MC(MCTYPE);
			CONSEC:=CONSEC+1;

		END LOOP;

		--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
		IF CON.SP_VALIDACIONES(MCTYPE, 'LOGISTICA') ='N' THEN
			SW='N';

			--BORRAMOS EL COMPROBANTE DE EXT
			DELETE FROM CON.MC____
			WHERE MC_____NUMERO____B = SECUENCIA_GEN AND MC_____CODIGO____CONTAB_B = 'FINT'
			 AND MC_____CODIGO____TD_____B = 'DIAR' AND  MC_____CODIGO____CD_____B = 'CDLG'  ;

			CONTINUE;
		END IF;

		-- ACTUALIZAMOS EL CAMPO DE APOTEOSYS DE LA CABECERA DEL CRéDITO PARA INDICAR QUE YA SE ENVíO
		IF(SW='S')THEN

			UPDATE
				con.comprobante
			set
				ref_2='S'
			where
				tipodoc=r_cdiario.tipodoc and
				numdoc=r_cdiario.numdoc;

			SW:='N';
		END IF;

		CONSEC:=1;


	END LOOP;

	RETURN 'OK';

END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_logistica_cdiario_apoteosys()
  OWNER TO postgres;
