-- View: con.factura_dblink

-- DROP VIEW con.factura_dblink;

CREATE OR REPLACE VIEW con.factura_dblink AS
 SELECT facturaselectrik.reg_status, facturaselectrik.dstrct, facturaselectrik.tipo_documento, facturaselectrik.documento, facturaselectrik.nit, facturaselectrik.codcli, facturaselectrik.concepto, facturaselectrik.fecha_factura, facturaselectrik.fecha_vencimiento, facturaselectrik.fecha_ultimo_pago, facturaselectrik.fecha_impresion, facturaselectrik.descripcion, facturaselectrik.observacion, facturaselectrik.valor_factura, facturaselectrik.valor_abono, facturaselectrik.valor_saldo, facturaselectrik.valor_facturame, facturaselectrik.valor_abonome, facturaselectrik.valor_saldome, facturaselectrik.valor_tasa, facturaselectrik.moneda, facturaselectrik.cantidad_items, facturaselectrik.forma_pago, facturaselectrik.agencia_facturacion, facturaselectrik.agencia_cobro, facturaselectrik.zona, facturaselectrik.clasificacion1, facturaselectrik.clasificacion2, facturaselectrik.clasificacion3, facturaselectrik.transaccion, facturaselectrik.transaccion_anulacion, facturaselectrik.fecha_contabilizacion, facturaselectrik.fecha_anulacion, facturaselectrik.fecha_contabilizacion_anulacion, facturaselectrik.base, facturaselectrik.last_update, facturaselectrik.user_update, facturaselectrik.creation_date, facturaselectrik.creation_user, facturaselectrik.fecha_probable_pago, facturaselectrik.flujo, facturaselectrik.rif, facturaselectrik.cmc, facturaselectrik.usuario_anulo, facturaselectrik.formato, facturaselectrik.agencia_impresion, facturaselectrik.periodo, facturaselectrik.valor_tasa_remesa, facturaselectrik.negasoc, facturaselectrik.num_doc_fen, facturaselectrik.obs, facturaselectrik.pagado_fenalco, facturaselectrik.corficolombiana, facturaselectrik.tipo_ref1, facturaselectrik.ref1, facturaselectrik.tipo_ref2, facturaselectrik.ref2, facturaselectrik.dstrct_ultimo_ingreso, facturaselectrik.tipo_documento_ultimo_ingreso, facturaselectrik.num_ingreso_ultimo_ingreso, facturaselectrik.item_ultimo_ingreso, facturaselectrik.fec_envio_fiducia, facturaselectrik.nit_enviado_fiducia, facturaselectrik.tipo_referencia_1, facturaselectrik.referencia_1, facturaselectrik.tipo_referencia_2, facturaselectrik.referencia_2, facturaselectrik.tipo_referencia_3, facturaselectrik.referencia_3, facturaselectrik.nc_traslado, facturaselectrik.fecha_nc_traslado, facturaselectrik.tipo_nc, facturaselectrik.numero_nc, facturaselectrik.factura_traslado, facturaselectrik.factoring_formula_aplicada, facturaselectrik.nit_endoso, facturaselectrik.devuelta, facturaselectrik.fc_eca, facturaselectrik.fc_bonificacion, facturaselectrik.indicador_bonificacion, facturaselectrik.fi_bonificacion, facturaselectrik.endoso_fenalco, facturaselectrik.cxc_traslado
   FROM dblink('dbname=selectrik port=5432 host=localhost user=postgres password=bdversion17'::text, 'SELECT reg_status, dstrct, tipo_documento, documento, nit, codcli, concepto,
					       fecha_factura, fecha_vencimiento, fecha_ultimo_pago, fecha_impresion,
					       descripcion, observacion, valor_factura, valor_abono, valor_saldo,
					       valor_facturame, valor_abonome, valor_saldome, valor_tasa, moneda,
					       cantidad_items, forma_pago, agencia_facturacion, agencia_cobro,
					       zona, clasificacion1, clasificacion2, clasificacion3, transaccion,
					       transaccion_anulacion, fecha_contabilizacion, fecha_anulacion,
					       fecha_contabilizacion_anulacion, base, last_update, user_update,
					       creation_date, creation_user, fecha_probable_pago, flujo, rif,
					       cmc, usuario_anulo, formato, agencia_impresion, periodo, valor_tasa_remesa,
					       negasoc, num_doc_fen, obs, pagado_fenalco, corficolombiana, tipo_ref1,
					       ref1, tipo_ref2, ref2, dstrct_ultimo_ingreso, tipo_documento_ultimo_ingreso,
					       num_ingreso_ultimo_ingreso, item_ultimo_ingreso, fec_envio_fiducia,
					       nit_enviado_fiducia, tipo_referencia_1, referencia_1, tipo_referencia_2,
					       referencia_2, tipo_referencia_3, referencia_3, nc_traslado, fecha_nc_traslado,
					       tipo_nc, numero_nc, factura_traslado, factoring_formula_aplicada,
					       nit_endoso, devuelta, fc_eca, fc_bonificacion, indicador_bonificacion,
					       fi_bonificacion, endoso_fenalco, cxc_traslado
					FROM con.factura WHERE tipo_documento=''FAC'' AND reg_status='''''::text) facturaselectrik(reg_status character varying, dstrct character varying, tipo_documento character varying, documento character varying, nit character varying, codcli character varying, concepto character varying, fecha_factura date, fecha_vencimiento date, fecha_ultimo_pago date, fecha_impresion timestamp without time zone, descripcion text, observacion text, valor_factura moneda, valor_abono moneda, valor_saldo moneda, valor_facturame moneda, valor_abonome moneda, valor_saldome moneda, valor_tasa numeric, moneda character varying, cantidad_items numeric, forma_pago character varying, agencia_facturacion character varying, agencia_cobro character varying, zona character varying, clasificacion1 character varying, clasificacion2 character varying, clasificacion3 character varying, transaccion integer, transaccion_anulacion integer, fecha_contabilizacion timestamp without time zone, fecha_anulacion timestamp without time zone, fecha_contabilizacion_anulacion timestamp without time zone, base character varying, last_update timestamp without time zone, user_update character varying, creation_date timestamp without time zone, creation_user character varying, fecha_probable_pago date, flujo character varying, rif character varying, cmc character varying, usuario_anulo character varying, formato character varying, agencia_impresion character varying, periodo character varying, valor_tasa_remesa numeric, negasoc character varying, num_doc_fen character varying, obs character varying, pagado_fenalco character varying, corficolombiana character varying, tipo_ref1 character varying, ref1 text, tipo_ref2 character varying, ref2 text, dstrct_ultimo_ingreso character varying, tipo_documento_ultimo_ingreso character varying, num_ingreso_ultimo_ingreso character varying, item_ultimo_ingreso integer, fec_envio_fiducia timestamp without time zone, nit_enviado_fiducia character varying, tipo_referencia_1 character varying, referencia_1 character varying, tipo_referencia_2 character varying, referencia_2 character varying, tipo_referencia_3 character varying, referencia_3 character varying, nc_traslado character varying, fecha_nc_traslado timestamp without time zone, tipo_nc character varying, numero_nc character varying, factura_traslado character varying, factoring_formula_aplicada character varying, nit_endoso character varying, devuelta character varying, fc_eca character varying, fc_bonificacion character varying, indicador_bonificacion character varying, fi_bonificacion character varying, endoso_fenalco character varying, cxc_traslado character varying);

ALTER TABLE con.factura_dblink
  OWNER TO postgres;
